- build.sbt
- modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/sbt.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/util.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/sbtTest.scala
- project/Dependencies.scala
This splits `Update` into two cases, `Single` and `Group`, so that we can group updates that differ only in their `artifactId` can be applied at the same time.
closes: #25
> Apply updates that differ only in their artifactId at the same time

- build.sbt
- modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/sbt.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/util.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/sbtTest.scala
- project/Dependencies.scala
Reverts fthomas/scala-steward#32
> Revert 32 topic/lockstep updates

- modules/core/src/main/scala/eu/timepit/scalasteward/NameResolver.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/gitLegacy.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/NameResolverTest.scala
This is a small follow-up to #68 that only includes the groupId
in the name if an artifactId is a common suffix. If no artifactId
is a common suffix, their names should be unambiguous enough.
I've also noted that `Update.name` is used for branch names, so we're
now using NameResolver only for commit messages and PR titles.
> Include groupId only if an artifactId is a common suffix

- modules/core/src/main/scala/eu/timepit/scalasteward/application/Context.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/NurtureAlg.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/json/JsonPullRequestRepo.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/json/PullRequestData.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/json/PullRequestStore.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/update/FilterAlg.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/update/UpdateService.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/github/data/NewPullRequestDataTest.scala
This is another part of #123 where we ignore updates if there is already an existing and up-to-date PR for an update. This should drastically reduce the number of repositories that need to be processed on each run.
> Ignore updates which have existing up-to-date PRs

- build.sbt
- modules/core/src/main/scala/eu/timepit/scalasteward/application/Config.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/application/Context.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/dependency/DependencyService.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/git/GitAlg.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/io/ProcessAlg.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/nurture/NurtureAlg.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/util/uri.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/git/GitAlgTest.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/io/MockProcessAlg.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/util/uriTest.scala
This changes how Git receives the password (or access token) of `gitHubLogin` for cloning, syncing, and pushing. Currently the password is part of the clone URL that is passed to Git. This means that the password is stored on disk in `.git/config` of each repository. This PR lets Git request the password via a [program in the `GIT_ASKPASS` environment variable](https://git-scm.com/docs/gitcredentials). The program used for this variable needs to be set in the `Config.gitAskPass` parameter.
> Do not use URLs with username and password for Git

- modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/sbt/parser.scala
- modules/core/src/main/scala/eu/timepit/scalasteward/update/FilterAlg.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
- modules/core/src/test/scala/eu/timepit/scalasteward/sbt/parserTest.scala
This parses [`configurations`](https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/ModuleID.html#configurations:Option[String]) from `dependencyUpdates` to skip updates that seem to be in most cases transitive dependencies of plugins.
> Use configurations to filter updates

- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
as seen here https://github.com/Slakah/uritemplate4s/pull/47
This bug was caused by the addition of `configurations` to
`Update.Single`.
> Prevent duplicated artifactIds in Update.Group

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/ConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- scripts/run.sh
This allows to set firejail's --whitelist and --read-only options
as command-line options of scala-steward.
> Add command-line options for firejail

- modules/core/src/main/scala/org/scalasteward/core/sbt/data/ArtificialProject.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
This does two things:
- it changes `ArtificialProject.halve` to also halve the project if it only contains libraries or plugins
- uses the former `divideOnError2` in `UpdateService.checkForUpdates` which now collect all updates even if one invocation of `sbtAlg.getUpdatesForProject` fails
The result is that `checkForUpdates` now caches more updates and does not discard updates if one of the updates check fails.
I'm sorry for the code quality of `ArtificialProject` and `UpdateService`. This will be improved later.
> Fix checkForUpdates

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- project/Dependencies.scala
better.files.File#delete() leaks file handles which can be observed
by watching `lsof | grep steward | wc -l` grow while steward runs.
With `FileUtils.forceDelete` the count of open files remains nearly
constant.
> Do not leak file handles in deleteForce

- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
Certain dependencies can't be checked for updates in a
`ArtificialProject` because they require settings in the build.
For example, com.ccadllc.cedi:build in `ArtificialProject` leads to the
following error:
```
References to undefined settings:
*:githubProject from *:pomExtra
((com.ccadllc.cedi.build.BuildSettings) BuildSettings.scala:147)
*:githubProject from *:githubHttpUrl
((com.ccadllc.cedi.build.BuildSettings) BuildSettings.scala:70)
```
So this ignores certain dependencies that cannot be checked for
an update when building up the updates cache.
> Ignore certain dependencies in the updates cache

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/ConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
My attempt to work on https://github.com/fthomas/scala-steward/issues/180 
I can get the tests to compile in my machine but the tests fail when they try to read files with test data like "create-fork.json"
Submitting this for initial feedback.
1. I need to figure out how to get the tests to pass in my machine
2. Need to write unit test for this new config flag.
3. I am using scalafmt 1.5.1 . I ran it against both src and test. Still I can't get past the scalafmtCheck in travis CI.
> Config for sandbox execution

- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
This tries to make the implementation of `separateBy` clearer by untangling the two loops that happen in the `loop` function. One loop constructs the inner `Nel[A]`s and the other constructs the outer `List[Nel[A]]`. The new implementation makes this clear by seaparating these two into the `innerLoop` and `outerLoop` functions. Unfortunately `innerLoop` is still quite complex.
> Make separateBy clearer

- .travis.yml
> Remove Travis CI stages

- modules/core/src/test/scala/org/scalasteward/core/MockState.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockWorkspaceAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/MockLogger.scala
By doing so we get `Sync[MockEnv]` and `MonadError[MockEnv, Throwable]` for free.
> Change MockEnv from State[MockState, A] to StateT[IO, MockState, A]

- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/EditAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
This extends the multi-step update strategy outlined in #236 to all
source files. That means we first try an update strategy on all source
files and stop if it changed any file. Only if it didn't change any file,
we'll try the next strategy and so on.
Also included is a relaxed update strategy that splits artifactIds by
hyphens and uses each part as a search term for updating the version
number. This helps in cases where there is an update for a single update
(e.g. for circe-parser) but the version is defined more generically
(e.g. `val circeVersion = "0.11.1"`).
The code is not pretty but will be improved once this idea proves to be
useful.
> Extend multi-step update strategy to all source files

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/DependencyPattern.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- project/Dependencies.scala
This implements repository specific configuration via a `.scala-steward.conf` file to ignore or only allow specific updates. [HOCON](https://github.com/lightbend/config/blob/master/HOCON.md) is used as format for this file. If a repository has `.scala-steward.conf` file in its root directory, scala-steward will read it and ignore updates according to the content therein.
Here is an example of a `.scala-steward.conf` file:
```hocon
updates.ignore = [
{ groupId = "com.typesafe.akka", artifactId = "akka-actor" },
{ groupId = "org.scalaz", artifactId = "scalaz-zio", version = "0.5" }
]
updates.allow = [
{ groupId = "org.http4s", version = "0.18" }
]
```
The objects of the `ignore` and `allow` lists are patterns that are matched against each update. `groupId` and `artifactId` are matched …
> Ignore updates via a repo-specific .scala-steward.conf file

- modules/core/src/main/scala/org/scalasteward/core/github/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/github/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This adds a `details` section to the PR body with a description of how to ignore updates using `.scala-steward.conf`.
A preview of this change can be seen here: https://github.com/fthomas/scala-steward/pull/302
> Add details section to PR about ignoring updates

- repos.md
we're very conservative about upgrading anything in this repo, so I probably
just shouldn't have added it in the first place.
> remove scala-dist

- build.sbt
This fixes an issue I've run across when building the docker image on CircleCI. I've tried many different things and setting the `DEBIAN_FRONTEND` to `interactive` in the DOCKERFILE during the build seems to be the only way I could get it to work.
```
[info] Setting up keyboard-configuration (1.164) ...
[info] debconf: unable to initialize frontend: Dialog
[info] debconf: (TERM is not set, so the dialog frontend is not usable.)
[info] debconf: falling back to frontend: Readline
[info] cat: '/sys/bus/usb/devices/*:*/bInterfaceClass': No such file or directory
[info] cat: '/sys/bus/usb/devices/*:*/bInterfaceSubClass': No such file or directory
[info] cat: '/sys/bus/usb/devices/*:*/bInterfaceProtocol': No such file or directory
[info] Configuring keyboard-configuration
[info] …
```
> Set DEBIAN_FRONTEND to noninteractive in docker build

- README.md
By mounting scala-steward directory into `/opt/docker` inside of the container, you overwrite all of the existing files including `/opt/docker/bin/scala-steward` and all the jars in `/opt/docker/lib/` which makes the container fail on startup (as the entry point script can no longer be executed).
I've updated the README to address this by mounting `$STEWARD_DIR` into `/opt/scala-steward` instead.
> Fix docker volume mounting in README.

- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
Having both only makes sense if we would be using `attemptLog` but we don't.
> Implement attemptLog_ directly without attemptLog

- repos.md
I am the maintainer of these 2 projects and would like to have scala-steward keep me informed of updated dependencies.
> support swagger-akka-http and swagger-scala-module

- modules/core/src/main/scala/org/scalasteward/core/github/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/github/package.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/github/data/NewPullRequestDataTest.scala
This uses Config.gitHubLogin as contact in the PR body if
Config.doNotFork is true. Prior to this change, the login of the repo
in which the PR was created was used in the body of PRs. But the login
in the PR body should be the account responsible for running the
scala-steward instance.
> Always use Config.gitHubLogin in PR body

- repos.md
I am not sure how scala-steward works and if it will work for sbt-catalyts. 
The versions I cared most are stored [here](https://github.com/typelevel/sbt-catalysts/blob/master/src/main/scala/org/typelevel/TypelevelDeps.scala), not even in the `build.sbt` file or in `project`
It's fine if steward doesn't know how to work with these versions at least I imagine it will update the plugin's own deps.
> attempt to include sbt-catalysts

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Add a flag `--ignore-opts-files`. This flag will enable the temporary deletion of .sbtopts and .jvmopts files (previously this PR was to have a flag `--disable-ignore-opts-files` to do the opposite).
See: #365 
Please let me know if there's anything amiss or any tests that I should probably add. Thanks!
> #365 Add --ignore-opts-files option

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- project/Dependencies.scala
This a fix for #384 and it builds on #387. 
I added tests for `RepoConfig`, but didn't find tests to simulate PR rebase and forced-pushes. 
This change preserves the previous behaviour, which is the PR is rebased when the bot detects that the current branch is behind upstream.
> Adds configuration settings to disable PR updates

- README.md
Makes copy pasting the examples less error-prone.
> escape multi line bash documentation

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
This gives scala-steward complete control over signing commits
regardless of a global "commit.gpgsign = true" setting.
> Use --no-gpg-sign option if signCommits is false

- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
This allows scala-steward to run the doobie build without running
into a SOE
> Create temporary .jvmopts to set stack size

- modules/core/src/main/scala/org/scalasteward/core/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/github/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/github/UrlTest.scala
If a repository changes its default branch, scala-steward wouldn't
create PRs of current updates for which PRs already exist against the
old base branch. Including the current base in the search for existing
PRs changes this behaviour.
This is in response to https://github.com/tpolecat/doobie/pull/863 where
scala-steward created PRs against on old default branch, all created PRs
were closed, and the default branch was updated. With this change
scala-steward recreated some of the closed PRs against the new
default branch.
> Include base branch when searching for existing PRs

- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
Hey there,
after adding some different test lines for ignore-comments test, i noticed i should have trimmed before checking if it starts with `//`. But nonetheless, here is the PR for it. Sorry for the inconvenience :sweat_smile: 
Cheers
> Extend ignore comments tests and fix a tiny bug

- repos.md
We will be archiving this repo soon. It can be removed from scala-steward already.
> Removes lagom-akka-discovery-service-locator

- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/util/string.scala
- modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
With this change `val hikariVersion = "3.3.0"` is found as version
definition for `"com.zaxxer" % "HikariCP"` because `HikariCP` is split
into `Hikari` and `CP` (which is discarded because it is shorter than
three characters).
> replaceAllInRelaxed: split camel case artifactIds

- README.md
We have dozens of teams & hundreds of people using Scala in their daily work at Zalando, so it was inevitable to set up scala-steward for internal purposes.
As a side note, it was incredibly easy to configure it, so huge thanks!
> Add Zalando to the list of companies

- repos.md
- it is now community maintained with very low frequency commits
- it's better for us to simply check for updates whenever someone
works on the code base
> remove scala-swing

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
> Ignore SNAPSHOT updates if current version is not already a SNAPSHOT

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/github/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/model/SemVer.scala
- modules/core/src/test/scala/org/scalasteward/core/github/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/model/SemVerTest.scala
- project/Dependencies.scala
This adds a simple `semver` label to PR bodies indicating the type of version bump according to [semantic versioning](https://semver.org/) if the current and next version adhere to the semver format.
For example if an update goes from 1.a.b to 2.x.y, scala-steward will add `labels: semver-major` to the PR body. It will add `labels: semver-minor` for bumps of the minor version and `labels: semver-patch` for bumps of the patch version.
This is the first step of a larger feature request @djspiewak mentioned on Gitter.
> Add a semver "label" to PRs

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
This makes it easier to compare them with updates of created
PRs which are already persisted without cross-version suffix.
> Remove cross-version suffix from artifactIds

- modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
This is another part of #123 where scala-steward ignores updates for which it already created PRs that where closed without merging. It also shows the `UpdateState` of each dependency in all repos.
> Ignore updates which have closed PR

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateData.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This is just an optimization to not repeatedly reading and parsing the
repository config when working on a repo.
> Read RepoConfig only once when updating a repo

- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/EditAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/EditAlgTest.scala
This is an optimization where the update heuristics are only tried
on files that contain the current version number. Since the heuristics
consists of non-trivial regular expressions, this has a significant effect
on large projects. In one instance applyUpdate now only takes ~1s
instead of ~30s.
> Only try to edit files that contain the current version

- modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
- modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
... to prevent PRs listed in https://github.com/fthomas/scala-steward/pull/545#issuecomment-499437250
This change drops the TLD from the groupId and only uses words that are
longer than three characters.
> Refine replaceAllInGroupId

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
This prevents errors like this:
```
[info] 2019-06-14 23:19:20,117 WARN  No files found that contain the current version
[info] 2019-06-14 23:19:20,148 INFO  Create branch update/scripted-plugin-1.1.6
[info] java.io.IOException: On branch update/scripted-plugin-1.1.6
[info] Untracked files:
[info]  project/project/
[info]  project/target/
[info]  target/
[info] nothing added to commit but untracked files present
```
> Ignore untracked files when checking if a repository has changes

- modules/core/src/main/scala/org/scalasteward/core/model/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/model/VersionTest.scala
So we don't have to care about really really long version numbers.
> Use BigInt instead of Long for the numeric parts of Version

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
The reason for this is to better distinguish what scala-steward
installed and everything else.
> Put all global sbt plugins in scala-steward.sbt

- modules/core/src/main/resources/StewardPlugin.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
This ignores dependencies of a repo which are not defined in the build
files but are introduced by plugins. This allows scala-steward to prune
more repositories it doesn't need to look at. Without this scala-steward
tried to update dependencies which were never defined in the build files
and therefore couldn't be updated.
> Ignore dependencies introduced by plugins

- modules/core/src/main/resources/StewardPlugin.scala
To prevent errors like this:
```
.sbt/1.0/plugins/StewardPlugin.scala:38:49: The evaluation of `scalaVersion` inside an anonymous function is prohibited.
[error]
[error] Problem: Task invocations inside anonymous functions are evaluated independently of whether the anonymous function is invoked or not.
[error]
[error] Solution:
[error]   1. Make `scalaVersion` evaluation explicit outside of the function body if you don't care about its evaluation.
[error]   2. Use a dynamic task to evaluate `scalaVersion` and pass that value as a parameter to an anonymous function.
[error]
[error]             CrossVersion(moduleId.crossVersion, scalaVersion.value, scalaBinaryVersion.value)
[error]                                                 ^
```
> Call .value outside of lambda

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/UrlTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/util/uriTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/PullRequestOutTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/RepoOutTest.scala
Just notice this while browsing the sources. Please, feel absolutely free to reject this PR.
> Tiny code tweaks

- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Environment variables are now prepended to MockState.commands entries.
This clarifies which environment variables are used for which command.
> Remove MockState.extraEnv

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
This fixes two issues. The first is a conflict between the globally
installed sbt-scalafix and sbt-scalafix comming from a repo that uses a
different version. Here is an example where scala-steward can't load a
build because of a conflict:
```
[info] Loading global plugins from /home/frank/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/frank/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Compiling 1 Scala source to /home/frank/.sbt/1.0/plugins/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] Loading settings for project recursionz-build-build from hack.sbt ...
[info] Loading project definition from /home/frank/scala-steward/workspace/repos/enzief/recursionz/project/project
[info] Updating …
```
> Install sbt-scalafix plugin only during migrations

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
This is interesting because there is not one but four rules for migrating to 0.7.0. `Migration` currently supports only one rule and needs to be updated for multiple rules.
Example PR: https://github.com/fthomas/scalafix-test/pull/11
closes #612, /cc @regadas
> Add Scalafix migrations for Scio 0.7.0

- repos.md
Due to the recent extraction of interop modules in separate repositories.
> Track ZIO's interops

- modules/core/src/main/resources/logback.xml
Attempting to fix #621 by env variables. These can be passed via cli ex: `-DLOG_LEVEL=DEBUG`, `-DROOT_LOG_LEVEL=DEBUG` and default to `INFO` logging
> Ability to set log level via env variables

- modules/core/src/main/scala/org/scalasteward/core/update/UpdateRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/main/scala/org/scalasteward/core/update/json/JsonUpdateRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/update/json/UpdateStore.scala
This should save a few cycles and reduce disk I/O.
> Optimize JsonUpdateRepository

- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
In Soviet Russia, @scala-steward gets pull requests from you!
> Simplify bindUntilTrue, evalFilter

- modules/core/src/main/scala/org/scalasteward/core/model/SemVer.scala
- modules/core/src/test/scala/org/scalasteward/core/model/SemVerTest.scala
Found an error in SemVer when going from `0.20.0-M3` to `0.20.3` was labelled `semver-patch` which does not seem consistent with https://semver.org/
Hopefully this doesn't affect the system in another way I don't expect
> Elevate pre release semver

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This will be useful for https://github.com/fthomas/scala-steward/issues/592
where we only want to cache actual `RepoConfig`s and not also the default
values.
> Split getRepoConfig into readRepoConfig{,OrDefault}

- repos.md
Since I have renamed https://github.com/Atry/Binding.scala-template to https://github.com/Atry/scalajs-all-in-one-template, also make change here
> Rename Binding.scala-template to scalajs-all-in-one-template

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/package.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/data/SbtVersion.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
Closes #101.
Steward will propose update if they found `sbt.version=X.Y.Z-SOMETHING`.
It does not update `SbtVersion` that used for conditional build like below
```scala
sbtSeries.value match {
case "0.13" => SbtVersion("0.13.17")
case "1.0"  => defaultSbtVersion
case _      => defaultSbtVersion
}
```
since such build requires cautious update.
I could not find how to perform system-test against actual repos...
How should I perform ?
> Add ability to propose sbt version update

- .travis.yml
- README.md
- build.sbt
- docs/running.md
- project/plugins.sbt
Based on the ask in #407 
This PR does the following:
* Set the tag of the sbt build docker image to be `latest` + version determine by [sbt-dynver](https://github.com/dwijnand/sbt-dynver).
* Docker image name updated to be `fthomas/scala-steward` (allows it to be published to dockerhub).
* Release stage added to `.travis.yml` which does a `docker login` using travis set environment variables `DOCKER_USER` and `DOCKER_PASS`. Changes to the travis build are inspired by 
other project https://github.com/fthomas/refined/blob/master/.travis.yml#L16 .
* Docker badge added to repo README.md
I tested the travis build [on my fork](https://github.com/slakah/scala-steward), the test run of the release job can be seen [on travis](https://travis-ci.org/Slakah/scala-steward/jobs/556422648).
The docker …
> Travis Publish Docker Image

- README.md
- docs/repo-specific-configuration.md
This PR adds a document about `.scala-steward.conf` fille.
It will be a basis for upcoming new features like https://github.com/fthomas/scala-steward/issues/678
> Document .scala-steward.conf

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/model/Dependency.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/json/JsonRepoCacheRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/json/RepoStore.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/data/ArtificialProject.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
- modules/core/src/main/scala/org/scalasteward/core/update/splitter.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/data/ArtificialProjectTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
Storing the sbt versions will be useful later to determine which repos
use an outdated sbt version.
> Rename DependencyService to RepoCacheAlg and store sbt versions

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
This includes sbt in the update check which prunes repositories so that
Scala Steward only looks at repositories where it does something.
With this change Scala Steward should update sbt in all repositories.
> Include sbt in update check

- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/json/JsonPullRequestRepo.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
When searching for already existing PRs, we need to take the newest
version number into account so that we don't find PRs that update
to older versions.
> Use nextVersion when looking for existing PRs

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/util/string.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Closes #192
Adding two markups to control lines to be ignored.
A line ends with `// scala-steward:off` is ignored solely.
```scala
"com.typesafe.akka" %% "akka-actor" % "2.4.0", // scala-steward:off
"com.typesafe.akka" %% "akka-testkit" % "2.4.0", // Update should happen on this line
```
Once a line starts with `// scala-steward:off` found, Steward won't edit lines until `scala-steward:on` found.
```scala
// scala-steward:off
"com.typesafe.akka" %% "akka-actor" % "2.4.0",
"com.typesafe.akka" %% "akka-testkit" % "2.4.0",
// scala-steward:on
"com.typesafe.akka" %% "akka-stream" % "2.4.0", // Update should happen on this line
```
A range markup like `// scala-steward:only 2.4.x` was suggested in #192. 
I think we do not need such, since sbt already supports [version range in the form of …
> Add markup to ignore lines

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
- modules/core/src/main/scala/org/scalasteward/core/util/Change.scala
- modules/core/src/main/scala/org/scalasteward/core/util/string.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/editTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/ChangeTest.scala
`Change` indicates if some input value has been changed or not. I think
it is clearer than using `Option` in `replaceSomeInOpt` where `Some`
meant that the input was changed. It is also used in the implementation
of `replaceSomeInAllowedParts` where we're making use of its monoid
instance.
The ultimate goal here was to give `replaceSomeInChange` and
`replaceSomeInAllowedParts` the same signature so that one is a drop-in
replacement for the other.
> Add Change datatype

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
This changes when Scala Steward updates pull requests. Prior to this
change PRs were updated when they were behind the base branch. This
resolved potential merge conflicts but could also flood CI systems if
there were multiple open PRs by Scala Steward. With this change, only
PRs which are actually in conflict with the base branch are updated.
This should dramatically reduce the number of times Scala Steward
triggers CI builds by updating PRs.
closes: #384
> Update PRs only if there are conflicts with the base branch

- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/sbtTest.scala
This will update sbt in all projects that use release candidates for 1.3.0.
> Set 1.3.0-RC3 as latest sbt RC for 1.3.0

- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
as discussed in #689, I also removed `parentRepoOutDecoder` as it's mostly the same with `repoOutDecoder`
@daddykotex
> Fix errors when running with gitlab repos owned by groups with --do-not-fork flag

- modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
its the first time I am using cats/fs2/http4s so maybe there is a simpler way to achieve the same.
I decided to re-throw the UnexpectedResponse in case of a match error so that I immediately see the obvious error (and not a MatchError)
> introduce UnexpectedResponse and recoverWith instead of handleErrorWith

- modules/core/src/main/scala/org/scalasteward/core/gitlab/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
I noticed that for Gitlab, Steward will consider an outdated MR with the wrong target branch. 
For Github it was already taken into account.
I could not test this patch properly yet (different setup home/work) but I can probably test it during the week.
> Filter Gitlab MRs on target branch

- build.sbt
Reason: Custom resolvers that are usually added in our CI pipeline before `sbt` starts, as well as adding certificates. This change allows me to build a base image with all that myself and use it to build the scala-steward docker image that'll work in my gitlab org.
Let me know if the name needs changing or there's anything else wrong with this ;)
> Allow using a custom base image for docker builds

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Closes #771 
Unfortunately, [`github:` scheme](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#using-github) is not available for `scalatest/autofix`, since the repository has their arbitrary project structure (multiple scala projects in sub directories), IIUC.
So used [`https:` schema](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#using-http) to support arbitrary project structure.
Also, used a SHA1-marked immutable reference as stated in https://github.com/fthomas/scala-steward/issues/626 for security consideration.
> Add scalafix migration for scalatest 3.1.0 

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
The current implementation of `UpdateHeuristic` is tightly coupled to
the existing heuristics. This reduces `UpdateHeuristic` to the bare minimum
required by `EditAlg` and allows to have implementations that are much
different to the already existing heuristics.
> Clean up UpdateHeuristic

- repos.md
Has been moved into Http4s and shims respectively.
> Remove Deprecated ChristopherDavenport Repos

- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
This PR updates the URL of scalafix rule for `cats v1.0.0` from https://raw.githubusercontent.com/fthomas/cats/update/scalafix/scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala to https://raw.githubusercontent.com/typelevel/cats/master/scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala
Currently, `update/scalafix` branch in `fthomas/cats` had already
deleted(?), and as a result, running scala-steward to the repository that contains an update for cats to v1.0.0 ends up with 404 error like this.
```
[error] (types / Compile / scalafix) scalafix.sbt.InvalidArgument: 404 -
not found
https://raw.githubusercontent.com/fthomas/cats/update/scalafix/scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala
```
> Update the url of scalafix rule for cats v1.0.0

- .travis.yml
Current Travis CI builds use a version that starts with "0.0.0" instead
of "0.3.0":
> [info] Packaging /home/travis/build/fthomas/scala-steward/modules/core/.jvm/target/scala-2.12/scala-steward-core_2.12-0.0.0-167-fe8f4da7.jar ...
I guess sbt-dynver can't correctly determine the version with a clone
depth of 50 (which is the default). This sets the git clone depth to
500 to fix the version.
> git clone with a depth of 500 to fix the version

- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
... and get the latest sha1 from the local clone instead of the Git repo
manager which could already be outdated by the time the repo is cloned.
> Split refreshCache into two functions

- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
This is a follow-up to https://github.com/fthomas/scala-steward/pull/814
It allows to check multiple possible compare URLs for existence. In
particular, it also supports tags without leading "v".
Example PR: https://github.com/fthomas/refined-sjs-example/pull/16
> Check multiple compare URLs

- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- project/Dependencies.scala
Follow-up of #762 and #814 
Improves handling incomplete `<scm>` reporeted in https://github.com/coursier/coursier/pull/1291#issuecomment-521518104
>  I've noticed that scm is None when developerConnection is missing in the POM. But not setting developerConnection seems to be common:
>```
><scm>
>   <url>https://github.com/typelevel/cats-effect</url>
>   <connection>git@github.com:typelevel/cats-effect.git</connection>
></scm>
>```
> Better handling scm url 

- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
When pruning repos, Scala Steward now takes into account if updates are
rejected by repo configuration. This will prevent Scala Steward from
unnecessarily working on repos where it determined that a dependency is
outdated but it was actually ignored by the repo config.
> Add update state UpdateRejectedByConfig

- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
bug reported at gitlab: https://gitlab.com/gitlab-org/gitlab-ee/issues/13050
> Gitlab 12.1.1 returns 404 instead of 409 (seems to be a bug)

- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/UtilTest.scala
> artifactIdCross does not need minor version

- modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Follow-up of #842 
https://github.com/fthomas/scala-steward/pull/842#issuecomment-522218941
>[info]   org.scalameta:scalafmt-core_2.12 : 2.0.0 -> 2.0.1
Temporary `scalafmt-core` dependency's artifact id is `scalafmt-core_2.12` (including scalaBinaryVersion) due to https://github.com/fthomas/scala-steward/blob/1718dc26c08df42caf8376bc761c92965218a25f/modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala#L178-L180
Therefore `UpdateHeuristic` for `scalafmt-core` does not work.
This PR makes the artifact id scalaBinaryVersion-agnostic for `scalafmt-core`.
So future updates for any Scala binary version (2.13, 2.14 or 3.0) should work.
Example PR
https://github.com/exoego/scala-steward-test-project/pull/77
> Remove scalaBinaryVersion from temporary scalafmt dependency.

- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
This should prevent errors like this:
```
[error] coursier.error.ResolutionError$CantDownloadModule:
Error downloading org.scalameta:scalafmt-core_2.12:1.5.1
```
Different groupIds means that Scala Steward won't propose updates
anymore if the scalafmt version is at 2.0.0-RC1.
> scalafmt-core prior to 2.0.0-RC2 used a different groupId

- modules/core/src/main/resources/StewardPlugin.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/io/package.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/UpdateServiceTest.scala
Closes #613
```sbt
"org.spire-math" %% "kind-projector" % "0.9.10" ->
"org.typelevel"  %% "kind-projector" % "0.10.0" 
```
Example PR  https://github.com/exoego/scala-steward-test-project/pull/91
```sbt
"com.geirsson"  %% "sbt-scalafmt" % "1.6.0-RC3" ->
"org.scalameta" %% "sbt-scalafmt" % "2.0.2"
```
Example PR https://github.com/exoego/scala-steward-test-project/pull/90
For 1st iteration, these old-to-newer relations are stored in `UpdateService.getNewerGroupId` and needs manually updated.
> Change groupId when dependencies published under a different groupId

- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
See https://github.com/typelevel/scalacheck/pull/498
> Add migration rule for (not yet released) scalacheck 1.14.1

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
We don't know if a dependency is only used in main sources or also in
test sources. So we now always run `scalafix $rule` and `test:scalafix
$rule` to not miss possible fixes in test sources.
> Always run Scalafix migrations for main and test sources

- modules/core/src/main/resources/StewardPlugin.scala
This fixes the following compilation error with sbt 0.13:
```
[error] /home/frank/.sbt/0.13/plugins/StewardPlugin.scala:68: value contains is not a member of Option[String]
[error]         && !moduleId.configurations.contains("plugin->default(compile)")   => false
[error]                                     ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```
> Fix compile error with sbt 0.13

- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
For the same reason as given in https://github.com/fthomas/scala-steward/pull/882.
It is also a workaround for https://github.com/fthomas/scala-steward/issues/888.
> Make HttpExistenceClient fail-safe

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
Reverts fthomas/scala-steward#878
That change caused quite a few errors that looked like this:
```
2019-09-09 15:14:58,601 INFO  ──────────── Nurture exoego/aws-sdk-scalajs-facade ────────────
2019-09-09 15:14:58,601 INFO  Clone and synchronize exoego/aws-sdk-scalajs-facade
2019-09-09 15:15:04,961 INFO  Find updates for exoego/aws-sdk-scalajs-facade
2019-09-09 15:17:07,322 INFO  Ignore org.scala-lang:scala-library:provided : 2.12.8 -> 2.12.9 -> 2.13.0 (reason: ignored globally)
2019-09-09 15:17:07,324 INFO  Found 3 updates:
ch.epfl.scala:sbt-scalajs-bundler : 0.15.0-0.6 -> 0.15.0
org.scalameta:scalafmt-core : 2.0.0 -> 2.0.1
org.xerial.sbt:sbt-sonatype : 2.5 -> 2.6 -> 3.6
2019-09-09 15:17:07,363 INFO  Process update ch.epfl.scala:sbt-scalajs-bundler : 0.15.0-0.6 -> 0.15.0
2019-09-09 …
```
> Revert "do not force push as it might overwrite other changes"

- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Closes #915 
`HttpExistenceClient` should return `true` only if http response status is 200.
This is necessary since some servers return 302 and then 200 for 404.html.
Example PR:
* scalaz (404) have no link https://github.com/exoego/scala-steward-test-project/pull/98
* groovy (302->200) have no link https://github.com/exoego/scala-steward-test-project/pull/97
* minitest (200) have link to GitHub release https://github.com/exoego/scala-steward-test-project/pull/99
> Do not include non-existent release note/changelog

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Dependencies are required to find URLs. If getting dependecies fails, it
should not prevent Scala Steward from creating the PR.
This is another source of errors which will be eliminated with #851.
> Ignore errors in memoizedGetDependencies

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/GitHubRepoAlgTest.scala
The default branch is the only branch required from the upstream repo
for syncing Scala Steward's fork. Working on large repos with many
branches will be a lot faster with this change.
> Fetch only default branch when syncing the fork

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
This banner is now printed at the start of the application:
```
2019-09-15 20:32:54,029 INFO
____            _         ____  _                             _
/ ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
\___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
|____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
v0.4.0-1-5653f7f0-20190915-1731
```
This is obviously a very important enhancement! :-)
The banner was generated by http://patorjk.com/software/taag/#p=display&f=Standard&t=Scala%20Steward
> Print banner at start of application

- build.sbt
java.lang.Throwable: Required option --workspace not specified
Required option --repos-file not specified
Required option --git-author-email not specified
Required option --vcs-login not specified
Required option --git-ask-pass not specified
at org.scalasteward.core.application.Cli.$anonfun$parseArgs$7(Cli.scala:33)
at cats.syntax.EitherOps$.bimap$extension(either.scala:128)
at org.scalasteward.core.application.Cli.parseArgs(Cli.scala:33)
at org.scalasteward.core.application.Context$.create(Context.scala:48)
at org.scalasteward.core.Main$.run(Main.scala:24)
at cats.effect.IOApp.$anonfun$main$3(IOApp.scala:67)
at cats.effect.internals.IOAppPlatform$.mainFiber(IOAppPlatform.scala:36)
at cats.effect.internals.IOAppPlatform$.main(IOAppPlatform.scala:24)
at …
> Update scala-steward permissions in docker container

- repos.md
We're starting a new project and we'd like to use Scala Steward for it. Thank you.
> Add avast/scala-server-toolkit to repos.md

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/update/ExcludeAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
If `pruneRepos` is `true`, Scala Steward will check all dependencies of
all repos for newer versions to decide on which repos it needs to be
working on. If a dependency can't be checked for updates with
`SbtAlg.getUpdatesForProject`, the whole update check is slowed down
considerably because of the way `UpdateAlg.checkForUpdates` is currently
implemented. Before this change, there was a static list of dependencies
that should be excluded from the update check to speed it up. With this
change this list is now dynamic and it excludes dependencies that
can't be checked for updates for 21 days from the update check. After
that period they are checked again for updates and if that fails again,
they'll be exluded again for the next 21 days.
> Automatically exclude dependencies from update check

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
This is a temporary workaround for https://github.com/fthomas/scala-steward/issues/980
> Use 2.12 for Scalafix migrations

- modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
Closes #790 
This PR should wait until [scalatest/autofix](https://github.com/scalatest/autofix) releases its stable version.
> Update scalafix for scalatest

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
If `--prune-repos=true`, Scala Steward checks for every repository if
their `RepoCache` is still fresh and refreshes it if necessary. A cache
refresh calls sbt to get a list of all dependencies and is therefore a
costly operation. There are some repositories for which the refresh
fails because of a broken build. These broken repos slow down Steward
because it tries to refresh them on every run. With this change, the
caches of those repositores are not refreshed for 7 days. Note that the
caches are not invalidated if there is an error during the refresh.
> Do not refresh caches of failing repos

- README.md
I'm working for Rewards Network and, as I mentioned on Gitter earlier this week, we started using it in a gradual capacity. Hopefully within the next couple of months it becomes standard for all new projects. Right now we're using it on about ~5-6 or so on our internal repositories.
> Add Rewards Network to companies using Scala Steward

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
This contains code from #851 for preventing updates to a pre-release of
another version series. Version.selectNext is now responsible for
selecting the next version from a list of possible newer versions. This
functions implements the scheme described in
https://github.com/fthomas/scala-steward/blob/master/docs/faq.md#how-does-scala-steward-decide-what-version-it-is-updating-to
and also filters out all bumps between pre-releases of different version
series. This code incidentally also makes the code to deal with updates
from non-snapshot to snapshot versions (#485) superfluous.
Closes #956.
>  Prevent updates to a pre-release of another series

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
The latest version is 3.2.2 and was released in 2015.
See also https://search.maven.org/search?q=g:commons-collections%20AND%20a:commons-collections&core=gav
> Prevent updates to commons-collections 20040102.233541

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/util/string.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This allows to make 1.0.0-20131213005945 (which is a pre-release version) less than 1.0.0. The `numericComponents` we hade before, couldn't accomplish that.
> Introduce Version.Component to improve Order[Version]

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
With #1009 we can simplify FilterAlg.badVersions since some of the
updates prevented by it are now prevented by selectSuitableNextVersion.
> Simplify FilterAlg.badVersions

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This change allows updates from e.g. 8.0.192-R14 to 12.0.2-R18 (where
the 'R' stands for Release). It is currently not allowed because the
hyphen in the version number makes it a pre-release version and we
don't allow updates to a pre-release of a different version series.
With this change we require that the version acually contains a
pre-release identifier like RC, SNAPSHOT, or alpha to be considered a
pre-release version.
> Only consider versions with pre-release identifiers as pre-releases

- modules/core/src/main/resources/StewardPlugin.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
This adds `sbtVersion` and `scalaVersion` attributes to
`coursier.Dependency` to correctly resolve POMs of sbt plugins. With
this change, Scala Steward shows the SCM URL or homepage in the PR body
of sbt plugins that are on Maven Central.
Here is a PR of sbt-sonatype before this change:
https://github.com/fthomas/refined-sjs-example/pull/57
and here with this change:
https://github.com/fthomas/refined-sjs-example/pull/63
> Resolve POMs of sbt plugins

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
As discussed in Gitter. 
because GroupId heuristic filters search terms containing 3 or less characters, organisations like Sky, BBc, etc. get dropped and not updated (unless using variables for their versions).
> add heuristic taking into account org type for short group ids

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
This extracts a generic `takeUntil` stream combinator from `processUpdates`.
This isn't strictly necessary - it is just that I enjoy writing stream combinators. :smiley:
> Add takeUntil stream combinator

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
The reason for this change is to have "2.0.0-RC4" < "2.0.0-RC4-1".
It also brings our version ordering closer to the ordering used in
Coursier: https://get-coursier.io/docs/other-version-handling.html#ordering
> Ignore separators when comparing versions

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
The `Option` here  isn't necessary since a `None` always produced an
empty result without running any effects.
> Do not use Option for repoUrl parameters in VCSExtraAlg

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- project/Dependencies.scala
This adds an in-memory cache to HttpExistenceClient which caches the
status codes of HEAD requests it does. The effect of this cache is that
repeated calls to `VCSExtraAlg.getReleaseNoteUrl` for example now only
take a few milliseconds:
```scala
scala> dateTimeAlg.timed(vcsExtraAlg.getReleaseNoteUrl("https://github.com/fthomas/refined", data.Update.Single(data.GroupId("eu.timepit"), "refined", "0.9.9", Nel.of("0.9.10")))).unsafeRunSync
res0: (Option[String], scala.concurrent.duration.FiniteDuration) =
(Some(https://github.com/fthomas/refined/releases/tag/v0.9.10),7997 milliseconds)
scala> dateTimeAlg.timed(vcsExtraAlg.getReleaseNoteUrl("https://github.com/fthomas/refined", data.Update.Single(data.GroupId("eu.timepit"), "refined", "0.9.9", Nel.of("0.9.10")))).unsafeRunSync
res1: …
```
> Add in-memory cache to HttpExistenceClient

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
This adds a `SelfCheckAlg` which is used to run self checks at program
start. The intention of these self checks is to check that components
work correctly before they are used later in the program. This should
help users tweaking the environment until all components work as
expected. For now it only includes a check of HttpExistenceClient which
might need additional JVM properties if Scala Steward is operated behind
a proxy server.
> Run self checks at program start

- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
When looking for version diffs and release notes we now also check URLs
that contain tags like `release-$version`.
ScalaTest uses this scheme for their tags. Here is an example PR that
now includes links to the version diff and release notes because of this
change: https://github.com/fthomas/refined-sjs-example/pull/67
> Add "release-$version" as possible tag for diffs and release notes

- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
`CHANGES.md` is used by Monix for example:
https://github.com/fthomas/refined-sjs-example/pull/69
Without this, we link to `RELEASES.md` (which describes Monix'
release process):
https://github.com/softwaremill/bootzooka/pull/206
> Add CHANGES as basename of possible changelog filenames

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
To allow updates from 2.0.0.AM4 to 2.0.0, for example.
This identifier is used by [org.apache.directory.api:api-all](https://mvnrepository.com/artifact/org.apache.directory.api/api-all) and I assume
it designates a milestone release. But I've no idea what the 'A' stands
for. If somebody has an idea, please let me know.
> Treat 'AM' as pre-release identifier

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
See https://github.com/scala-js/scala-js/issues/3865.
> Mark Scala.js 0.6.30 as bad

- modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestState.scala
Hi,
according to this issue:
https://github.com/fthomas/scala-steward/issues/1100
In this PR I added a toLowerCase method inside the PullRequestState decoder to parse correctly the "OPEN" state of Bitbucket Server.
I added the declined state to match as a closed state
Regards,
Andrea
> Bitbucket server pull request state should be case sensitive

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Reverts fthomas/scala-steward#985. That PR was meant as a temporary workaround and I hope this isn't necessary anymore since there have been a few new Scalafix and Scalameta versions since then.
> Revert "Use 2.12 for Scalafix migrations"

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
With this change StewardPlugin.scala is compiled as part of the sbt
build and IDEs recognize this file now as proper source file.
> Move StewardPlugin in new plugin subproject

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/data/ArtificialProject.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/data/ArtificialProjectTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
This contains the changes to StewardPlugin from #851 without the other
changes to the core module. I'm more comfortable digesting the changes
of #851 in piecemeal.
The advantage of this change is that we get rid of the parser for the
dependencyUpdates task, that we get more newer versions from
sbt-updates, and that we don't need to set dependencyUpdatesFailBuild
any more because dependencyUpdatesData is not using it.
> New StewardPlugin tasks, attempt 2

- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
If a program created by `process.slurp` outputs a lot of lines, the
internal line buffer can grow until there is no more available heap
space and an OOME occurs. I've observed this with a Scalafix migration
that printed a lot of stack traces.
To prevent OOMEs we put an upper bound on the number of lines we're
storing by using the new `appendBounded`.
> Do not grow line buffer in slurp unbounded

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
This is another change inspired by #851 that removes
`RepoCacheRepository` from `SbtAlg`. In `getUpdatesForRepo` we also
need the dependencies of the repo to find updates that change the
groupId. Prior to this change, `RepoCacheRepository` was used to get the
dependencies. The disadvantage of this approach was, that it required a
fresh cache but the cache is only populated and fresh if
`--prune-repos=true`.
We now query sbt for dependencies and updates at the same time so there
is no more need for the `RepoCacheRepository` and updates with a new
groupId are now also reported if `--prune-repos=false`.
> Do not use RepoCacheRepository in SbtAlg

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
... if the current version is not a dynamic version. With this change
1.2.0+17-7ef98061 is not a suitable next version for 1.2.0. So we now
treat dynamic versions like 1.2.0+17-7ef98061 similar to snapshot
versions.
> Do not select a dynamic version as next version

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
This method was called in two places before but now it is only used
`getDependencies` so we can inline it there.
> Inline SbtAlg.getOriginalDependencies

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
... if the current version does not contain one. This is similar to
https://github.com/fthomas/scala-steward/pull/1134.
`selectNext` currently allows these updates:
```
org.specs2:specs2-core:test : 4.5.1 -> 4.5.1-924020314
io.monix:monix-catnap : 3.1.0 -> 3.1.0-2156c0e
io.monix:monix : 3.0.0 -> 3.0.0-ec266e1
com.lihaoyi:ammonite : 1.6.7 -> 1.6.7-2-c28002d
com.lihaoyi:ammonite-ops : 1.6.6 -> 1.6.6-10-5fa74ab
com.lightbend.paradox:sbt-paradox-project-info : 1.1.3 -> 9-6845d95d
commons-httpclient:commons-httpclient : 2.0.2 -> 2.0-dev.20020705.071400
org.specs2:specs2-core : 4.2.0 -> 4.2.0-add90d25e-20180428143534
```
All of these look like a transition from a release version to a dynamic
version except that these version numbers don't use `+` but a `-` to
separate the dynamic part from the …
> Do not select versions with a hyphen

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This prevents updates like this:
`org.choco-solver:choco-solver : 4.10.2 -> %5BWARNING%5D`
`%5BWARNING%5D` is my new favorite version number since working on Scala
Steward. :-)
> Only select versions that start with a letter or digit

- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
The default TTL of Coursier's FileCache is 24 hours. Now that we're
using Coursier to find new versions, 24 hours is too long since the
runtime of my public instance is about 5-6 hours. If the TTL is greater
than that, Scala Steward could prune repos that have updates available.
This PR sets the TTL to 1 hour. This is fine for my public instance and
I assume that nobody runs Scala Steward more frequent than once per hour.
> Set TTL of Coursier's FileCache to 1 hour

- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
Update.Group.artifactId tries to find the "main" artifactId and should
only be used if really necessary. This is definitely not the case for
sorting updates.
> Don't use Update.Group.artifactId for sorting updates

- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
... to better distinguish it from Update.Single.artifactId.
> Rename Update.artifactId to mainArtifactId

- modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
Using show in combination with "+" issues this warning sometimes:
```
[warn] Issuing a cross building command, but not all sub projects have
the same cross build configuration. This could result in subprojects
cross building against Scala versions that they are not compatible with.
Try issuing cross building command with tasks instead, since sbt will be
able to ensure that cross building is only done using configured project
and Scala version combinations that are configured.
```
In this case, `+ show stewardDependencies` only list dependencies
for `scalaVersion`. Not using show and printing in our tasks directly,
seems to have the desired effect of displaying dependencies for all
`crossScalaVersions`.
> Do not use show to display the output of sbt tasks

- modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Closes #404 
Added the below labels
* `sbt-plugin-update`
* sbt plugins,  example PRs: [scala-js](https://github.com/exoego/scala-steward-test-project/pull/113) and [sbt-salafmt](https://github.com/exoego/scala-steward-test-project/pull/115)
* scalafmt versions in `.scalafmt.conf`, example PR: https://github.com/exoego/scala-steward-test-project/pull/116
* sbt itself, example PR: https://github.com/exoego/scala-steward-test-project/pull/104
* `test-library-update`
* Example PRs: [scalatest](https://github.com/exoego/scala-steward-test-project/pull/119) and [scalacheck](https://github.com/exoego/scala-steward-test-project/pull/118)
* Otherwise `library-update`
* Example PRs: [circe](https://github.com/exoego/scala-steward-test-project/pull/111) and …
> Label PR so users can automate their workflow depending on update type.

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/data/DependencyInfo.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
For each dependency in a repository we now also cache the files that
contain its current version number. This is then used in PruningAlg
to discard dependencies whose version is not in any file. We don't need
to check for an update of a dependency if we can't bump the version
number later. This change will prune more repositories.
If pruning is the default, we will be able to use this file list later
in EditAlg instead of computing it there again.
> Only check dependencies whose version is in source files

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
These are not needed anymore because sbt and scalafmt-core are included
as dependencies.
> Remove sbt and scalafmt version from RepoCache

- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This prevents errors like this in `HttpExistenceClient`:
```
org.http4s.ParseFailure: Invalid URI: Invalid input '{', expected Pchar, '/', '?', '#' or 'EOI' (line 1, column 29):
https://github.com/JodaOrg/${joda.artifactId}/compare/v2.2.0...v2.2.1
```
> Use Uri as return type of CoursierAlg.getArtifactUrl

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
My main motivation for this change is that 42.2.9.jre7 is now < 42.2.9
which is also consistent with sbt-updates' ordering.
> Tweak version ordering so that it is more similar to Coursier's

- build.sbt
This makes runSteward independent of where the repo is checked out
locally.
> Use baseDirectory in runSteward sbt task

- docs/running.md
When using a `!` in your password, `echo $PASSWORD` will not work, it needs to be escaped.
I've updated the example in the documentation.
> Allow special characters in passwords to work

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
If #1209 is merged, our own `Order[Version]` will become more important.
To prevent that it does something stupid, this adds a double-check which
uses coursier.core.Version to verify that the next version of an update
is greater than the current. Once our own ordering is battle-tested
enough, this can be removed again.
> Use Coursier to double-check our version ordering

- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Reverts fthomas/scala-steward#1202
This is a nice change in theory, but I think this makes it more likely that Scala Steward gets blacklisted by Maven Central.
> Revert "Parallelize UpdateAlg.findUpdate"

- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Reverts fthomas/scala-steward#1215
It seems that checking for updates sequentially didn't help with not being blacklisted by Maven Central. Other services are also seeing 403s from Maven Central (see https://twitter.com/dwijnand/status/1213406224450048001), so maybe it is not entirely Scala Steward's fault.
I'll now trying out the [Maven Central mirror on Google Cloud Storage](https://cloudplatform.googleblog.com/2015/11/faster-builds-for-Java-developers-with-Maven-Central-mirror.html) via [Coursier's mirrors mechanism](https://get-coursier.io/blog/2019/07/05/1.1.0-M14.html#mirrors):
```
~$ cat .config/coursier/mirror.properties 
gcs-maven-central.from=https://repo1.maven.org/maven2
gcs-maven-central.to=https://maven-central.storage-download.googleapis.com/repos/central/data/
```
> Revert "Revert "Parallelize UpdateAlg.findUpdate""

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Such that we agree with Coursier that "1.7R5" is less than "1.7.11".
> Sort alpha components before non-zero numeric ones

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/RateLimiter.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
Scala Steward has become so fast that it is now frequently being
blacklisted by Maven Central despite using Coursier's caching layer.
Previous attempts to prevent that (#1215 and #1216) were't successful
so I'm now trying to limit the rate of calls to Coursier that
potentially result in a call to Maven Central.
> Throttle (concurrent) requests to Maven Central

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/RateLimiter.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
The same rationale as for #1218 applies here too. Our own versions cache
allows for a more fine-grained control of which calls to Coursier (and
therefore potentially to Maven Central) are rate limited. Since we are
using the same TTL for our cache and for Coursier's cache, our cache
should be as fresh as Coursier's.
The previous rate limiting could result in limited calls that hit
Coursier's cache and unlimited calls that missed Coursier's cache.
This won't happen with this implementation. So we're faster now and
reduce the chance of being blacklisted by Maven Central again.
> Add our own versions cache

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCache.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/VersionsCacheAlg.scala
- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
This changes two things:
* `stewardResolvers` now uses `fullResolvers` instead of `resolvers`
* `CoursierAlg.getVersions` doesn't use any default resolvers
That means that `getVersions` now uses exactly the same Maven repositories
as used in the build.
> Don't use default resolvers for getting versions

- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
The same as #1236 but for `CoursierAlg.getArtifactUrl`.
Prerequisite for #1088.
> Don't use default resolvers for finding artifact URL

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
Without it, we don't find updates for sbt or scalafmt.
> Use resolver in SbtAlg.findAdditionalUpdates

- modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala
- modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Scala Steward is still regularly blocked by Maven Central and I'm now
experimenting with a few things that might help reducing traffic. I'd be
surprised if this would make a difference (because sbt shouldn't need to
hit the internet just for printing dependencies) but I'm trying it
nonetheless.
> Run sbt in offline mode when querying dependencies

- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
I have a project (Gitlab) which is currently resolved by scala-steward as follows 
```
https://gitlab.redacted.com/api/v4/projects/Redacted%20Products%2Fsome-service/repository/branches/master
```
which results in a `org.scalasteward.core.util.UnexpectedResponse` with 404.
The correct url should be 
```
https://gitlab.redacted.com/api/v4/projects/redacted%2Fsome-service/repository/branches/master
```
The Gitlab `/project/:id` response from the API looks as follows:
```
{ 
"id":10,
"name":"Redacted Products",
"path":"redacted",
"kind":"group",
"full_path":"redacted",
"parent_id":null,
"avatar_url":"/uploads/-/system/group/avatar/10/redacted.png",
"web_url":"https://gitlab.redacted.com/groups/redacted"
}
```
Currently, Scala Steward looks for the path of the project under `name`, but it …
> Bugfix: wrong Gitlab project URL

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- scripts/run.sh
Versions are now again cached by `VersionsCache` to better control when
a request to a remote repository happens (see https://github.com/fthomas/scala-steward/pull/1259#issuecomment-579591682 for a reason why we want to do this).
This partly reverts the changes of https://github.com/fthomas/scala-steward/pull/1241.
An improvement over the last time we cached the versions ourself is that
we are now taking resolvers into account. Ignoring resolvers was one of
the main motivations for creating #1241 in the first place.
> Cache versions again

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
This allows the same workspace to be used for multiple Scala Steward
instances that use different Git repo manager.
> Add Git repo manager as prefix to key value stores

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
The behavior of "allow" really confuse me, in document:
```properties
updates.allow  = [ { groupId = "com.example" } ]
```
> The only dependencies which match the given pattern are updated.
I thought it should filler out everything else not in the "allow" list
But the current behavior is
When there are 3 artifacts
```scala
val update1 = Single("org.http4s" % "http4s-dsl" % "0.17.0", Nel.of("0.18.0"))
val update2 = Single("eu.timepit" % "refined" % "0.8.0", Nel.of("0.8.1"))
val shouldNotAllow = Single("abc.def" % "ghi" % "0.8.0", Nel.of("0.8.1"))
```
And the rules is
```
allow = List(
UpdatePattern(update1.groupId, None, Some("0.17")),
UpdatePattern(update2.groupId, Some("refined"), Some("0.8"))
)
```
the artifacts after filter is `update1` and `shouldNotAllow`
but the group id of …
> should "allow" behave like white list?

- docs/faq.md
- docs/repo-specific-configuration.md
Improve the wording of the documentation after the merge of #1254
The FAQ entry  added in #1275 should mention `pin` not `allow` after  #1229 
I tried to rephrase the docs in the `Repository-specific configuration`. 
Feel free to ignore or further change them.
> Improve the wording of the documentation

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
This persists errors when checking for new versions so that we can check
artifacts that we have never seen in a repository less frequently.
The aim here is to reduce network traffic and to make finding versions
faster.
> Check artifacts that are not in a repository less frequently

- .mergify.yml
I just installed mergify on my own repos and figured out, that the file here didn't work for me, because I still used the legacy version of travis. The added comment would have saved me some time.
Furthermore I think it makes sense to:
- enable strict merging (https://doc.mergify.io/merge-action.html?highlight=strict#strict-merge)
- set the merge method to squash to avoid unnecessary merge bubbles in the commit history
> Mergify: method squash, strict mode, add travis legacy comment

- modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
Hi,
In this PR I implemented the getBranch method into the Bitbucket Server algebra that since now was throwing a NotImplemented exception.
I changed the `UserOut(user.login)` to `UserOut(repo.owner)` because in Bitbucket server the repo owner is not the username but the project name and this impact on the URI generation.
Thanks, Andrea
> Implement getBranch for bitbucket server

- modules/core/src/main/scala/org/scalasteward/core/io/package.scala
There is no good reason to edit only `.travis.yml` files bot not other
YAML files that are used by other CI providers like CircleCI or GitHub
Actions.
> Allow editing all .yml files and not only .travis.yml

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
This PR implements the idea proposed by @fthomas in a [comment](https://github.com/fthomas/scala-steward/issues/1038#issuecomment-543178540) to issue #1038:
> `UpdatePattern`, which is used for `.scala-steward.conf`, allows to match versions but only via `startsWith`. In this case we want to match a version if it ends with `jre8`. I would propose to change the version matching code to `endsWith` when `UpdatePattern.version` starts with `.*`.
After finishing this I realised one shortcoming: it is not possible to restrict  for the same artefact the prefix and the suffix. E.g pin a major version and enforce `jre8`. One solution would be to use `.*` as a separator between prefix and suffix, e.g. `7..*jre8` (there are 2 dots so it matches only against version 7 and not against version 70) …
> Support version suffixes in `UpdatePattern`

- modules/core/src/main/scala/org/scalasteward/core/data/ReleaseRelatedUrl.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
> Include all release related links in PR body

- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
The slug used to be picked from the `name` key in the `https://gitlab.com/api/v4/projects/:project_id` response, however this path refers to the human-readable name and not the actual slug, which is the `path` key (see image below)
This MR fixes it.
Edit: a little more context, when trying to start the project on a Gitlab instance, the URL generation for the default branch would yield an incorrect result because it would try to build it from the human-readable name, see the log below
```
[info] 2020-02-12 15:09:12,176 INFO   
[info]   ____            _         ____  _                             _
[info]  / ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
[info]  \___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
[info]   ___) | (_| (_| | | (_| |  ___) | || …
```
> Fix Gitlab repository url generation

- modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
The list of versions can contain duplicates if the dependency is provided
by two or more resolvers.
> Remove duplicated versions in VersionsCache

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/DateTimeAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/Timestamp.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
This is in preparation for #1316. We store the timestamp when a
`PullRequestData` is created for the first time. This can later be
used to determine the duration since the last created pull request.
> Store timestamp when a PullRequestData is created

- build.sbt
- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/Timestamp.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- project/Dependencies.scala
This PR adds a new `pullRequests.frequency` option to `.scala-steward.conf` files which can be used to control how often or when Scala Steward is allowed to create pull requests. Possible values of this option are `@asap` (default), `@daily`, `@weekly`, `@monthly`, or a [cron4s](https://www.alonsodomin.me/cron4s/) compatible CRON expression. The effects of these values are explained in [repo-specific-configuration.md](https://github.com/fthomas/scala-steward/blob/aaa4284fb1fcaef6f083c8f8b412c1e4cd2b8470/docs/repo-specific-configuration.md).
Some example configs:
```hocon
pullRequests.frequency = "* * ? * mon-fri"
pullRequests.frequency = "@weekly"
pullRequests.frequency = "0 8 ? * MON"
```
Note that this option does not affect the number of pull requests Scala Steward creates when it is …
> Add config to specify how frequent PRs are created

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This makes `PullRequests.frequency` an optional field so that the
default value is not persisted in `RepoCache` if that field is not set
by the user.
If the default is persisted now, it can't be easily changed later.
> Make frequency an optional field

- .gitignore
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
It appears that the first version of [NeQuissimus/sort-imports](https://github.com/NeQuissimus/sort-imports) scalafix rule was published with an incorrect version back in June [36845576](https://search.maven.org/artifact/com.nequissimus/sort-imports_2.12), which is getting picked up by Scala Steward as the latest version. See the following PR https://github.com/beautiful-scala/sbt-scalastyle/pull/13.
Could this version be ignored globally by Scala Steward?
cc @NeQuissimus
> Mark com.nequissimus:sort-imports:36845576 as an invalid version.

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Zero or a negative integer doesn't make sense for updates.limit so we
reflect this in the type.
> Use PosInt as type for updates.limit

- build.sbt
- docs/running.md
This PR changes docker base image from debian`openjdk:8` to alpine `openjdk:8-jre-alpine`.
The motivation was to reduce the resulting image size. 
I replaced JDK with JRE since neither sbt nor scalac require JDK.
I also removed `firejail` from image and  put `--disable-sandbox` to docker entrypoint args to fix #347.
The resulting image size is reduced from 1.06GB to 208MB.
> Optimize docker image size

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
Wraps decoding errors into a case calls including uri and method. It makes it possible to identify the origin of the error.
The error I got on my CI server:
<details>
```
org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON: empty body
at org.http4s.jawn.JawnInstances$.defaultJawnEmptyBodyMessage(JawnInstances.scala:42)
at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage(JawnInstances.scala:17)
at org.http4s.jawn.JawnInstances.jawnEmptyBodyMessage$(JawnInstances.scala:16)
at org.http4s.circe.package$.jawnEmptyBodyMessage(package.scala:3)
at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:41)
at scala.util.Either.flatMap(Either.scala:352)
at cats.data.EitherT.$anonfun$subflatMap$1(EitherT.scala:365)
at …
```
> add context to json paring errors

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
I added the ability, for bitbucket server only, to use the default reviewers configured in the repository settings.
I just call the default-reviewers API of Bitbucket and add the list of the reviewer to the PR input.
Here the documentation:
https://docs.atlassian.com/bitbucket-server/rest/6.10.0/bitbucket-default-reviewers-rest.html
The feature can be enabled with the flag --use-default-reviewers that by default is set to false.
> Add the ability to use default reviewers to bitbucket server

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Attempts a stab at #145 by introducing a flag `updates.includeScala` which when set to true (default: false) updates scala version as well
Tested this on a personal repo and it works, although needs some more work to update unit tests and docs (and of course a thorough review since I still feel new to the codebase)
> Update scala version

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
aaa4284fb1fcaef6f083c8f8b412c1e4cd2b8470 changed the parser for
`CronExpr` to only support expressions with 5 fields. Unfortunately I
forget to update the encoder to also emit only 5 fields. So the current
encoder/decoder pair doesn't round-trip which means we can't read
`RepoConfig`s with a cron expression that were serialized by
`RepoCacheAlg`.
This PR fixes round-tripping of the `PullRequestFrequency` encoder/decoder
by also allowing cron expressions with 6 fields.
> Fix round-tripping of PullRequestsFrequency codec

- docs/running.md
Based on discussion here: https://gitter.im/fthomas/scala-steward?at=5ea312d89a04a259f22df0e5
The SBT_CREDENTIALS thing I mentioned in the message thread was a red herring. Getting the path correct like I noted in the docs works reliably for our internal repos.
> Docs: Using a credentials.sbt file for private artifacts

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Include them only in the PR, if they exist.
( I didn't perform the filtering before generating the release related URLs. But I'm not sure about that)
fixes #1403
> check for all artifact URLs return by coursier, if they exists.

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
This means that `scalap` won't be updated unless `updates.includeScala`
is set to `true`.
See https://github.com/scalameta/scalameta/pull/2037#discussion_r416408389
> Mark org.scala-lang:scalap as Scala dependency

- modules/core/src/main/resources/scalafix-migrations.conf
- modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/buildsystem/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
If a Scalafix has accompanying documentation Scala Steward will link to it in the PR.
fixes: #1348
> Link to documentation of Scalafix migrations

- docs/scalafix-migrations.md
* document `dependency:` schema to use published scalafix rules
* add `doc` URL example introduced in #1442 
fixes: #629
> Update scalafix doc with dependency: schema and doc URL

- modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
At my place of work we have an enterprise/secured nexus setup.  the normal `credentials` key doesn't load the credentials correct for multi project builds, but `allCredentials` does.
This change will help us deploy it internally for updating our private GHE repos.
see: https://github.com/sbt/sbt/pull/4855/files/c31e0b6b550b9da9f98d3a8289283df9ade11323
Thanks!
> Fix credential loading issue with courier on enterprise nexus setup.

- README.md
- docs/running.md
docs: Mention article about how Avast runs Steward in "running"
Hello,
I would like to add Avast to the community list of companies using it. I also wrote an article on how we run Scala Steward internally so I thought it would be good to mention in the docs describing how to run Scala Steward because there are certain parts that are not fully described. Thanks.
> docs: Add Avast to community list

- build.sbt
- docs/running.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- scripts/run.sh
In some scenarios there is a need to limit dependencies you want to update for all repos. 
Currently you'd need to update repo configuration (`.scala-steward.conf`) for every project you are working on.
If the repo doesn't have configuration (`maybeRepoConfig`) it will fallback to empty `RepoConfig.default`.
This PR is adding ability to override fallback to `RepoConfig.default` by reading `default.scala-steward.conf` within main scala steward repo. It gives you all the features as described in [repo-specific-configuration.md](https://github.com/fthomas/scala-steward/blob/master/docs/repo-specific-configuration.md)
Specifically, you can limit dependencies by providing `allow` settings (which is helpful if you have 100+ repos and you want to propagate specific dependencies, only)
- Added …
> Add default .scala-steward.conf for Scala Steward itself

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- scripts/run.sh
--default-repo-conf is not a mandatory argument and this should be
reflected in the type of Cli.defaultRepoConf.
> Make --default-repo-conf an optional argument

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
- modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Both projects serve the same purpose but for different build systems.
Their names should reflect their similarity.
> Rename plugin and mill sbt projects to sbt-plugin and mill-plugin

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
> Fix reference to the root pkg of the mill-plugin project

- modules/core/src/main/resources/scalafix-migrations.conf
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
[upgrade notes](https://github.com/twilio/guardrail/blob/master/MIGRATING.md#0590-may-contain-type-and-package-naming-changes-that-will-require-changes-in-consuming-code), forgot to create this PR before actually doing the release.
> Adding a scalafix rule for sbt-guardrail 0.59.0+

- modules/core/src/main/scala/org/scalasteward/core/git/Commit.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Prior to this change `mergeAndApplyAgain` only pushed changes if
applying an update again resulted in changes in the working copy
of a repo. This prevented Scala Steward from updating PRs if
`updatePullRequests` was set to `"always"` and there were no
merge conflicts between the base branch and the update branch.
In these cases, merging the base branch is the only thing required
to bring the update branch up-to-date with the base branch.
With this change Scala Steward now pushes changes even if updating
only results in a merge commit.
Closes #1511.
> Push in mergeAndApplyAgain even if there is only a merge commit

- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Scope.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
This will create Scalafmt updates independent of the used build tool.
This is possible because the Scalafmt version is defined in
`.scalafmt.conf` which is independent of any build tool.
> Do not restrict Scalafmt updates to sbt

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/command.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Use https://github.com/scalacenter/sbt-scalafix/pull/126, released in [sbt-scalafix 0.9.18](https://github.com/fthomas/scala-steward/pull/1522).
This slightly improves runtime as migrations can be run in parallel for `Compile` and `Test`.
Note that this will NOT run migrations on `IntegrationTest` or any other custom configuration, as Scalafix needs to be [enabled explicitly on them](https://github.com/scalacenter/scalafix/blob/v0.9.18/docs/users/installation.md#integration-tests).
> use scalafixAll

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
... and always use the mill executable from the PATH. For sbt and Maven
we're also not executing scripts in repositories but always the
systemwide installed sbt or maven executables. The less user-provided
code is executed, the better.
> Do not use mill scripts in repositories

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
This allows keywords to have additional punctuation that is not present in the artifactIds or groupIds. As the test demonstrates, `SCALA_JS_VERSION` is now recognized as variable for the Scala.js version although the artifactIds only contain `scalajs` without an underscore.
> Find keywords that contain additional punctuation 

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
This refactoring records the start indices of version components which
are used to simplify and optimize the alnumComponentsWithoutPreRelease
and preReleaseIndex functions.
> Store indices in Version.Component

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/sbtTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
In anticipation to https://github.com/typelevel/cats/pull/3566
> Allow setting compiler options for Scalafix migrations

- modules/core/src/main/resources/scalafix-migrations.conf
This adds @cb372's Scalafix for Cats 2.2.0 from https://github.com/typelevel/cats/pull/3566. Once that PR is merged, we should update the `rewriteRules` so that it points to the official Cats repo. Using 2.2.0-RC4 as `newVersion` allows us to test this migration before the final release. To do so just bump Cats to 2.2.0-RC3 and let Scala Steward do the update to 2.2.0-RC4 with this migration applied.
> Add preliminary Scalafix migration for Cats 2.2.0

- project/Dependencies.scala
For testing the Cats 2.2.0 Scalafix migration: https://github.com/scala-steward-org/scala-steward/pull/1588
> Update cats-core to 2.2.0-RC3

- modules/core/src/main/resources/scalafix-migrations.conf
See https://github.com/scala-steward-org/scala-steward/pull/1588
> Update Scalafix migration for Cats 2.2.0

- build.sbt
- project/Dependencies.scala
We switched to a hash version in https://github.com/scala-steward-org/scala-steward/pull/1551 but that switch wasn't intentional. Such PRs are now prevented by https://github.com/scala-steward-org/scala-steward/pull/1552.
> Use a proper Mill release instead of a hash version

- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
`FileAlg.createTemporarily` could leave partially written files behind
if `writeFile` fails with an error - for example if it fails with
an `IOException` if there is no space left on the device. With this
change `deleteForce` will be called in case of an error and the error
will be rethrown so that `createTemporarily` fails too (as before).
> Delete file in createTemporarily if writeFile fails

- modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
- modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Before this change `showDuration` returned `"60m 31s 0ms"` instead of `"1h 31s"` for example.
> Tweak and test splitDuration

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This fixes the broken transitivity of `Order[Version]` noticed in #1615 by removing cases in `Order[Component]`. It is concerning that that there are no test cases that were sensitive to the removed code. We should double-check if it is OK to remove that code or if we can write tests that are sensitive to that code.
> Fix transitivity of Order[Version]

- modules/core/src/main/scala/org/scalasteward/core/Main.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
We're currently printing a rather unhelpful stack trace if `Cli.parseArgs`
fails. This currently happens if
- a required argument is missing
- the value of an argument cannot be parsed
- `--help` or `--usage` is provided
With this PR no stack traces are printed under these conditions. Error
or help messages are just printed to stderr or stdout and the program
exits with an appropriate status.
> Do not print stack trace if Cli.parseArgs fails

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
This implements `createForkOrGetRepoWithDefaultBranch` in terms of
`createForkOrGetRepo` instead of duplicating its logic.
> Clean up and remove duplication in VCSApiAlg

- build.sbt
Looking at the logs:
```
Cloning into '/opt/scala-steward/workspace/repos/myorg/myrepo'...
Submodule 'external/mysubmodule' (git@internal.repo:myorg/mysubmodule.git) registered for path 'external/mysubmodule'
Cloning into '/opt/scala-steward/workspace/repos/myorg/myrepo/external/mysubmodule'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
fatal: clone of 'git@internal.repo:myorg/mysubmodule.git' into submodule path '/opt/scala-steward/workspace/repos/myorg/myrepo/external/mysubmodule' failed
```
I added the `openssh` dep and the error went away
> submodules added with ssh-style apparently use the ssh binary directly

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
- modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
This removes the `VCSApiAlg.createForkOrGetRepo` call in `NurtureAlg` by
reusing the result of `createForkOrGetRepoWithDefaultBranch` in
`RepoCacheAlg`.
> Avoid duplicated VCSApiAlg.createForkOrGetRepo call

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
`git merge --strategy-option=theirs` can fail if a file has been modified on `HEAD` but deleted on the other branch. Git reports these conflicts as`CONFLICT (modify/delete)`. This PR resolves them by just removing all unmerged files which should be the same files that were deleted on the other branch.
This PR includes a test case for this issue by @kiranbayram. Thanks!
Closes #1393.
> Fix (modify/delete) conflicts in GitAlg.mergeTheirs

- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
> Use Git's default commit message when resolving merge conflicts

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
This uses `File` in `Cli.Args` so that we don't need `Sync` when converting
from `Args` to `Config`.
> Use File in Cli.Args

- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
This passes extra environement variables (that are provided via
`--env-var` options) to all `exec` calls instead of only `execSandboxed`
calls. I think it was an oversight that they were only used in
`execSandboxed`.
> Pass extra env vars to all exec calls

- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/VersionsCache.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala
- modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
These aliases are defined in Cats Effect 3 and we'll use them once we
update to that version. This change will make the diff to that version
smaller.
> Rename *Throwable aliases to *Throw

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- scripts/run.sh
We're doing the same with sbt and Maven. All builds should be run with
`execSandboxed` since we're executing user-provided code.
> Run mill with execSandboxed

- build.sbt
- project/Dependencies.scala
We're using fs2-io already in `process` so this has been an undeclared
compile-time dependency for a while. Not declaring it also leads to a
binary incompatibility when updating to Cats Effect 3.
> Add fs2-io as dependency explicitly

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestFrequency.scala
- modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestsConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
This replaces `PullRequestFrequency.{Daily, Weekly, Monthly}` with a new
`Timespan` case for arbitrary timespans. It allows for example to set
the PR frequency like this:
```
pullRequests.frequency = "14 days"
```
`@daily`, `@weekly`, `@monthly` can still be parsed and are translated
to `Timespan(1.day)`, `Timespan(7.days)`, and `Timespan(30.days)`. The
main motivation for this change is to make it easier for users to set
the frequencey to every x days without resorting to cron expressions
which are harder to read and write.
> Replace @daily, @weekly, @monthly with arbitrary timespans

- modules/core/src/main/scala/org/scalasteward/core/bitbucket/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/github/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/github/http4s/Http4sGitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
I've only test that against GitLab as I said in: https://github.com/scala-steward-org/scala-steward/issues/119#issuecomment-709653048
All 4 server implement this with a PUT/PATCH to the pull request (merge request for Gitlab API) endpoint of the given pull request. There are some distinction in how the update in serialized but, all in all, it's quite similar:
```
https://docs.gitlab.com/ee/api/merge_requests.html#update-mr
GITLAB => {"state_event": "close"}
https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#update-a-pull-request
GITHUB => {"state": "closed"}
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D#put
https://docs.atlassian.com/bitbucket-server/rest/6.6.1/bitbucket-r …
```
> Close obsolete pull requests in the NurtureAlg

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
This closes obsolete PRs only if a new PR was created or if an existing
PR was updated. Sometimes `processUpdate` does not create a new PR
because it can't figure out where to bump the version number. I think
that in these cases Scala Steward should not close the PRs of older
updates.
Follow-up to #1667. /cc @daddykotex
> Close obsolete PRs only if a PR was created or updated

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
Closes #1056
This PR adds `scalafmt.runAfterUpgrading` config, as opt-oput (default `true`).
If `true` and when `scalafmt-core` is being updated, Scala Steward will run `scalafmt` CLI and add a separate commit if dirty.
Example PR: https://github.com/exoego/scala-steward-test-project/pull/173
> Run scalafmt when upgrading scalafmt (opt-out)

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
The first few lines of Scala Steward's output now look like this:
```
2020-10-19 17:27:05,585 INFO
____            _         ____  _                             _
/ ___|  ___ __ _| | __ _  / ___|| |_ _____      ____ _ _ __ __| |
\___ \ / __/ _` | |/ _` | \___ \| __/ _ \ \ /\ / / _` | '__/ _` |
___) | (_| (_| | | (_| |  ___) | ||  __/\ V  V / (_| | | | (_| |
|____/ \___\__,_|_|\__,_| |____/ \__\___| \_/\_/ \__,_|_|  \__,_|
v0.7.0-59-1fcfcc01-20201019-1455-SNAPSHOT
2020-10-19 17:27:06,745 INFO  Loaded 15 Scalafix migrations
2020-10-19 17:27:06,934 INFO  Run self checks
2020-10-19 17:27:07,135 INFO  Using git version 2.17.1
2020-10-19 17:27:07,769 INFO  Using scalafmt 2.7.5
```
If one of the binaries cannot be executed, it will print a warning:
```
2020-10-19 17:28:49,122 WARN  Failed to …
```
> Check that git and scalafmt can be executed in SelfCheckAlg

- modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
This reverts #584 which shouldn't be needed any more since #1188.
The goal of #584 was to ignore dependencies that are added by plugins
because those dependencies cannot be updated. Unfortunately this
solution is brittle because it also ignores plugins that are added via
`addSbtPlugin` in `settings`, see https://github.com/http4s/sbt-http4s-org/pull/26#issuecomment-712351259.
(They also have a source position like ` LinePosition(Defaults.scala,...)`.)
A similar optimization was later added in #1188 which ignores all
dependencies whose versions number cannot be found in files of the repo.
This optimization also covers dependencies that are added by plugins.
Let's see if this is good enough to also cover #584.
> Do not check in StewardPlugin if dependencies are defined in build files

- build.sbt
Closes #1677 
JAR-version of scalafmt is chosen, instead of GraalVM-native version of scalafmt.
Because native scalafmt is very slow on many Scala files, due to lack of JIT.
On my machine, on scala-steward repo (200 scala files) 
- JAR scalafmt took 20 seconds
- native scalafmt took 71 seconds
Also I guess native scalafmt may not work on alpine Docker image, due to lack of enough libs for native.
> Install scalafmt on Dockerfile

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
This changes the commit message for scalafmt commits to "Reformat with
scalafmt $version". I think "Reformat" is a more common commit message
for scalafmt changes and the version allows to search on GitHub for all
scalafmt commits of a particular version by Scala Steward.
> Change scalafmt commit message and add version

- docs/running.md
> Fix a typo in gitlab setup

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
See https://github.com/scala-steward-org/scala-steward/pull/1488#pullrequestreview-434222425
The main purpose here is to get rid of `nonExistingFileExtension`.
> Differentiate between non-set and empty file extensions

- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
- modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
Using a `Map` there is unnecessary because we never look up the values
by key. This PR also unifies how commands are logged.
> Pass environment variables as List to process.slurp

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
This allows to pass extra environment variables to `execSandboxed` in
preparation for a fix for #1698. It also changes how environment
variables are used if firejail is enabled. All environment variables
(those from the config and those passed to `execSandboxed`) are
now passed via the `--env` parameter of the firejail command instead of
injecting them into the environment. This has been suggested earlier in
https://github.com/scala-steward-org/scala-steward/pull/337#discussion_r264052558 by @mwz.
> Allow passing environment variables to execSandboxed

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
This runs sbt without the `-batch` and `-no-colors` command line
options since not all launchers support them, see #1698.
I did some tests and everything works as before and I also didn't see
any colors or color escape sequences in the log output when the log
level is set to `TRACE`. Maybe these options were redundant the whole
time. Let's test this.
Closes #1698.
> Run sbt without -batch and -no-colors options

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/command.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
Some builds cannot be loaded in offline mode because of missing
dependencies. They then fail with errors like this:
```
sbt.librarymanagement.ResolveException: unresolved dependency: com.github.gseitz#sbt-release;1.0.13: not found
```
Using `offline` was added in #1253 in an attempt to reduce traffic with
Maven Central. But it turned out that the policy of our version cache was
responsible for most of the traffic (#1259) so I'm fine with removing
this again now.
> Do not put sbt in offline mode

- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
This closes the standard input of processes created by `process.slurp`
so that these processes do not wait for user input. This emulates the
effect of sbt's `-batch` option which does the following:
```sh
-batch|--batch) exec </dev/null && shift ;; #>
```
So `-batch` redirects `/dev/input` to sbt's stdin which effectively
closes it so that sbt never waits for user input. The `-batch` option
was removed in #1705.
This change is required for projects that fail to load and wait for
user input with:
```
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```
> Close standard input of processes created by slurp

- modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
`Sync` wasn't required; `MonadThrow` is sufficient
> Replace Sync with MonadThrow in VCSSelection and *ApiAlg

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/ArtifactMigrations.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
This unifies how `Config` is passed to all other classes. Before this
change there was a mix of passing it explicitly and implicitly. It is
now always passed explicitly. I think we should converge to only pass
type classes and DSLs implicitly.
> Do not pass Config implicitly

- docs/running.md
- modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/CreatePullRequestRequest.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Page.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/RepositoryResponse.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/authentication.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/authentication.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/authentication.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/JsonCodecTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/authenticationTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This removes the `http4s` package and `Http4s` prefix from `VCSApiAlg`
implementations. These are now unnecessary remnants from the time when
we only supported GitHub and `VCSApiAlg` was called `GitHubApiAlg`.
> Remove http4s packag/prefix from VCSApiAlg implementations

- .github/workflows/ci.yml
- build.sbt
While trying to release 0.8.0, I hit an issue with gpg2:
```
Running ci-release.
branch=refs/tags/v0.8.0
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
...
gpg: key 96BDF10FFAB8B6A6/96BDF10FFAB8B6A6: error sending to agent: Inappropriate ioctl for device
gpg: error building skey array: Inappropriate ioctl for device
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
...
[error] gpg: no default secret key: No secret key
[error] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/scala-steward/scala-steward/modules/mill-plugin/.jvm/target/scala-2.12/scala-steward-mill-plugin_2.12-0.8.0.pom.asc …
```
> Do not use gpg2 with sbt-ci-release

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
This uses dependencies with the next version instead of the current
version when querying Coursier for URLs. If a dependency adds URLs to
its `pom.xml` or `ivy.xml` for its next version Scala Steward will be
able to use them immediately when it is creating PRs for this version.
Currently it can only use them on the next version but one since it
uses the current version to find these URLs.
> Use next version when looking for artifact URLs

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestNumber.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestOut.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/PullRequestOutTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This contains some of the changes that were also in #1631 and is a
follow-up to #1667. This PR stores the pull request number in
`PullRequestOut` and persists it in `PullRequestRepository`. To sidestep
the issue of migrating old `pull_requests.json` files, the PR number is
added as an optional field to `PullRequestData`.
The goal here is to use the persisted PR number instead of
`VCSExtraAlg.extractPRIdFromUrls` in a future release.
> Add PR number to PullRequestOut and persist it in PullRequestRepository

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestNumber.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This uses `PullRequestData.number` for closing obsolete PRs if it is
present and falls back to `vcs.extractPullRequestNumberFrom` otherwise.
It also uses `PullRequestNumber` in `VCSApiAlg` and its implementations
and moves `extractPRIdFromUrls` from `VCSExtraAlg` to the `vcs` pacakge
since it doesn't have any dependencies.
Follow-up to #1741.
> Extract PR number from URL only if absent in PullRequestData

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
It is not necessary to run scalafmt in a sandbox.
> Post-update hooks: do not run scalafmt in a sandbox

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
- modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
This handles dependencies like org.scalatest:scalatest_2.12
and org.scalatest:scalatest_2.13 as one dependency
(org.scalatest:scalatest) with different cross artifactIds.
> Mill: extract artifact names with and without binary suffix

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
This prevents updates like https://github.com/typelevel/cats-tagless/pull/177 where a substring of an unrelated version was replaced.
> Do not replace a substring in another version

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/git/Author.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
This allows to set the Git config option [`user.signingKey`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-usersigningKey) which helps
Git to select the correct GPG key if it has trouble to choose one
itself. The key can be passed via `--git-author-signing-key $KEY` to
Scala Steward.
> Add signingKey to git.Author

- modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Version numbers in single line comments (`//`) are no longer changed
Fixes #1651
> Don't replace version numbers in comments

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
- modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
This PR replaces `--recursive` from the `git clone` options with an
[equivalent](https://git-scm.com/docs/git-clone/2.11.4#Documentation/git-clone.txt---recursive) `git submodule` call which we allow to fail. We allow it to fail
because submodules might point to private repos which may not be
necessary for updating dependencies.
This change is motivated by https://github.com/scala-steward-org/repos/pull/514#issuecomment-734213126.
> Ignore errors while cloning Git submodules

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlg.scala
- https://tools.ietf.org/html/rfc8288
- https://docs.github.com/en/free-pro-team@latest/rest/guides/traversing-with-pagination
> support pagination in installation/repositories and app/installations

- docs/repo-specific-configuration.md
Based on feedback https://github.com/scala-steward-org/scala-steward/issues/1788#issuecomment-740158243 -
We bumped into this recently, expecting `updates.limit` to be a global limit on how many PRs scala-steward would make, rather than how many it would make *per run*. Hopefully this wording change makes that distinction a little bit clearer.
> Minor refinement to `updates.limit` documentation

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
If executing a post-update hook fails, Scala Steward aborts the current
update and other pending updates of the current repository. With this
change Scala Steward ignores errors from executing post-update hooks
instead. Changes in the working copy are committed as if the post-update
hook executed without errors.
> Ignore errors when executing post-update hooks

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Updates were sorted by Scalafix migrations so that a failing migration
does not prevent other updates (#1065). Later we changed that a failing
Scalafix migration aborts all other pending updates (#1121) so this
sorting by migrations is not necessary any more.
> Do not sort updates by Scalafix migrations

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
This changes `EditAlg` such that it creates commits itself after running
Scalafix migrations and bumping version strings. It also moves
`HookExecutor` into `EditAlg` so that hooks are also executed when a PR
is updated because of merge conflicts.
Example PR with a separate commit for Scalafix changes: https://github.com/fthomas/scalafix-test/pull/74
Closes #604.
> Use a separate commit for Scalafix changes

- build.sbt
I forgot to do this in https://github.com/scala-steward-org/scala-steward/pull/1701.
> Remove remnants of http4s-async-http-client from the build

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
Parsing of versions now uses regex.
In addition a new component for hashes is added to make it easier to detect them.
After the short discussion in https://github.com/scala-steward-org/scala-steward/pull/1798#issuecomment-741892096 I gave it a try.
> Simplify version parsing

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
This prevents updates like https://github.com/ghostdogpr/caliban/pull/684 where
the version could not be bumped and the only commit is from the
post-update hook.
Follow-up to #1800.
> Do not run post-update hooks if version could not be bumped

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
Recent changes (#1802) to `Version.selectNext` and `Version.Component` made it
unnecessary to track the `startIndex` of version components. There is no
point in keeping it if it isn't used, right?
> Remove startIndex from Version.Component

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
This does not run any Scalafix migration if the version cannot be
bumped. It prevents PRs that only contains changes from Scalafix
migrations.
> Run Scalafix migrations only if version can be bumped

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
This avoids parsing the `RepoCache` in `PruningAlg.needsAttention` again
since it has already been parsed or computed in `RepoCacheAlg`.
> Pass RepoCache from RepoCacheAlg to PruningAlg

- modules/core/src/main/scala/org/scalasteward/core/edit/package.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
This supports using `scala-steward:off` in files that do not use `//` for single line comments.
Motivated by https://github.com/broadinstitute/cromwell/pull/6053.
> Allow arbitrary punctuation before scala-steward:off

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Git submodules are now initialized after the latest changes from the
upstream repo are merged into Scala Steward's fork instead of directly
after cloning our fork and before changes are synced. I hope that this
is enough to ensure that our submodules are always in sync with the
submodules of the upstream repos.
If we're lucky, this closes #339.
> Init Git submodules after syncing with upstream repo

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
This allows the repo config option `updates.limit` to be zero so that it
can now be zero or positive instead of positive only. A zero
`updates.limit` means that Scala Steward will not create or update PRs.
It can be used to temporarily disable Scala Steward in a repo or if it
is used in the default repo config it would be similar to a hypothetical
dry-run option.
> Allow updates.limit option to be zero

- modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
The abstract methods in `KeyValueStore` are now `get` and `set` instead
of `get`, `modifyF`, and `put`.
> Implement KVStore.{put, modifyF} in terms of set

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/CreateComment.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/Comment.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/Url.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
Before closing an obsolete PR add a comment to reference the newer PR.
I'm not sure if the `commentPullRequest` should have a return value. But at least is simplifies the testing.
Fixes #1674
> Add a comment: "Superseded by #" on old PRs when closing them

- modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
Subsequent reads will not need to read a file that only contains `null`.
> KVStore: delete JSON file when setting no value

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/CachingKeyValueStore.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/Repo.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
The `pull_requests` key value store is repeatedly accessed in
`PruningAlg` with the same key. This happens when we're looking for
already existing PRs which means that the same JSON file is repeatedly
read and decoded. This PR adds a caching layer to the `pull_requests`
store that caches the value of last accessed key.
> Add caching layer to pull requests store

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Add a note and a label to a pull request, if the source still contains the old version number.
Fixes #1006 
thanks @DStranger for starting this
> Add note and label for old version numbers

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Removes the remote update branch if we detect that a PR has been closed without merging.
See also #1793.
> Remove branch if PR is closed by project maintainer

- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This puts `oldVersionDetails` directly above the `ignoreFutureUpdates`
details instead of directly under the release releated URLs.
https://github.com/scala-steward-org/test-repo-2/pull/14#issuecomment-751992453
shows how this looks in comparison the current arrangement. IMO it is
nicer if all details sections are below each other. On the other hand,
`oldVersionDetails` is not as easily missed if it is directly under
the URLs.
WDYT @mzuehlke, do you have a preference for one or the other arrangement?
> Show all details in the PR body below each other

- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
With this change, multiple obsolete PRs are closed in order of their
creation date.
> Sort obsolete PRs by their number

- modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
If there has been a previous error during `RepoCacheAlg.computeCache`, we now log something like this:
```
Skipping due to previous error for 6d 23h 43m 46s 440ms
```
instead of just
```
Skipping due to previous error
```
> Show duration a repo is skipped in RefreshErrorAlg

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/CommitsConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestsConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/ScalafmtConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
Repoconfig classes are not only semigroups (because they can be merged
with the global repoconfig) but also monoids because the empty
`RepoConfig` should be the identity element with regards to merging
configs. That means that merging with the empty `RepoConfig` should not
change a repo-specific config.
This change promotes all `Semigroup` instances of config classes to
`Monoid`s and checks the monoid laws for all of them.
`UpdatesConfig.mergePin` and `UpdatesConfig.mergeIgnore` needed small
adjustments so that they satisfy the left and right identity laws.
> Check Monoid laws for all repoconfig classes

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
The new name is shorter and IMO better expresses what the class is about: it **checks** if **url**s exist.
> Rename HttpExistenceClient to UrlChecker

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/RepoData.scala
- modules/core/src/main/scala/org/scalasteward/core/data/UpdateData.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This removes `RepoCacheAlg` and `RepoConfigAlg` from `NurtureAlg` which were used to read the repo cache and repo config again. Both have been read before in `RepoCacheAlg` and `PruningAlg` and it is wasteful to do the same again in `NurtureAlg`. Both are now passed as part of a new `RepoData` class to `NurtureAlg`.
> Do not read RepoCache and RepoConfig twice

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
https://github.com/johnynek/bosatsu/pull/648 contains changes from a
Scalafix migration that exited with a non-zero status code in the same
commit as the version bump. Migration changes and the version bump
are supposed to be in separate commits but weren't because we're
currently only creating the Scalafix commit if it exited without an
error. This change always commits after a Scalafix migration regardless
of its exit status.
> Create commit for Scalafix migration even if it failed

- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/BuildRootConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
For the same reason as given in #1339.
> Make RepoConfig.buildRoots optional

- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
`runMigrations` was always called with a `Nel` of size one because we
want to have a separate commit for each migration. So there is no point
in having `runMigrations` taking a list of migratios instead of only
one.
> BuildToolAlg.runMigrations -> runMigration

- modules/core/src/main/scala/org/scalasteward/core/Main.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/ArtifactMigrationsTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
This reduces duplication in `Context` and `MockContext` which both contained code to initialize classes. The first does it for the production `F` while the latter does it for `MockEff`. This change splits `Context.create` into two functions, `step0` and `step1`, such that `step1` takes the classes we want or need to mock in tests as parameters. `step1` is then used in `MockContext` to create a `Context[MockEff]` whose members are used in test classes instead of the previously manually initialized instances in `MockContext`.
> Reuse Context in tests

- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
incorporates the feedback of #1890
> improve error message in case git or scalafmt is not on the path

- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
`waitFor` [blocks the calling thread][1] so it is appropriate to
evaluate it on the available `Blocker`.
[1]: https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#waitFor--
> Use Blocker for Process#waitFor in slurp

- README.md
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/Url.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
This PR fixes closing a superseded PR for the bitbucket cloud VCS. The current implementation fails due to the following API error:
```
2021-01-27 21:55:16,362 INFO  Create branch update/kinesis-2.15.71
2021-01-27 21:55:16,385 INFO  Push 1 commit(s)
2021-01-27 21:55:18,183 INFO  Create PR update/kinesis-2.15.71
2021-01-27 21:55:19,067 INFO  Created PR https://api.bitbucket.org/2.0/repositories/xxx/xxx/pullrequests/380
2021-01-27 21:55:19,086 INFO  Closing obsolete PR https://api.bitbucket.org/2.0/repositories/xxx/xxx/pullrequests/379 for software.amazon.awssdk:{kinesis, sqs} : 2.15.69 -> 2.15.70
2021-01-27 21:55:19,665 WARN  Closing PR #379 failed
org.scalasteward.core.util.UnexpectedResponse: uri: https://api.bitbucket.org/2.0/repositories/xxx/xxx/pullrequests/379
method: PUT
status: 400 …
```
> fix closing a pull request in bitbucket cloud

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
Using `Resource` for `UrlChecker` is not necessary because
`CaffeineCache#close` is a no-op.
> Do not wrap UrlChecker in Resource

- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala
The default state is `open` but if only open PRs are listed, Scala
Steward recreates PRs of updates that have been declined before.
API doc: https://docs.atlassian.com/bitbucket-server/rest/7.10.0/bitbucket-rest.html#idp29
> BitbucketServer: list also declined and merged PRs

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
It is unnecessary to compute the root directory on every call to
`jsonFile`. This change does it only once at the creation of the store.
> Remove effect from JsonKeyValueStore#jsonFile

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
This only allows the `moduleId` heuristic to modify version numbers in
ModuleID definitions. It prevents that version numbers are bumped in
unrelated ModuleIDs.
Closes #1314.
> Do not allow heuristics below 'moduleId' to modify ModuleIDs

- modules/core/src/main/resources/artifact-migrations.conf
Can't use sbt-release 1.0.14 due to `publishMavenStyle := false` 🙇 
I have published new version
https://github.com/sbt/sbt-release/compare/v1.0.14...v1.0.15
https://github.com/pulls?q=sbt-release+1.0.14+is%3Apr+author%3Ascala-steward+archived%3Afalse
```
[error]   not found: https://repo1.maven.org/maven2/com/github/sbt/sbt-release_2.12_1.0/1.0.14/sbt-release-1.0.14.pom
```
> fix sbt-release version in artifact-migrations

- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
This merges the `commands` and `logs` field of `MockState` into one
`trace` field that is a `Vector` of `Cmd`s and `Log`s. The advantage of
this change is that commands and logs in `MockState` are now interleaved
so that we can check their order in the tests.
> Merge MockState#{commands, logs} to MockState#trace

- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
- modules/core/src/test/scala/org/scalasteward/core/persistence/JsonKeyValueStoreTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
This changes `MockFileAlg` such that it not only modifies the `MockState` but also files in the filesystem via the default `FileAlg` implementation. The main motivation for this change is to make using actual Git commands in tests possible. Another advantage is that we increase the coverage of the default `FileAlg`. A disadvantage is that tests can now be influenced by existing or deleted files. So we need to be more careful now that tests do not write files in the same location.
> Use default FileAlg to implement MockFileAlg, take 2

- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
And do not reference `/tmp` directly.
> Use a common root directory for file operations in tests

- modules/core/src/main/resources/artifact-migrations.conf
- modules/core/src/main/resources/scalafix-migrations.conf
I was just made aware that log4cats is now published under `org.typelevel`.  This will rewrite the organization of log4cats-core, log4cats-noop, log4cats-slf4j, and log4cats-testing. The package names for these were also changed from `io.chrisdavenport.log4cats` to `org.typelevel.log4cats`, so if we merge this all update PRs will fail because of that source incompatibility. In theory this could be salvaged with a Scalafix migration that rewrites the imports and is used at the same time, but I'm not sure if it is worth the hassle.
/cc @ChristopherDavenport, @rossabaker
> Migrate log4cats artifacts

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/IncludeScalaStrategy.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Partially fixes #589 by attempting to create a draft PR for scala updates
Instead of `updates.includeScala` being strictly `true` or `false`, we introduce a third option called `"draft"` and make it the default option (and conveniently rename the other options to `"yes"` or `"no"`). When `updates.includeScala` is set to `"draft"`, we raise a github pull-request in draft mode and leave it to the project maintainer to further work on it if needed, mark it ready for review and then merge. Other options `"yes"` and `"no"` behave like in the previous revision. Thess draft PRs will ensure that scala projects do get a "notification" whenever there is an scala version update
- Sbt plugins may see a barrage of scala upgrades from 2.12 to 2.13 and will fail the builds
- Projects with scala cross …
> Create draft PRs for scala update

- modules/core/src/main/resources/artifact-migrations.conf
- https://repo1.maven.org/maven2/org/scalatestplus/mockito-3-4_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/mockito-3-3_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/junit-4-12_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/junit-4-13_2.13/
> add more scalatestplus migration configs

- modules/core/src/main/resources/scalafix-migrations.conf
I normally prefer immutable references but in this case I want to make
sure that the Scalafix can be run in case the `v2.4.0` tag has not been
pushed after the release happened.
See also #1982.
> Tweak URL for the Cats Effect 2.4.0 Scalafix migration

- modules/core/src/main/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/MergeRequestPayloadTest.scala
GitLab support for draft MRs introduced in #1961 (see [`NewPullRequestData`](https://github.com/scala-steward-org/scala-steward/pull/1961/files#diff-9f88dbf5ecab0e5057fa1fff36ae22860f197aa6cfb0d1b0d62a8bb74a6d2321R43))
> Added support for GitLab draft MRs

- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Removes overtaking updates as described in https://github.com/scala-steward-org/scala-steward/issues/129#issuecomment-789731187.
> Prevent overtaking updates

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This should prevent exiting Scala Steward's workspace using build roots
that contain `..`.
> Ignore build roots that contain '..'

- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
> Also remove overtaking updates after ensuring that updates are fresh

- modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
If sbt's logger is configured to not print info messages, for example
via `logLevel := Level.Warn`, Scala Steward will not receive any
information about dependencies from sbt. Using `println` here should
fix that.
> Do not use sbt's logger to print stewardDependencies

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
This inheritance was an unnecessary complication since we don't pass
the dispatcher to code that expects a `BuildToolAlg`. This change allows
us to remove `BuildToolDispatcher#containsBuild` which was never used.
> Do not make BuildToolDispatcher a subclass of BuildToolAlg

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
Instead of reading and parsing a repo's config twice in `RepoCacheAlg`
and `BuildToolDispatcher` we now only parse it once in `RepoCacheAlg`
and then pass that value to `BuildToolDispatcher`.
> Parse RepoConfig only once

- build.sbt
- modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- project/Dependencies.scala
This implements `Version.Component.parse` with cats-parse which gives a nice performance improvement:
```
master:
[info] Benchmark                    Mode  Cnt   Score   Error  Units
[info] VersionBenchmark.parseBench  avgt    3  10.233 ± 0.329  us/op
topic/cats-parse:
[info] Benchmark                    Mode  Cnt  Score   Error  Units
[info] VersionBenchmark.parseBench  avgt    3  6.979 ± 0.692  us/op
```
This change is of course totally irrelevant for the overall performance of Scala Steward. Playing with and getting a feel for cats-parse was the main motivation here.
> Implement Version.Component.parse with cats-parse

- modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionBenchmark.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
```
master:
[info] Benchmark                    Mode  Cnt   Score   Error  Units
[info] VersionBenchmark.parseBench  avgt    3  11.632 ± 0.250  us/op
topic/improve-startsWithDate
[info] Benchmark                    Mode  Cnt  Score   Error  Units
[info] VersionBenchmark.parseBench  avgt    3  9.044 ± 0.913  us/op
```
> Improve performance of Version.startsWithDate

- build.sbt
This fixes these warnings:
```
[warn] there are 4 keys that are not used by any other settings/tasks:
[warn]
[warn] * benchmark / moduleRootPkg
[warn]   +- /home/runner/work/scala-steward/scala-steward/build.sbt:202
[warn] * mill-plugin / moduleRootPkg
[warn]   +- /home/runner/work/scala-steward/scala-steward/build.sbt:202
[warn] * root / moduleRootPkg
[warn]   +- /home/runner/work/scala-steward/scala-steward/build.sbt:305
[warn] * sbt-plugin / moduleRootPkg
[warn]   +- /home/runner/work/scala-steward/scala-steward/build.sbt:202
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
```
> Fix warnings about unused moduleRootPkg key

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Motivated by sbt 1.5.0 updates that lead to diffs like this when running `sbt githubWorkflowGenerate`:
```diff
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,7 +74,7 @@ jobs:
strategy:
matrix:
os: [ubuntu-latest]
-        scala: [2.12.12]
+        scala: [2.12.13]
java: [adopt@1.8]
runs-on: ${{ matrix.os }}
steps:
```
> Run githubWorkflowGenerate on sbt updates

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Use simple predicates first and expensive predicates later.
> Change order of predicates for finding hooks

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
Pre-push hooks can prevent Scala Steward from pushing its update branches. Here is an example from the logs:
```
...
2021-04-07 21:09:11,026 INFO  Trying heuristic 'original'
2021-04-07 21:09:11,382 INFO  Push 2 commit(s)
2021-04-07 21:09:19,117 ERROR Steward stryker-mutator/stryker4s failed
java.io.IOException: 'git push --force --set-upstream origin update/cats-effect-3.0.1' exited with code 1
Running pre-push formatting hook... (you can skip this with --no-verify, but don't)
Looking for unformatted files...
...
```
> Bypass Git's pre-push hooks

- modules/core/src/main/resources/scalafix-migrations.conf
http4s got a new Scalafix for the upgrade to 0.22 in https://github.com/http4s/http4s/pull/4743, so let's add it here too.
/cc @rossabaker @vasilmkd
> Add Scalafix migration for http4s 0.22.0

- modules/core/src/main/resources/scalafix-migrations.conf
Hello, we would like to add an automatic rule for the migration, but I don't know how to test to make sure it will work/resolve correctly. Thanks for your feedbacks
> Add a migration rule for scalafix 0.9.28

- docs/faq.md
I recently republished the action to fix a typo in the name (and marketplace URL).
> Fix link to auto-merge GitHub Action

- build.sbt
fixes #2156 
Unfortunately there exists no openjdk11-alpine image from the openjdk organisation (https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754 https://github.com/docker-library/openjdk/issues/313).
Therefore I decided to switch to the alpine variant of adoptopenjdk. Another approach would be to switch to something like openjdk/11-jdk-slim. My reasoning behind doing it this way was to keep the operation system constant (and good experience with adoptopenjdk). If you prefer the other way around: I am happy to change the PR.
> Switched default docker base image from openjdk8 to adoptopenjdk11

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Add refresh back-off period configuration
Fixes #1912
> Add refresh back-off period configuration

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
This will run `sbt githubWorkflowGenerate` if necessary in projects that use sbt-davenverse.
/cc @ChristopherDavenport @JesusMtnez
> Add sbt-davenverse to the plugins that depend on sbt-github-actions

- README.md
it came up in chat that somebody
* didn't know that the steward can update multiple kinds of things
* didn't know GitHub isn't the only supported hosting service
> tweak readme wording

- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Noticed that in the tests there is a legacy option. Maybe worth removing?
> Remove removed scala update config

- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- project/Dependencies.scala
Supersedes #2187
This updates `refined` and `case-app` together, since `case-app` v2.1.0-M1 dependes on refined 0.9.26+.
Test code are slightly fixed, since `case-app` now outputs ANSI colors after https://github.com/alexarchambault/case-app/releases/tag/v2.1.0-M1
> New help / usage formats (picocli-inspired, with ANSI colors, etc.)
> Update refined and case-app

- modules/core/src/main/resources/artifact-migrations.conf
Trigger migration with new version of `sbt-avro` in `com.github.sbt` organisation
See #2216
> Migrate to newer artifact version

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillVersionParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
This PR adds support to read and update `.mill-version` files.
----
Initial but outdate comment:
_This is a draft, as the feature isn't complete yet_
@fthomas Thanks for the detailed steps in https://github.com/scala-steward-org/scala-steward/issues/1504#issuecomment-832950344. I managed to implement step 1 and 2, but fail at step 3. I think I'm not familiar enough with the used APIs. I could imagine it's just a finger exercise for you, in which case I'd be glad if you could help me out with a snippet. Please don't take it as a demand, but probably it speeds things up, at least on my side. ;-) Thank you!
I tried to add tests for step 1 and 2, but have no idea how to test step 3.
> Support reading and updating .mill-version file

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAttempt.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditCommit.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
This introduces the `EditAttempt` enum for the different types of edits Scala Steward can do in a PR: version bumps, Scalafix changes, and post-update hooks changes. The purpose of this change is that we can in the future use the list of `EditAttempts` returned by `EditAlg` to create more faithful PR bodies that better reflect what Scala Steward did: for example only mention Scalafix migrations if they result in changes, indicate if a Scalafix migration failed, or add labels for post-update hooks., etc.
> Introduce EditAttempt enum

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
A new `--default-branch` argument has been added to the Scala Steward cli. When this argument is present, its value will be used as the default branch when updating repositories instead of the repository's default branch.
This change enables users who run their own instances of Scala Steward to customize the branch in which updates are performed. This will enable multiple use-cases, for example:
- Updating multiple branches in a repository.
- Merging updates into a "develop" branch regularly that will be merged into the real default branch every so often.
This change will be specially useful for users of the [Scala Steward GitHub Action](https://github.com/scala-steward-org/scala-steward-action) after scala-steward-org/scala-steward-action#268 is merged.
Example:
```yml
on:
schedule:
- …
```
> Allow choosing a custom default branch

- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Closes #2099
Multi-line artifact and its version now will be updated.
This could be helpful specially for Maven users, because dependencies in Maven are often declared like below:
```xml
<dependency>
<groupId>commons-io</groupId>
<artifactId>commons-io</artifactId>
<version>2.6</version>
</dependency>
```
> Support multi-line artifact and version

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Run scalafmt with `--quiet` option so that exceptions from scalafmt do
not contain useless progress output like this:
```
Reformatting...
Reformatting... (0.12 %, 1 / 836)
Reformatting... (0.72 %, 6 / 836)
Reformatting... (1.56 %, 13 / 836)
Reformatting... (2.39 %, 20 / 836)
Reformatting... (4.31 %, 36 / 836)
Reformatting... (7.18 %, 60 / 836)
...
```
> Run scalafmt with `--quiet`

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
This sets the default `--refresh-backoff-period` to 0 days which means
that Scala Steward will not skip repos where running the build failed
previously. It effectively disables the `RefreshErrorAlg`. I
think this is a better default for most Scala Steward users since most
have control over the repositories that Scala Steward tracks and can fix
any issues with failing repos. Skipping repos is mostly interesting for
public instances where the Scala Steward operator cannot fix all issues.
> Set default `--refresh-backoff-period` to zero

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Sets the `User-Agent` header for all request by our http4s client. For @scala-steward it looks like this:
```
User-Agent: Scala-Steward/0.12.0-40-63828607 (operated by scala-steward; https://github.com/scala-steward-org/scala-steward)
```
Closes #2326.
> Set `User-Agent` header

- modules/core/src/main/resources/scalafix-migrations.conf
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/PullRequestState.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
This allows to run Scalafix migrations after the version bump. To run a
migration after the version bump, the `executionOrder` field has to be
set to `"post-update"`. The effective default value for this field is
`"pre-update"`.
Post-update migrations are useful if they consist of multiple rules
that only produce compiling code if the version is bumped before. One
example is the FS2 migration added here that consists of multiple
`replace:` rules. The symbols it renames are still present after the
bump to > 3.0.7. So it is OK to apply them successively after the
version bump but it would lead to compile errors if they were applied
before the bump because each rule could produce code that does not
compile with the old version. Running subsequent rules would then fail
with compile errors. …
> Allow running Scalafix migrations after version bump

- .github/workflows/ci.yml
- build.sbt
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
> codecov v2

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
Follow-up to #2330. This also sets the `http.agent` Java property which
is used for `java.net.HttpURLConnection`'s `User-Agent`. `HttpURLConnection`
is used in this code base by Coursier and the default `FileAlg#readUri`
implementation.
> Set `http.agent` Java property

- build.sbt
- docs/help.md
- modules/core/src/main/resources/default.scala-steward.conf
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/data/package.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoader.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoader.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
This adds support for reading a defaultl repo config from this repository. Multiple repo configs can be loaded per Scala Steward installation with the `--repo-config` command-line option and are merged into one effective global repo config. Loading the default repo config from this repository can be disabled with `--disable-default-repo-config`. This is similar to the handling of Scalafix and artifact migrations config files.
The purpose of this change is to allow library maintainers to tell Scala Steward to ignore updates until a new version is announced (#1104). They can do this adding new entries to the `updates.ignore` list of the default repo config. All (public and private) Scala Steward installations that do not opt-out of loading the default repo config will then ignore the added …
> Support reading a default repo config from this repository

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/docs/mdoc/help.md
This will also include the message for each option into the output of
`--help`. Another advantage is that the CI will complain if an option
is added but the doc is not updated.
> Generate "CLI help" doc from the code

- docs/faq.md
- modules/docs/mdoc/faq.md
Adds a link to https://scastie.scala-lang.org/6cTFqY3dTmGbZIIEgM6lyQ to the FAQ.
This is useful for checking if Scala Steward will propose an update from version x to version y.
> Add Scastie about Version#selectNext to the FAQ

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
Using `Resource` makes it easier to compose those functions compared to
nesting `F[A] => F[A]`.
> Use Resource for temporarily creating and removing files

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/test/scala/org/scalasteward/core/util/UnexpectedResponseTest.scala
This lists each header of the response on its own line instead of
having them all on one line.
> Improve formatting of UnexpectedResponse.getMessage

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
We don't have different implementations of the `BuildToolAlg` subclasses
so having `trait`s for them is a needless complication.
> Do not use traits for BuildToolAlg implementations

- docs/running.md
- modules/docs/mdoc/running.md
Adjust docs for changes to the cli options when introducing default repo config
see #2337
closes #2344
> Adjust docs for default repo config cli options

- modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoaderTest.scala
Adds a test to prevent duplicated entries in `artifact-migrations.conf`.
fixes #2314
(I hope this is what you intended @exoego)
> Duplicate test for artifact migrations

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/package.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
> Delete update branch when syncing a fork

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Prevents PRs like https://github.com/VirtusLab/scala-cli/pull/407.
> Do not select versions with a "smaller" pre-release identifier

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
`git diff` fails if there is a branch and file with the same name:
```
2021-11-23 14:16:10,530 INFO  Create branch update/bloop-config-1.4.11
2021-11-23 14:16:18,210 ERROR Steward com-lihaoyi/mill failed
git diff --name-only main update/bloop-config-1.4.11' exited with code 128
fatal: ambiguous argument 'main': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
This change therefore adds `--` after the branches in our `git diff` call.
> Fix `git diff` call

- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
Changes `git push origin --delete origin/update` to
`git push origin --delete update` because it fails with the
remote prefix:
```
git push origin --delete origin/update' exited with code 1
error: unable to delete 'origin/update': remote ref does not exist
```
Follow-up to #2371.
> Fix `deleteRemoteBranch` call

- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
* indicate if a Scalafix migration produced no change
* group rules and documentation together
* add for which new version the migration got applied
fixes #2038
Below an example from a test case:
<details>
<summary>Applied Scalafix Migrations</summary>
* com.spotify:scio-core:0.7.0
* I am a rewrite rule
* I am a 2nd rewrite rule
* Documentation: https://scalacenter.github.io/scalafix/
* org.typeleve:{cats-effect,cats-effect-laws}:3.0.0 (created no change)
* I am a rule without an effect
</details>
> Reformat Scalafix migrations notes in PR

- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This reworks the syntax for creating updates in tests. It
* does not use the `Update.Single.apply` and `Update.Group.apply` methods anymore. This will make it easier to change both classes since we  need to update the `apply` method in a lot less places.
* gets rid of implicit conversions in `TestSyntax`. The syntax is now based on extension methods via implicit classes only.
* makes creating `Update`s more concise.
> Rework syntax for creating updates in tests

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
This checks the `runAfterUpgrading` option before reformatting changed
files after the version bump. Until now this option only controlled if
scalafmt should be run on the whole project after a scalafmt update.
I think it makes sense to use this option also here so that one can
disable runnig scalafmt completely.
> Check `runAfterUpgrading` for formatting changed files

- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This adds the `commit-count` label to PR bodies. If the PR contains one
commit, the label will be `commit-count:1`. If it contains more than one
commit, the label will be `commit-count:n:$n` where `$n` is the number of
commits.
This allows to search for PRs with multiple but unspecified number of
commits and for PRs with a specified number of commits.
Closes #2383.
> Add `commit-count` label to PR bodies

- build.sbt
- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/Main.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
- modules/docs/mdoc/help.md
- project/Dependencies.scala
This replaces [case-app](https://github.com/alexarchambault/case-app) with [decline](https://ben.kirw.in/decline/) for command-line arguments parsing. My main motivation for doing this was to get familiar with decline but it also has some benefits:
* Help messages are ordinary values instead of annotations of fields. This means we can use variables and string interpolation in those messages which is currently not possible in annotation arguments. The biggest benefit here is that we don't need to repeat default values verbatim.
* Relationships between different options can be expressed. For example, `--enable-sandbox` and `--disable-sandbox` are now mutually exclusive and it is a runtime error if both are specified. Similar, if one of the GitHub app option is specified, the other must be …
> Replace case-app with decline

- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
This partially reverts #2321.
The `--quiet` option also suppresses helpful error messages:
```
$ scalafmt --non-interactive --quiet
$ scalafmt --non-interactive
Invalid config: Default dialect is deprecated; use explicit: [sbt0137,sbt1,scala211,scala212,scala212source3,scala213,scala213source3,scala3]
Also see https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects"
: ~/.scalafmt.conf
```
Which means we currently get unhelpful error messages like this:
```
[info] 2021-12-23 16:34:31,733 WARN  Reformatting changed files failed
[info] java.io.IOException: 'scalafmt --non-interactive --quiet --mode changed' exited with code 8
[info] 	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
```
With this change, the above exception will contain the message about …
> Do not run scalafmt with `--quiet`

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Instead of `(Boolean, List[Update.Single])` where the first element
designate if the second is empty, we use
`Option[Nel[UpdateState.WithUpdate]]` instead. This is a little bit
nicer since we don't need to interpret the `Boolean` but just traverse
the `Option`.
Having the `UpdateState`s available in `StewardAlg` will probably also
come in handy when dealing with #2355. I imagine that some kind of rate
limiter in `StewardAlg` will solve that issue.
> Change return type of `PruningAlg#needsAttention`

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
> Repo specific post update hooks

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Glad I learned about this the other day :)
> Add sbt-typelevel to `sbtGitHubActionsModules`

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- use `Nel[String]` instead of throwing an Exception
see https://github.com/scala-steward-org/scala-steward/pull/2434#discussion_r779472755_
> Ensure post update hooks having a `command` set via it's type

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
For the same reason as given in #1339.
> Make RepoConfig.postUpdateHooks optional

- modules/core/src/main/resources/artifact-migrations.conf
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChange.scala
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
- modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoaderTest.scala
Check if the version of the migrated artifact exists using the `versionCache`. As now the version of the migrated artifact is detected `ArtifactChange#initialVersion` is no longer needed.
fixes #2450 
This should prevent problems like in #2447
> check if the version of the migrated artifact exists

- modules/core/src/main/resources/artifact-migrations.conf
These are needed so that older versions of Scala Steward can read this
file again.
Closes: #2471
> Add initialVersion again to artifact-migrations.conf

- docs/artifact-migrations.md
- modules/core/src/main/resources/artifact-migrations.conf
- modules/core/src/main/resources/artifact-migrations.v2.conf
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsLoader.scala
- modules/docs/mdoc/artifact-migrations.md
This adds a new default file for artifacts migrations that does not contain the `initialVersion` fields. Since older Scala Steward instances load the list of artifact migrations from this repository, removing fields is a backward-incompatible change so that we cannot remove them in the old default file.
See #2455 and #2472 for context.
@mzuehlke What do you think about this change. Is there a better way to keep older Scala Steward versions happy and still getting rid of the `initialVersion` field?
> Add new version of artifact-migrations file

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- project/plugins.sbt
Retrieve the latest `sbt-scalafix` plugin version from coursier (`versionCache`) instead of relying on a hardcoded version.
Fixes #2357
> dynamic sbt-scalafix version

- build.sbt
- project/Dependencies.scala
This includes https://github.com/coursier/coursier/pull/2332.
> Update Coursier to 2.1.0-M2-19-g5a34ba7c1

- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This removes the constant `Failed to parse .scala-steward.conf: ` from
`RepoCache.maybeRepoConfigParsingError`. It is unnecessary to have this
in the caches and in PR bodies.
> Remove constant string from repo config parsing error

- .github/workflows/ci.yml
- build.sbt
- docs/artifact-migrations.md
- docs/faq.md
- docs/running.md
- docs/scalafix-migrations.md
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
I'd like to rename the default branch of this repo from `master` to `main`. If this is done, I'd check that older Scala Steward versions can still read the default `artifact-migrations.conf` and `scalafix-migrations.conf` files using the old URLs. I think GitHub redirects those.
> Rename `master` to `main`

- modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
- modules/core/src/main/scala/org/scalasteward/core/git/package.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillVersionParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
This uses `Version` instead of `String` for the version fields in
`Dependency` and `Update`. The benefit of this is type safety and less
manual conversions between `String` and `Version`.
> Use Version in Dependency and Update

- modules/core/src/main/resources/artifact-migrations.v2.conf
We already publishing snapshots with the new groupid:
https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-play-ebean_2.12_1.0/6.2.0-RC3+3-8ecd9ef2-SNAPSHOT/
> Add artifact migration for sbt-play-ebean

- modules/core/src/main/resources/artifact-migrations.v2.conf
- https://repo1.maven.org/maven2/org/scalatestplus/selenium-4-1_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/selenium-3-141_2.13/
- https://github.com/scalatest/scalatestplus-selenium/commit/21749d6aebd25c16bed3b166ba572b44a1f8c9fd
- https://github.com/scalatest/scalatestplus-selenium/commit/fbb80034b1e7c0011c8614ad85291886463a8e3e
- https://github.com/scalatest/scalatestplus-selenium/commit/f4d1fcf0787af328fae8c93bd609e7fd71052391
> add scalatestplus selenium in `artifact-migrations.v2.conf`

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
This adds a custom `PostUpdateHook` for sbt-typelevel, which calls a `tlPrePrBotHook` command alias. The idea is that:
1. Since sbt-typelevel subsumes several other plugins, it may require multiple post-update steps to be run.
2. We can easily update the command in sbt-typelevel without needing to change Scala Steward.
3. Downstream plugins can update the alias with their own custom steps, without needing to add their own `PostUpdateHook` to Steward.
Additional background in:
- https://github.com/typelevel/sbt-typelevel/pull/111.
Let me know what you think. Thanks in advance! :)
> Add custom `PostUpdateHook` for sbt-typelevel

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
@fthomas do you think this is too drastic
Fixes #2483
> Don't use versions that only consist of a hash.

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
> Reset update branch before merging the base branch

- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
This wraps `UnexpectedResponse`s on PR creation in the newly added
`RepositoryArchived` exception if the repository has been archived.
This makes it easier to extract the archived repositories from the
logs.
Here is an example from the log output:
```
[info] 2022-02-06 13:29:41,768 ERROR Steward xxx/yyy failed
[info] org.scalasteward.core.vcs.github.GitHubException$RepositoryArchived: xxx/yyy
[info] Caused by: org.scalasteward.core.util.UnexpectedResponse: uri: https://api.github.com/repos/xxx/yyy/pulls
[info] method: POST
[info] status: 403 Forbidden
...
```
> Add RepositoryArchived exception

- modules/core/src/main/scala/org/scalasteward/core/vcs/data/RepoOut.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
This throws `RepositoryArchived` in `createFork` and `getRepo` if
`RepoOut#archived` is `true` instead of later in `createPullRequest`.
Scala Steward cannot do anything meaningful on archived repositories,
so it is better to throw that exception sooner than later.
> Throw RepositoryArchived in createFork/getRepo

- modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala
- modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
Context: https://github.com/scala-steward-org/scala-steward/pull/2515#discussion_r801344269
This also helps adding new time-related test in PR #2515
> Limit precision for human readability

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
From checking if the complete version value is a hash to only checking if it contains a hash (at least 8 characters long).
The hash component detected by the parser only requires 6 byte, but in addition some leading separator.
Fixes #2502
Improves predecessor #2498
Original issue #2483
> Adapt the check for hashes in versions

- modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
First assertion was ignored previously. https://github.com/typelevel/munit-cats-effect#getting-started suggests using a for comprehension.
> Fix ignored test assertion

- modules/core/src/main/resources/artifact-migrations.v2.conf
Due to the closure of bintray, I had to migrate sbt-sassify to Sonatype OSS. As a result of that migration, and the stricter groupId policies of Sonatype, I had to change its groupId.
> Add migration of sbt-sassify

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
So that Scala Steward runs `githubWorkflowGenerate` if a project uses sbt-typelevel-mergify
and not one of the other plugins listed in `sbtGitHubActionsModules`.
> Add sbt-typelevel-mergify to the list of plugins that depend on sbt-github-actions

- modules/core/src/main/resources/artifact-migrations.v2.conf
In [sttp 3.6.1](https://github.com/softwaremill/sttp/releases/tag/v3.6.1) some artifacts are no longer published as they're included in their respective 'core' modules (`httpclient-backend-fs2` ➡ `fs2`). Example of the rename that needs to be done: https://github.com/stryker-mutator/stryker4s/pull/1154/files
This PR adds artifact migrations for the changed modules.
I haven't found a setting for what version the artifact is migrated, so I assume scala-steward uses the latest version when upgrading?
> Add sttp 3.6.1 artifact migrations

- modules/core/src/main/resources/artifact-migrations.v2.conf
Changed the groupId with this pull request: https://github.com/playframework/play-grpc/pull/420
Moving all the grpc artifacts from https://repo1.maven.org/maven2/com/lightbend/play/ to https://repo1.maven.org/maven2/com/typesafe/play/
> Add artifact migration for play-grpc

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
This is a suggestion that came up on typelevel/typelevel-scalafix#6.
The [build file](https://github.com/scalacenter/scalafix.g8/blob/main/src/main/g8/scalafix/build.sbt#L3=) in projects generated by [scalafix.g8](https://github.com/scalacenter/scalafix.g8) determines its Scala versions based on properties provided by sbt-scalafix.
Any time that sbt-scalafix is updated in those projects it's possible that the `crossScalaVersions` will change.
Contributed on behalf of the @opencastsoftware open source team. 👋
> Add Scalafix to the list of artifacts that can cause sbt-github-actions workflows to be regenerated

- modules/core/src/main/resources/artifact-migrations.v2.conf
from https://www.bouncycastle.org/latest_releases.html:
> **Packaging Change (users of 1.70 or earlier):** BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars.
> add artifact migration for Bouncy Castle Crypto APIs

- modules/core/src/main/resources/scalafix-migrations.conf
Attempt to reflect a change in defaults for generated code to reduce upgrade burden
> Adding IteratorToVector rule for sbt-guardrail 0.72.0

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
- modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
Partially addresses #2355 by implementing [Retry-After](https://httpwg.org/specs/rfc7231.html#header.retry-after) support.
I'm only handling response headers of the form `Reply-After: 60` seconds since that's what github actually returns. Non-numeric/date-based values like the one in the RFC will be ignored:
```
scala> "Wed, 21 Oct 2015 07:28:00 GMT".toIntOption
val res0: Option[Int] = None
```
> Retry on Retry-After response header

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
> Scan project/project/... folders

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
> Warn if repos.md is not properly formatted

- build.sbt
Closes #2613 
Tag the latest stable docker image with `latest-release`, see https://www.scala-sbt.org/sbt-native-packager/formats/docker.html#publishing-settings
> Tag latest docker image with latest-release

- modules/core/src/main/scala/org/scalasteward/core/git/Commit.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This could probably be used for implementing #2567. In the `HookExecutor` we could take the sha1 of the formatting commit and add it to `.git-blame-ignore-revs`.
> Add sha1 field to Commit case class

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAttempt.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/package.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
This adds a new field `addToGitBlameIgnoreRevs` to `PostUpdateHook`
which controls if the commit hash of that hook should be appended to
`.git-blame-ignore-revs`. If that file does not exists in the repo,
it will be added by Scala Steward.
Example PRs:
* https://github.com/scala-steward-org/test-repo-1/pull/15
* https://github.com/scala-steward-org/test-repo-1/pull/16
Closes: #2567
> Add reformatting commits to .git-blame-ignore-revs

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
This adds the executed command of post-update hooks to their commit
message. It makes it obvious what Scala Steward did and is helpful for
users who want to reproduce the changes themselves.
> Add command to the commit message of post-update hooks

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- repos.md
New message:
```
Regenerate GitHub Actions workflow
Executed command: sbt githubWorkflowGenerate
```
Old message:
```
Regenerate workflow with sbt-github-actions
Executed command: sbt githubWorkflowGenerate
```
The rationale for changing the message is that Scala Steward also runs
this task if the project does not depend on sbt-github-actions but on a
plugin that provides the `githubWorkflowGenerate` task. For example,
sbt-typelevel provides [this task](https://github.com/typelevel/sbt-typelevel/blob/b2cabecd3441d6292a186b62d87892f3796ca17b/github-actions/src/main/scala/org/typelevel/sbt/gha/GenerativeKeys.scala#L23-L24) and does not depend on
sbt-github-actions. So the old message is misleading in this case.
> Change commit message of hook that runs 'sbt githubWorkflowGenerate'

- README.md
- repos.md
This points users to https://github.com/VirtusLab/scala-steward-repos
instead of the now archived https://github.com/scala-steward-org/repos.
Many thanks again to VirtusLab for hosting the public instance!
/cc @romanowski @Kordyjan @pikinier20
> Advertize VirtusLab's public Scala Steward instance

- modules/core/src/main/resources/artifact-migrations.v2.conf
- modules/core/src/main/resources/scalafix-migrations.conf
See associated doc [here](https://github.com/trace4cats/trace4cats-docs/blob/master/docs/migrating.md) and issue https://github.com/trace4cats/trace4cats/issues/701
> Add trace4cats artifact and scalafix migrations

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
Fixes #2634 
Added dedicated configuration, which alters pre-release version checks for specified dependencies.
Similar features has been mentioned there https://github.com/scala-steward-org/scala-steward/issues/1023#issuecomment-551942307
> Allow pre-release updates to specific dependencies

- README.md
- docs/running.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
- modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- modules/docs/mdoc/running.md
- modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
- modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
This PR lets Scala Steward also pick up custom headers used for authentication. This is for example needed for Gitlab. I think looking at `csrConfiguration.value.authenticationByRepositoryId` is the cleanest and most generic way to achieve this.
Example snippet of a .sbt file from a project that sets a custom HTTP-header for authentication with Coursier:
```
resolvers += "gitlab-repo" at "https://gitlab.example.com/api/v4/groups/1/-/packages/maven",
csrConfiguration ~= _.addRepositoryAuthentication("gitlab-repo", Authentication(Seq( ("private-token", "xxx") )))
```
It works for SBT and Mill, but doesn't work for Maven
> Collect HTTP Headers from Coursier for authentication

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
If the `sbt-typelevel-github-actions` plugin is used directly, we want pull requests to run `githubWorkflowGenerate`.
> Add sbt-typelevel-github-actions to sbtGitHubWorkflowGenerateModules

- modules/core/src/main/resources/artifact-migrations.v2.conf
The repo was transferred on GitHub and will from now on publish with the new group ID.
> Add artifact migrations for geo-scala

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillPluginParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
This pr adds in the ability to detect Mill plugins that are defined in
the following way, which is new as of 0.10.x of Mill.
```
import $ivy.`com.goyeau::mill-scalafix::0.2.10`
```
The artifact for this will end up being:
```
mill-scalafix_mill0.10_2.13
```
There is no API currently for Mill to give you the plugins being used in
the build file, so instead of this logic being in the actual Mill plugin
we parse the build file.
Closes #2694
> feat: add ability to detect Mill plugins

- modules/core/src/main/resources/default.scala-steward.conf
https://www.scala-lang.org/blog/2022/09/05/scala-3.2.0-released.html
> update scala version in `default.scala-steward.conf`

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This is a bug fix to match the documented behavior in #2635 
> This also implies, that it will be allowed for snapshot versions to be updated to snapshots of different series.
For this to work reliably we need to eliminate weight of common prefix in allowPrereleases mode upgrading from Snapshot to Snapshot.
This is crucial, because in many projects (which publishes only snapshots for some reasons like continuous builds) there is no point to merge snapshots one by one sequentially.
Tests for these cases added.
> Ignore common prefix weight for snapshots ordering

- modules/core/src/main/resources/default.scala-steward.conf
Akka starting from version 2.7.0 will use the BSL license, which will require from large companies to pay for license. Due to that any library that uses Akka and is included in a project would also need to pay for licenses.
To avoid unexpected costs for companies, let's add Akka 2.7.0 as ignored for Scala Steward, so that users will need to update it manually and consiously accept the new license.
Not sure how to properly allow for the updates if the user wants it, but if it proves to be difficult we can add some additional settings. I was thinking about maybe `allowedLicenses` that could get overriden in a local repo.
Let me know what everyone thinks about this change.
> chore: Exclude Akka artifacts due to change of license

- project/plugins.sbt
This is a blocker to update Scala to 2.13.10
> Update to scoverage to 2.0.5

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/Main.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlgTest.scala.scala
Attempt to solve #2638. Can be invoked like this (as a subcommand):
```
java -jar scala-steward-assembly-VERSION.jar validate-repo-config .scala-steward.conf
```
Sample input (with error):
`.scala-steward.conf`:
```ini
updatePullRequests = 123
```
Output:
```python
2022-07-12 11:17:08,589 ERROR Configuration file at /home/nikololiahim/scala/scala-steward/.scala-steward.conf contains errors:
Decoding failed with:
Got value '123' with wrong type, expecting string:
updatePullRequests
```
> A CLI command to validate repo configs 

- .scala-steward.conf
Supersedes #2719 
[logback-classic no longer supports JDK 8 starting from 1.4.0](https://logback.qos.ch/dependencies.html).
Let's pin it to 1.3.x series until we drop JDK 8 support.
> Update logback-classic only on 1.3.x series that supports JDK 8

- build.sbt
- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/data/SemVer.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/data/UpdateData.scala
- modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/package.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestGroup.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateFilter.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/data/GroupedUpdateTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
This PR was created with the idea of being reviewed commit by commit.
Each commit contains an incremental change (and its tests, if applicable) that makes it easier to review. Also some of the commits contain additional information in their description to help understand why the change was made.
<details><summary><b>I also recommend checking "Hide whitespace" when reviewing this PR!</b></summary></br>
</details>
This PR adds support for a long-requested feature of Scala Steward, the ability to group pull-request updates.
A new configuration value (`pullRequests.grouping`) can be added to the `.scala-steward.conf` file. This config will represent the desired PR groups.
A group will be an object with:
- `name` (mandatory): the name of the group, can be used for things like naming the …
> Add support for grouping dependency updates

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/util/logger.scala
- modules/core/src/test/scala/org/scalasteward/core/util/loggerTest.scala
- Fixes two bugs introduced on #2714:
+ `grouping` wasn't been joined properly when using the `Monoid` instance.
+ The update branch was trying to be created once per update in grouped updates.
It also rewords the log with the updates found so it better reflects which ones are grouped/single.
Example of PR with grouped update: https://github.com/alejandrohdezma/scala-steward-test/pull/3
> Fix grouping feature

- .github/dependabot.yml
Reverts scala-steward-org/scala-steward#2771
Because most of actions are managed in https://github.com/djspiewak/sbt-github-actions
> Revert "Add Dependabot configuration for GitHub Actions updates"

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
This allows the `--url-checker-test-url` option to be used multiple times. Each argument of this option is checked with the `UrlChecker` in `SelfCheckAlg` at program start-up.
This is useful when Scala Steward is used in corporate environments where one wants to ensure that it can check internal and externals URLs.
> Allow `--url-checker-test-url` option multiple times

- .github/workflows/ci.yml
- build.sbt
Closes #2746
Unfortunately, not a small number of libraries used in Scala Steward dropped Java 8.
Since scala-steward is not a library, I think long-term Java 8 support is not needed fundamentally.
> Replace Java 8 with newer LTS Java 17

- project/Dependencies.scala
Reverts scala-steward-org/scala-steward#2769
Temporary workaround for https://github.com/scala-steward-org/scala-steward/issues/2797
> Revert "Update coursier to 2.1.0-RC2"

- .scala-steward.conf
Reverts scala-steward-org/scala-steward#2745
Unpin logback-classic as mentioned in https://github.com/scala-steward-org/scala-steward/issues/2746#issue-1416131445.
> Revert "Update logback-classic only on 1.3.x series that supports JDK 8"

- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinder.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
Closes https://github.com/scala-steward-org/scala-steward/issues/2682.
> Scalafix artifactId patterns must match whole artifactIds

- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
> ❗ This must be released as a patch version ASAP.
`Update` decoders are expecting JSON objects to be wrapped in a field named as the class:
```json
"ForArtifactId": {
...
}
```
While individual encoders are not creating this field.
This only happens when decoding `Grouped` updates, since it is the only place an individual encoder was being used.
This PR ensures encoders always introduce this wrapper-field so updates are correctly parsed on every situation.
Fixes #2802
> Fix bug on `Update` JSON encoders

- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
My local Git version does not yet know the `--initial-branch` and thus the `FileGitAlgTest` fails for me with:
```
org.scalasteward.core.git.FileGitAlgTest:
==> X org.scalasteward.core.git.FileGitAlgTest.branchAuthors  0.585s java.io.IOException: 'VAR1=val1 VAR2=val2 git init . --initial-branch master' exited with code 129
error: unknown option `initial-branch'
```
Instead of using this option, we call `git init` now with the `init.defaultBranch=master` config which should have the same effect as the `--initial-branch` option according to the [docs](https://git-scm.com/docs/git-init). Older Git versions just ignore this config.
I hope this also fixes the problem mentioned in https://github.com/scala-steward-org/scala-steward/commit/cfe58570d4ddb9abd6efa40ffa7f625f968e8144
> Use init.defaultBranch instead of --initial-branch option

- modules/core/src/main/resources/scalafix-migrations.conf
Address #2770 
I'm not sure if my rule is too specific to the `scala-compact-library` and should be more general to the scala bumping version.
> Add scala-collection-compact Scalafile rule when bump from 2.12 to 2.13

- modules/core/src/main/resources/artifact-migrations.v2.conf
- modules/core/src/main/resources/default.scala-steward.conf
- modules/core/src/main/resources/scalafix-migrations.conf
This should clarify that the latest versions of these default config files are downloaded by all Scala Steward instances.
> Add note to default config files that are downloaded at start-up

- .mergify.yml
So that Mergify automatically merges Scala Steward's PRs again.
> Bump JDK versions in Mergify config

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
The `$MILL_BIN_PLATFORM` replacement is only supported when used with `import $ivy`.
Fix issues introduced in #2821
> Fix: Replaced import logic in predef script for Mill projects

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- project/Dependencies.scala
- repos.md
scalaStewardMillPlugin has been used recursively before.
> Use scalaStewardMillPluginArtifactName in scalaStewardMillPlugin

- README.md
- docs/help.md
- docs/running.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/JsonCodec.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/azurerepos/authentication.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/UrlTest.scala
- modules/docs/mdoc/running.md
This PR adds support for Azure Repos as requested on #2659 
Azure APi Doce: [here](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-7.1)
WIth this feature, scala-steward can be run on Azure Repos using docker as follows
1. Create and add an access token to `pass.sh` file:  [See how](https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows)
```bash
echo "#!/bin/sh"  >> pass.sh
echo "echo '$AZURE_REPO_ACCESS_TOKEN'" >> pass.sh
```
2. Run steward
```bash
docker run -v $PWD:/opt/scala-steward \
-it fthomas/scala-steward:latest \
-DLOG_LEVEL=TRACE \
--do-not-fork \
--workspace "/opt/scala-steward/workspace" \
--repos-file "/opt/scala-steward/repos.md" \
--git-author-email …
```
> Add support for Azure Repos

- docs/scalafix-migrations.md
- modules/docs/mdoc/scalafix-migrations.md
> Update links to Scalafix documentation

- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
My hope is that users that see these warnings are encouraged to contribute Scalafix migrations support to Scala Steward for their build tool. :-)
> Warn about missing Scalafix support in MillAlg and MavenAlg

- build.sbt
These tools are required to deal with some scala.js projects.
See https://github.com/wiringbits/scala-webapp-template/issues/298
NOTE:
- I have tested that the docker image can be published locally.
- I'm yet to test that this change fixes https://github.com/wiringbits/scala-webapp-template/issues/298
- A potential improvement could be to install nvm instead but that would require to install yarn per repository.
> Add node/yarn to the docker image

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
`StewardPlugin.scala` is the sbt plugin that outputs all relevant information from a build for consumption by Scala Steward. That plugin has been installed so far globally at the start of Scala Steward into sbt's home directory. With this PR, that plugin is now installed into the local `project/` directories as long as it is needed to run `sbt stewardDependencies`.
This change is motivated by #2847 - i.e. only sbt >= 1.3.0 can currently load our sbt plugin. With this change we would be able to use different plugins dependending on a repo's sbt version.
closes: #1624
> Add sbt plugins locally and not globally

- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This merges `ConfigParsingResult` and `ConfigValidationResult` which were basically the same data structures. It removes some duplication and the explicit cases of `ConfigParsingResult` make that type easier to understand.
> Merge ConfigParsingResult and ConfigValidationResult

- build.sbt
This sets the sbt version that is used to compile our plugin and it shows that we currently require at least 1.3.11 (see also https://github.com/scala-steward-org/scala-steward/issues/2847#issuecomment-1364132307). This setting should also help with making us aware of any changes in the plugin that would require a newer sbt version.
> Show that our sbt plugin requires at least 1.3.11

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/SbtVersion.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/parser.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
- modules/sbt-plugin-1_0_0/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_0_0.scala
- modules/sbt-plugin-1_3_11/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin_1_3_11.scala
This PR injects a sbt plugin into a repo's build that depends on the used sbt version. The main motivation of this change is to fix #2847.
The changes here are:
- the `sbt-plugin` project in the build is renamed to `sbt-plugin-1_3_11`. `1_3_11` is used as suffix because the plugin requires at least sbt 1.3.11, see #2858.
- a new `sbt-plugin-1_0_0` is added that contains a `StewardPlugin_1_0_0.scala` that is compatible with sbt 1.0.0 and above. It should also work with sbt 0.13.x but we don't test it here because I don't want to add Scala 2.10 to `crossScalaVersions`.
- `SbtAlg#getDependencies` first reads the sbt version from `build.properties` and then selects the appropriate plugin based on that version.
closes: #2847
> Use a version dependent sbt plugin

- project/plugins.sbt
- repos.md
It seems that this isn't needed anymore.
> Do not overwrite version scheme for scala-xml

- modules/benchmark/src/main/scala/org/scalasteward/benchmark/VersionPositionScannerBenchmark.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/VersionPositionScanner.scala
I played with using `VersionPositionScanner` instead of `GitAlg#findFilesContaining` in `RepoCacheAlg` and noticed that the regex used in `findMillDependency` is quite slow since it allows whitespace (including newlines) in the groupId and artifactId identifiers.
This change disallows whitespace in those identifiers and requires that they are not empty. It increases performance significantly even with the toy example in the added benchmark.
> Optimize regexes in VersionPositionScanner

- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/package.scala
This one actually executes `f` on the provided `pool`.
> More faitful implementation of `coursier.util.Sync#schedule`

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
This fuses the `evalFilter(...).evalMapFilter(...)` calls in `FileAlg#findFiles`. In my experiments this resulted in a 5-10% performance improvement.
> Fuse stream transformations in `FileAlg#findFiles`

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSType.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
* ensure that `--do-not-fork` is given for azure-repos and bitbucket-server
* ensure that `--add-labels` is not given for bitbucket and bitbucket-server
> Add more validation to vcs specific arguments

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
This adds a `clientResponses: HttpApp[MockEff]` field to `MockState`. It is used by the http4s client in `MockContext` and allows to have different pre-determined responses in the different tests without constructing a new client in each test.
The changes in `VCSExtraAlgTest` demonstrate that this works.
> Add pre-determined HTTP responses to `MockState`

- build.sbt
`unmanagedResourceDirectories` now contains the shared resource directory `modules/core/src/main/resources` without this workaround.
> Remove sbt-crossproject workaround

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
Sometimes scala-steward fails to bump a version.
When this happens, the logs just show:
```
WARN Unable to bump version
```
This PR adds the name of the update to that warning. This will look something like:
```
WARN Unable to bump version for update com.foo:library : 1.2.3 -> 1.3.0
```
> Log the update when scala-steward is unable to bump a version

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/gitlab/GitLabApiAlgTest.scala
* Use the newly added #2872  `clientResponses` field in `MockState` throughout the test in vcs.
* Construct the different vcsAlg instances using `VCSSelection`
* add tests for the `Authorization` headers
* convert tests to `CatsEffectSuite`
> Use `clientResponses` from `MockState` in vcs tests

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
- project/Dependencies.scala
As per title, I swapped the client implementation.
There are a few things to note by the way:
- As you can see [here](https://github.com/http4s/http4s-jdk-http-client/blob/main/core/src/main/scala/org/http4s/jdkhttpclient/JdkHttpClient.scala#L257) JdkHttpClient doesn't expose a builder that let you operate over the `java.net.HttpClient.Builder` so I had to copy some of the default logic from the lib (this might be a nice addition to the upstream lib btw)
- the default `BuilderMiddleware` is no more an identity as the default for HttpClient is to do not follow redirects
- There's no way to "destroy" the HttpClient instance so the Resource.release is a F.unit
Closes https://github.com/scala-steward-org/scala-steward/issues/2887
> Replacing deprecated http4s-okhttp-client with http4s-jdk-http-client

- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala
This is a follow-up to #2863. Before this change, the `info.releaseNotesUrl` property from the POM was ignored if `project.scm.url` and `project.url` were not set (since `DependencyMetadata#repoUrl` is then empty too). With this change the `releaseNotesUrl` is added to the PR even if the other two are not set.
> Use releaseNotesUrl even if repoUrl is empty

- modules/core/src/main/scala/org/scalasteward/core/edit/update/data/ModulePosition.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
This is a fix and tests for the issue I raised in #2877.
Prior to this fix, scala-steward was failing to properly update this example:
```scala
val ScalaTestVersion = "3.2.13"
libraryDependencies ++= Seq(
"org.scalatest" %% "scalatest" % ScalaTestVersion,
"org.scalatest" %% "scalactic" % "3.2.13"
)
````
due to the trailing comma in `ScalaTestVersion,`.
> Issue #2877: Fix "Unable to bump version" when using a val version in libraryDependencies ++= Seq(...)

- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/package.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
... instead of manually constructing the repoDir from the workspace config. This makes the tests independent of the actual implementation of `WorkspaceAlg#repoDir` so that they don't break if the implementation is changed.
> Use WorkspaceAlg#repoDir in tests

- modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrl.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
If `DependencyMetadata#releaseNotesUrl` contains the same URL that `possibleUpdateInfoUrls` returns in a `GitHubReleaseNotes`, we currently discard the `GitHubReleaseNotes` in favor of the `CustomReleaseNotes` coming from the `DependencyMetadata#releaseNotesUrl`. In the PR body we would then present that URL as `Release Notes` instead of `GitHub Release Notes` although it points to the GitHub release notes. With this change, we prefer `GitHubReleaseNotes` over `CustomReleaseNotes` regardless where the GitHub release notes URL is coming from.
> Prefer GitHub release notes over custom release notes

- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
- modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
- modules/core/src/test/scala/org/scalasteward/core/data/UpdateTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
This supports artifact migrations of multiple artifacts in one update. Prior to this change, this was not possible because the `newerGroupId` and `newerArtifactId` fields were discarded while `ForArtifactId` updates were grouped into `ForGroupId`. With this change, `ForGroupId` is just a non-empty list of `ForArtifactId`s, so that these fields are not lost.
Closes: #1974
> Support artifact migrations in `Update.ForGroupId`

- docs/CONTRIBUTING.md
Based on discussion in https://github.com/scala-steward-org/scala-steward/issues/2903
I added Reference and How-to based on my own interpretation of the "Documentation System". I really like it as a framework, but I have struggled on where to put links. I usually put them under the Reference section, but I could also see links interpreted as an Explanation.
> Add a How-to section to CONTRIBUTING.md

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
This renames `JsonParseError` to `DecodeFailureWithContext` and tests it. IMO `DecodeFailureWithContext` is a better name since the class wraps a `DecodeFailure` and adds context to ease debugging.
> Rename and test JsonParseError

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
This unifies the client calls in `HttpJsonClient`. There is now only one method that calls the underlying client that works for all other methods. The nice thing about this is that we only need to handle decoding failures and unexpected responses in one place.
> HttpJsonClient: unify client calls

- modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala
- modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubAppApiAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/util/HttpJsonClientTest.scala
This implements `HttpJsonClient#getAll` as `fs2.Stream`. The nice thing about this is that the consumer of the stream has control over how many requests are made independent of how many pages exists in total.
`GitHubAppApiAlg` still accumulates all values into a list, so this change does not make a difference in practice but I think it is a nicer foundation.
I should also note that the values returned by `getAll` are now in the same order is in the pages. This means Scala Steward as GitHub App will work on repos in the same order as in the `/installation/repositories` responses.
> Implement HttpJsonClient#getAll as fs2.Stream

- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala
This collapses the first three cases into one by comparing the groupId/artifactId with the `before` value if it exists or the `after` value if not. The case where both `before` are `None` is prevented by https://github.com/scala-steward-org/scala-steward/blob/73a360c1dc9ff5d37545ce06862390627cdb13e2/modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChange.scala#L37-L40
> Simplify implementation of `findArtifactChange`

- modules/core/src/main/scala/org/scalasteward/core/application/SelfCheckAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/FileAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala
See https://github.com/scala-steward-org/scala-steward/pull/2886#issuecomment-1372712263.
Fixes #2889
> Log a warning, when the workspace directory doesn't exist

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
This changes the value of the `pullRequests.frequency` config in the example to slow down future updates in PR bodies from `@monthly` (which is an alias for `30 days`) to `30 days`. An advantage of this new value is that it is immediately clear how it needs to be adapted if you want to receive updates every 7, 14, 60, etc. days.
With `@monthly` you need to look at the documentation to learn what other special values exist and how to configure a custom frequency of every n days.
> Use `30 days` instead of `@monthly` in repo config example

- modules/core/src/main/scala/org/scalasteward/core/edit/update/ModulePositionScanner.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
This allows updating Maven dependencies that use a property for the Scala binary suffix:
```xml
<groupId>org.foo</groupId>
<artifactId>log4cats_${scala.binary.version}</artifactId>
<version>1.1.1</version>
<groupId>org.foo</groupId>
<artifactId>log4cats_2.13</artifactId>
<version>1.1.1</version>
```
> Support Maven dependencies with a property for the Scala binary suffix

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixCli.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/package.scala
- modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
What has been done?
This changes `slurp` such that it throws an `ProcessBufferOverflowException` if a process outputs more lines than the max buffer size of the internal lines buffer. Throwing that exception can be prevented via the new `SlurpOption.IgnoreBufferOverflow`. `slurp` then behaves as before this change.
Some `exec` calls now use `SlurpOption.IgnoreBufferOverflow` in cases where we ignore the output of a process or a partial output of a process is sufficient.
Why?
This allows us to decide in `ProcessAlg#exec` calls if we need the complete output of a process or if it is okay to only get a fraction of it (for example, if we completely ignore the output). In some situations it is important that we receive the complete output and this allows us to fail early instead of getting …
> Throw if slurp reads more lines than `max-buffer-size`

- docs/running.md
- modules/docs/mdoc/running.md
Unfortunately, the current example does not work out of the box. 
```
java.io.IOException: Cannot run program "/builds/xxx/scala-steward/askpass.sh" (in directory "/builds/xxx/scala-steward/workspace"): error=13, Permission denied
```
```
/opt/docker/bin/scala-steward  # collapsed multi-line command
Missing expected flag --forge-login, or command (validate-repo-config)!
Usage:
....
```
> Update GitLab example

- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
This simplifies `ProcessAlg` by removing the `NoSandbox` and `WithFirejail` classes in favor of the new `ProcessAlg#toArgs` and `ProcessAlg#toSandboxArgs` methods. These two show that the difference between normal and sandboxed execution is just how `Args` is constructed.
> Simplify ProcessAlg

- modules/core/src/main/scala/org/scalasteward/core/git/Sha1.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/BranchOutTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
`Sha1.unsafeFrom` makes it easier to create `Sha1`s in the tests.
> Add `Sha1.unsafeFrom`

- build.sbt
This changes the base image being used from [adoptopenjdk](https://hub.docker.com/r/adoptopenjdk/openjdk11) which has been [deprecated](https://github.com/AdoptOpenJDK/openjdk-docker) to it's replacement [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin).
This new base image will help get updates and resolve some security vulnerabilities.
> Use adoptopenjdk replacement temurin base image

- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/PullRequestPayload.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/JsonCodecTest.scala
this refactoring replaces `NewPullRequestData` that was serialized into Json and used as a payload for POST /repos/{owner}/{repo}/pulls (creating PR on GitHub) because `NewPullRequestData` contains fields that are not processed by GitHub API (such as labels, assignees, reviewers). New model only has fields that are expected by GitHub API.
> github: add dedicated model for create PR body

- modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
Workaround for https://github.com/http4s/http4s-jdk-http-client/issues/714#issuecomment-1443837210. Hopefully :)
> Drain response bodies before retrying

- docs/repo-specific-configuration.md
Without the double quotes, it broke my grouping configuration. It seems it was forgotten in this doc
> docs(repo-specific): fix title for grouping

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoAlgTest.scala
While working on #2995 I ran into a problem that prevented me from running scala steward locally on my machine.
That's because in my `~/.gitconfig` I configured that the default remote of a freshly cloned git repo should always be called `upstream`:
```
[clone]
defaultRemoteName = upstream
```
However, if you grep through the scala-steward source code, you will see that scala-stewared heavily and basically everywhere and always relies on the remote's name to be `origin`.
So this pull requests make sure that when scala-steward clones a git repository the name of the remote is always called "origin" by overriding global git config (user) setting directly at the git-clone command.
With this fix I was able to run scala-steward locally, without it it always failed (or better: the git commands …
> Make sure remote is always called "origin" when cloning git repo

- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/JsonCodec.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/Url.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/JsonCodecTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/UrlTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/MergeRequestPayloadTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
ForgeApiAlg.labelPullRequest only used during creation of pull request. Some providers such as GitLab, Azure, Gitea can add labels to PRs in the same API call used for PR creation and it's unreasonable to make it as a separate call. For providers that do not support it, labelPullRequest() is kept as private member
> refactoring: remove ForgeApiAlg.labelPullRequest

- modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
This actually executes commands in `MockProcessAlg` (in addition to recording them in `MockState#trace`) if `MockState#execCommands` is `true` and there is no predefined output in `MockState#commandOutputs`.
This can be useful if certain tests should actually run external processes. For example if we want to execute `git grep` in `RewriteTest` as mentioned in https://github.com/scala-steward-org/scala-steward/pull/2994#issuecomment-1455174931.
> Allow to execute commands in MockEff

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
Some projects set up plugins in `project/project/plugins.sbt` and even in `project/project/project/plugins.sbt` (I worked on such a private project, so I can't share details, but such things do exists :wink:)
For example, Play and the sbt-web-build-base project put [sbt-buildinfo](https://github.com/sbt/sbt-buildinfo) in their `project/project/plugins.sbt` files:
* https://github.com/playframework/playframework/blob/main/project/project/buildinfo.sbt
* https://github.com/sbt/sbt-web-build-base/blob/master/project/project/buildinfo.sbt
However, as you can see, even though scala-steward is enabled and visiting those repos, that plugin never gets updated ([latest release is 0.11.0](https://github.com/sbt/sbt-buildinfo/releases), also see [maven …
> Check up to 5 nested project folders

- modules/core/src/main/resources/artifact-migrations.v2.conf
Changed in [this PR](https://github.com/Dwolla/async-utils-twitter/commit/ca7e954bd5d5cc07fcd1645be35f4931e5ebaf58#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91)--`cats-effect` 2 support was removed.
> Adding artifact migrations for async-utils

- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
This uses `git commit`'s [`--trailer` option](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---trailerlttokengtltvaluegt) for commit message trailers instead of formatting and appending them as last `-m` argument ourself. The advantage is that Git takes care of formatting them properly and it is aware of them now. I guess this better composes with other Git options that add trailer(s) themself ([`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) for example).
This PR also contains two renamings:
* `toNel` -> `paragraphs`
* `withParagraph` -> `appendParagraph`
> Use Git's `--trailer` for commit message trailers

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/data/Substring.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
Fixed the issue that is throwing StringIndexOutOfBoundsException when duplicated replacements are used to edit the file. 
In other words, trying to replace single dependency more than once which is not valid.
> Fixed throwing StringIndexOutOfBoundsException

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- project/Dependencies.scala
Since https://github.com/coursier/coursier/pull/2633 handling for resolving sbt plugins from Maven repositories got extracted into `SbtMavenRepository` in the `coursier-sbt-maven-repository` module
closes: #3011
> Update to changes in coursier 2.1.0

- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
I am using `--gitlab-merge-when-pipeline-succeeds` to automatically merge scala-steward merge requests, however, today scala-steward failed to merge a merge request which was `Ready to merge` state.
Only thing I could see in the logs was the following;
```
Unable to automatically merge ...
```
Looking at the code, this log would only be printed when merge request status is NOT `can_be_merged`. I believe the underlying issue is that scala-steward doesn't have any sort of back-off strategy while checking merge request status. Scala-steward probably exhausted all retires in a very short period of time while merge request status was still in "Checking" state therefore scala-steward didn't even attempt to merge the merge request at the end.
In this pull request, I added basic back-off between …
> Check merge request status with backoff

- build.sbt
Recent builds failed intermittently because Coursier could not be installed in the Docker image via `git.io/coursier-cli` (see https://github.com/coursier/coursier/issues/2724). The [current Coursier installation instructions](https://get-coursier.io/docs/cli-installation) does not mention `git.io/coursier-cli` anymore and recommends to download the appropriate binary directly.
Coursier is now installed by downloading and extracting https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux-static.gz. The installation processes of all binaries has been equalized by using `curl` and a common structure.
> Don't install Coursier via `git.io/coursier-cli`

- modules/core/src/main/resources/artifact-migrations.v2.conf
See 
* https://github.com/FluentLenium/FluentLenium/pull/1770
* https://github.com/FluentLenium/FluentLenium/releases/tag/v6.0.0
* https://repo1.maven.org/maven2/io/fluentlenium/
> Migrate `org.fluentlenium` to `io.fluentlenium`

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
> Add support for multiple configuration file locations

- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
When updates without a migration are present, but filterd out, updates with a migration are not even considered.
This fixes the behaviour.
An example is "com.dwijnand:sbt-dynver" in version 4.1.1. A bunch of later milestones are available. But the version 5.0.1 after the migration (#3026) is not considered.
```
2023-05-06 17:38:24,185 INFO  Ignore com.dwijnand:sbt-dynver : 4.1.1 -> 4.1.1+2-b4addc54 -> 4.1.1+4-b08da358 -> ... -> 5.0.0-M3+8-4d20677f -> 5.0.0-M3+10-ffae0733 -> 5.0.0-M3+12-c25bc496 (reason: no suitable next version)
```
> Updates with migration are no longer hidden

- modules/core/src/main/resources/artifact-migrations.v2.conf
https://github.com/sbt/sbt-eclipse/releases/tag/6.0.0
Can someone please check if that entry correct, since everything changes, the groupId and the artifactId:
```sbt
// From
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.4")
// To
addSbtPlugin("com.github.sbt" % "sbt-eclipse" % "6.0.0")
```
Also, this is a sbt-plugin. Is it necessary to add the suffix `_2.12_1.0` to the entries?
See https://repo1.maven.org/maven2/com/github/sbt/sbt-eclipse_2.12_1.0/6.0.0/
Thanks!
> Migration for sbt-eclipse

- modules/core/src/main/resources/artifact-migrations.v2.conf
See: https://github.com/sbt/sbt-pom-reader/pull/76
Released in: https://github.com/sbt/sbt-pom-reader/releases/tag/v2.4.0
before: https://index.scala-lang.org/sbt/sbt-pom-reader/artifacts/sbt-pom-reader/2.2.0
after: https://index.scala-lang.org/sbt/sbt-pom-reader/artifacts/sbt-pom-reader/2.4.0
> Migration for sbt-pom-reader

- modules/core/src/main/resources/artifact-migrations.v2.conf
To be merged after https://github.com/sbt/sbt-javaagent/pull/26 is merged and a new release is cut.
> sbt-javaagent is published to the com.github.sbt group ID

- README.md
- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/git/CommitMsg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/package.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/ForgePackageTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/CommitMsgTest.scala
Solves 2 issues in the `grouping` feature:
1. Failed grouping PRs (using `Update.Group`) get stuck: When a grouping PR is created by Scalasteward and the PR fails to build, then scalasteward does not create a new PR when new versions are released, because an existing PR is still open and the branch names are not unique. Solution: Introduce unique branch names in the grouping feature. This is similar to `Update.Single`
2. Commit messages are unclear. Solution: Added artifactIds and versions to the commit message. This is similar to `Update.Single`
> Improve grouping feature

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
The [`Option.when(cond)(value)`](https://www.scala-lang.org/api/2.13.x/scala/Option$.html#when[A](cond:Boolean)(a:=%3EA):Option[A]) Option builder was added to Scala 2.13 with https://github.com/scala/scala/pull/5995, and it's a nice, slightly more concise alternative to using if/else, eg: `if (cond) Some(value) else None`.
In this change, I've just updated the Scala Steward codebase to use `Option.when` where it's appropriate.
> Use `Option.when(cond)(value)` where appropriate

- build.sbt
- project/Dependencies.scala
Everthing Mill specific is handled by the mill-plugin.
We only need a version to download the Mill bootstrap script. Version `0.11.0-M11` is the last one still using Github Release pages, which is required as Scala-Steward needs to support Mill versions down to `0.6`.
Fix https://github.com/scala-steward-org/scala-steward/issues/3082
> Remove obsolete dependency on Mill

- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/io/WorkspaceAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/io/MockWorkspaceAlg.scala
To ensure that its workspace is clean, and that unintended files are not held over from previous runs, Scala Steward already erases the `repos` folder before starting its run. With new `run-summary.md` file introduced by https://github.com/scala-steward-org/scala-steward/pull/3071, we again want to be careful that the summary file from a previous run isn't picked up in a subsequent run.
https://github.com/scala-steward-org/scala-steward-action/pull/503 addressed this for the particular concern of GitHub Actions, by ensuring that the file wasn't persisted to cache, but @fthomas [pointed out](https://github.com/scala-steward-org/scala-steward-action/pull/503#issuecomment-1594477950) that this additional point at the start of Scala Steward's code was also a good place for removing any …
> Remove any run-specific files before starting run

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
As discussed in the issue here: https://github.com/scala-steward-org/scala-steward/issues/3092, it appears that when running scala steward against repos that are running an sbt version less than 1.7, it will cause it to fail silently due to the following error (traces have been truncated for brevity, full trace available in issue):
```
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
Caused by: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
Caused by: org.scalasbt.ipcsocket.NativeErrorException: [95] Not supported
Create a new server? y/n (default y)
```
It appears that this has been fixed in sbt since …
> Add sbt.server.forcestart option to SbtAlg to allow for sbt compatibility versions < 1.7

- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
PR #2515 in February 2022 introduced `dependencyOverrides` frequency settings to rate-limit how often PRs would be raised by Scala Steward for specific dependencies. Unfortunately this rate-limit isn't currently enforced for _grouped_ PRs (introduced by PR #2714 in October 2002), so that bug is fixed with this change.
This PR finishes off the work done with PR #3087 on fixing this bug (reported/discussed in issue #3096)
The rate-limiting in `PruningAlg.newPullRequestsAllowed()` was failing because it was being passed an empty `artifactLastPrCreatedAt` parameter, even when a previous PR for that artifact definitely _did_ exist. That empty `None` value (rather than a populated timestamp) was passed to `newPullRequestsAllowed()` in `PruningAlg.filterUpdateStates()` from the value returned by …
> Fix #3096: Don't ignore dependency-frequency-limits for *grouped* PRs

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/docs/mdoc/repo-specific-configuration.md
This generates `docs/repo-specific-configuration.md` from a mdoc source file such that the default values referenced in that documentation are always in sync with the actual default values in the source code.
> Use actual default values in `.scala-steward.conf` doc

- build.sbt
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
Several of Scala Steward's tests (eg `PullRequestRepositoryTest`) write files to the filesystem, using `MockConfig.mockRoot` as the base folder.
https://github.com/scala-steward-org/scala-steward/blob/b1de3ab58194f543f3526e013b363a52c675c769/modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala#L8
However, the folder is not erased between runs, and (possibly depending on operating system or Java version) the folder _can be_ the same path for multiple runs. In that case, tests may pass first time, but fail the second (this is the case for `PullRequestRepositoryTest`), as unexpected old files are encountered.
Here's a video showing that on my machine (Java 17.0.4, macOS 12.6):
https://github.com/scala-steward-org/scala-steward/assets/52038/bd5a1317-3828-460f-8b79-936645e97e …
> Ensure `mockRoot` test folder is always cleared before tests run

- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/CreatePullRequestPayload.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/UpdatePullRequestPayload.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/JsonCodecTest.scala
This PR was created with the idea of being reviewed commit by commit. Each commit contains an incremental change that makes it easier to review. Also some of the commits contain additional information in their description to help understand why the change was made.
<details><summary><b>I also recommend checking "Hide whitespace" when reviewing this PR!</b></summary></br>
</details>
This PR includes a new method in `ForgeApiAlg` for updating a PR details. This method will be used when updating a PR to ensure new updates (for example, when using grouping feature) are correctly detailed in the PR body/title.
Currently this is only supported for GitHub forge. Other forges will be added in subsequent PRs.
This PR fixes #3110.
> Ensure PR bodies and titles are recreated when updating PRs

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/docs/mdoc/repo-specific-configuration.md
Without the leading dot (not hidden),
Now that the config can be located inside the already hidden `.github` and `.config` folder (#3033) there is not need for the config file to be hidden as well inside that folders.
To stay backward compatible a hidden config `.scala-steward.conf` will always be preferred, only when such a hidden file can't be found anywhere, only then we try to read the "unhidden" `scala-steward.conf` in the same search order (root, `.github`, `.config` folders)
See https://github.com/scala-steward-org/scala-steward/pull/3033#issuecomment-1629376018
> Support `scala-steward.conf` (makes sense in `.github` and `.config` folder)

- modules/core/src/main/resources/scalafix-migrations.conf
These migrations attempt to rewrite some pattern that can be improved in the new release.
The rule rewrite following pattern:
```scala
input
.through(fs2.data.json.tokens)
.through(fs2.data.json.ast.values)
```
by
```scala
input
.through(fs2.data.json.ast.parse)
```
> Add fs2-data-json migrations

- modules/core/src/main/scala/org/scalasteward/core/io/process.scala
- modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
This wraps the `fs2.text.LineTooLongException` that is thrown by `fs2.text.linesLimited` which is used in `process.slurp` to enrich the error message with more helpful information.
Instead of this:
```
2023-07-19 15:34:45,215 ERROR Steward scala-steward-org/test-repo-1 failed
fs2.text$LineTooLongException: Max line size is 50 but 79 chars have been accumulated
at fs2.text$.$anonfun$linesImpl$1(text.scala:553)
...
```
we now get this:
```
2023-07-19 16:02:41,546 ERROR Steward scala-steward-org/test-repo-1 failed
org.scalasteward.core.io.process$ProcessLineTooLongException: 'mvn --batch-mode dependency:list -DexcludeTransitive=true' outputted a line longer than 50 chars. If the process executed normally and the buffer size is just too small, you can increase it with the --max-buffer-size …
```
> Improve error message on overlong lines in `process.slurp`

- modules/core/src/main/resources/scalafix-migrations.conf
This PR adds a Scalafix migration for sbt-tpolecat v0.5.0, which will [migrate many of the symbols in the project to a new package](https://github.com/typelevel/sbt-tpolecat/compare/v0.4.4...typelevel-migration-the-second).
> Add a Scalafix migration for sbt-tpolecat v0.5.0

- modules/core/src/main/resources/artifact-migrations.v2.conf
See
* https://github.com/playframework/playframework/pull/11927
Thanks!
> Play 2.9 will rename some artifacts

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/DependencyMetadata.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeRepo.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeType.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
This PR has 3 commits, which each can be reviewed separately and contain a single refactor:
* ➡️ replace conditionals in `UpdateInfoUrlFinder` with polymorphism on `ForgeType` - responsibility for generating urls displaying diffs & files moves to `ForgeType`
* 📦 introduce `ForgeRepo` as a parameter object
* 📦 introduce `Version.Update` as a parameter object
_(as it happens, each subsequent refactor here is smaller than the last)_
Cumulatively, the benefits of these changes are:
* **clearer responsibility**: when supporting a new type of forge, the responsibility is now solely implementing a new instance of `ForgeType`, without also having to search out additional switch statements elsewhere in the codebase
* **reduced parameter count** for several methods - for instance, …
> Refactor `UpdateInfoUrlFinder`, enhance `ForgeType`

- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/RepositoryResponse.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
As pointed out in issue [#3143](https://github.com/scala-steward-org/scala-steward/issues/3143) it looks like bitbucket cloud API has started to emit null jsvalue which break the circe custom decoder for RepositoryResponse.
The proposed solution is a bit naive. And I hacked a test around with what is already available.
Feel free to edit.
> Handle null value in bitbucket API response for repository

- modules/core/src/main/resources/default.scala-steward.conf
We have published RC2 now, so this line from #3169 can be reverted, so other Play libs are allowed to release a version `2.9.0-RC1` (since the `artifactId` is missing). Everything else can stay as it matches the exact version with the artifactId.
> Allow groupId `com.typesafe.play`, exact version `2.9.0-RC1`

- build.sbt
This provides `tput` for the scalafmt post-update hook.
Fixes #3120
> Add ncurses to the Docker image

- modules/core/src/main/scala/org/scalasteward/core/edit/update/ModulePositionScanner.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/update/ModulePositionScannerTest.scala
`ModulePositionScanner` currently reports wrong substring positions if an artifactId is a proper substring of a groupId. With this change, regex capturing groups are used to get the correct start indices of substring positions of `ModulePosition`s.
Closes #3206
> Use correct start indices in ModulePositionScanner

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/git/FileGitAlgTest.scala
> Reset instead of merge to update branches

- modules/core/src/main/resources/artifact-migrations.v2.conf
I am taking over the maintenance of [play-swagger](https://github.com/iheartradio/play-swagger/), which has been discontinued by `com.iheart`.
With the change in maintainer, the groupId has been changed. Therefore, please allow me to add instructions for migration settings.
[docs: Add guide for repository migration](https://github.com/iheartradio/play-swagger/pull/606)
> Migration for play-swagger

- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
This adds a `artifact-migrations` label for updates where the groupId and/or artifactId is changed. My main motivation for this label is to search for PRs that rewrite the groupId/artifactId on GitHub and to add this search to our [Artifact Migrations documentation](https://github.com/scala-steward-org/scala-steward/blob/main/docs/artifact-migrations.md).
> Add label for artifact migrations

- README.md
The Gitter chat accumulates an unanswered question every other month. We should stop advertising it IMO.
> Remove link to Gitter chat

- build.sbt
`DevMode` is nicer for development because it does not set `-Xfatal-warnings`. More about sbt-tpolecat's modes can be found here: https://github.com/typelevel/sbt-tpolecat#modes
> Use sbt-tpolecat's DevMode if CI env var is not set

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
... instead of hardcoding Maven Central. If the default resolver is not overridden it, it will be Maven Central, so nothing will change in this case.
I'm doing this for the same reason as given in https://github.com/scala-steward-org/scala-steward/pull/1899 where the hardcoded Maven Central was replaced in `SbtAlg` with the default resolver.
> Use default resolver in `MillAlg`

- build.sbt
This is not necessary anymore since https://github.com/scala-steward-org/scala-steward/pull/3233.
> Remove `-Xfatal-warnings` comment

- modules/core/src/main/resources/artifact-migrations.v2.conf
Old groupId(s)
- https://repo1.maven.org/maven2/com/mohiva/
- https://repo1.maven.org/maven2/io/github/honeycomb-cheesecake/
The new groupId:
- https://repo1.maven.org/maven2/org/playframework/silhouette/
The project itself:
- https://github.com/playframework/play-silhouette
Thanks!
> We migrate play-silhouette to the Play Framework organization

- docs/artifact-migrations.md
- docs/help.md
- docs/scalafix-migrations.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/docs/mdoc/artifact-migrations.md
- modules/docs/mdoc/scalafix-migrations.md
See https://github.com/scala-steward-org/scala-steward/pull/3221.
> Add links to PRs labelled with `artifact-migrations`

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
This contains two small refactorings which minimizes the diff of the BSP branch (https://github.com/scala-steward-org/scala-steward/pull/3236).
> Minimize diff to BSP branch

- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
This adds a default implementation for `BuildToolAlg#runMigration` that logs a warning that Scalafix migrations are not supported by the build tool. It saves some repeated text that is used for every build tool except sbt.
> Add default implementation for `BuildToolAlg#runMigration`

- README.md
The previous description was from the days when Scala Steward only worked with sbt builds. The new description is more generic and lists the supported build tools.
> Update short description of Scala Steward

- build.sbt
- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/Main.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/application/ValidateRepoConfigContext.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/ValidateRepoConfigAlgTest.scala
This removes the `Context.StewardContext` hierarchy. IMO `StewardContext` makes `Context.scala` unnecessarily more complicated only for saving one `case` in `Main.run` and a little duplication.
> Remove `StewardContext` hierarchy

- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeAuthAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
Prior to this change, the `gitAskPass` program was called once on start-up and its output was cached and used for API calls to the forge while Git itself does not cache its output but calls it anytime a password is needed. This means if the output of `gitAskPass` changes during a Scala Steward run, the new password is only used for Git operations but not for forge API calls.
With this change we now do the same as Git and call `gitAskPass` everytime the password is needed. This should make it easier to support GitHub Apps proper which require different access tokens during a run. See also https://github.com/scala-steward-org/scala-steward/issues/2973#issuecomment-1866224921.
> Do not cache the output of `gitAskPass`

- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/github/GitHubApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala
This removes the unnecessary `Repo` parameter from the function for modifying requests to add authentication headers. This parameter was added in #373 but wasn't ever used as can be observed in the diff of `ForgeSelection`. My motivation for adding `Repo` back then was to eventually use different credentials for different repositories for proper GitHub App support. But #3250 demonstrates that we can achieve this without this extra parameter.
> Remove repo from function for modifying requests

- modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/util/uri.scala
This instance is general enough to be added to the `util.uri` object.
> Move `Encoder[Uri]` to `util.uri`

- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
This allows hashes to also be separated with a `.` and `_` from the preceding component.
Here is for example what `Version.Component.parse("1.0.0+1320.38b57aa")` returned before this change and what it returns now:
```
before:
Numeric(1), Separator(.), Numeric(0), Separator(.), Numeric(0), Separator(+),
Numeric(1320), Separator(.), Numeric(38), Alpha(b), Numeric(57), Alpha(aa)
now:
Numeric(1), Separator(.), Numeric(0), Separator(.), Numeric(0), Separator(+),
Numeric(1320), Separator(.), Hash(38b57aa))
```
Recognizing hashes was added in #1549 but that PR gives no explanation why they only could preceded by `-` and `+`.
Closes #3124
> Recognize hashes if they are preceded by `.` or `_`

- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
This makes `--vcs-*` options unusable. If they are used, Scala Steward will print a message and exit with an error.
These options are deprecated since https://github.com/scala-steward-org/scala-steward/pull/2916 and should be replaced with the corresponding `--forge-*` options.
> Fail on `--vcs-*` options

- modules/core/src/main/resources/artifact-migrations.v2.conf
We are currently also migrating this plugin to the `com.github.sbt` groupId, the repo itself already lives under the sbt github repo organisation, also see
- https://github.com/sbt/sbt-pull-request-validator/pull/12
> Migrate `sbt-pull-request-validator`

- modules/core/src/main/resources/artifact-migrations.v2.conf
We just transferred the repo to the sbt GitHub organization and will publish new releases under its groupId:
- https://github.com/sbt/sbt-paradox-material-theme/pull/34#issuecomment-1919400459
> Migrate `sbt-paradox-material-theme` to `com.github.sbt`

- modules/core/src/main/resources/default.scala-steward.conf
We're already seeing [Scala Steward raise PRs for Scala 3.4.0](https://github.com/guardian/play-secret-rotation/pull/432), this might be unintentional, as there are no [GitHub release notes for 3.4.0](https://github.com/lampepfl/dotty/releases/tag/3.4.0)?
See also https://github.com/scala-steward-org/scala-steward/pull/2337 & https://github.com/scala-steward-org/scala-steward/issues/1104.
cc @Kordyjan
> Ignore Scala 3.4.0 until it's announced

- modules/core/src/main/resources/scalafix-migrations.conf
Context: https://github.com/typelevel/otel4s/pull/426.
> Add migrations for `otel4s` 0.5.0

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigLoaderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
The merging of the default Scala Steward configuration for pinned artifacts was reversed.
In contrast to the comment and intend:
```Scala
//  Strategy: union with repo preference in terms of revision
```
This pull-request fixes the merging order and adapts the test. In addition it adds tests that show how `updates.pin` can  be used to control Scala LTS release updates.
Discussed in 
- #3302 
- #2467
> Fix the merging order updates.pin

- modules/core/src/main/resources/artifact-migrations.v2.conf
- https://github.com/sbt/sbt-jupiter-interface/issues/64
Related:
- https://github.com/VirtusLab/scala-steward-repos/pull/356
> Migrate `sbt-jupiter-interface` to `com.github.sbt`

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala
This is done in the [`RepoConfigLoader`](https://github.com/scala-steward-org/scala-steward/blob/main/modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigLoader.scala#L35) with the default config and the supplied additional configs. And now here in the same way.
The `RepoConfig.combine`  function treats the 2nd argument as the one overwriting the 1st one in cas emerging doesn't make sense. This applies at the moment only for "pin".
This fixes the problem reported in https://github.com/typelevel/sbt-typelevel/pull/703#issuecomment-2079703210 
Without the fix the https://github.com/typelevel/sbt-typelevel/blob/main/.scala-steward.conf was overwriting the config supplied by the repo https://github.com/typelevel/sbt-typelevel/blob/main/.scala-steward.conf
This became a …
> Combine `RepoConfig` with the one taken the higher importance on the right side

- modules/core/src/main/resources/default.scala-steward.conf
Re-enable Scala 3 Next PRs after #3328 got merged and is part of https://github.com/scala-steward-org/scala-steward/releases/tag/v0.30.0
> Allow 3.4.x pull request for users already on Scala Next

- modules/core/src/main/scala/org/scalasteward/core/data/package.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
* the artifact contains a cross version, so only comparing the artifact name leads to the correct result 
* adapt lowest Scala 3 NEXT version
Tested with  https://github.com/playframework/play-json to prevent in the future pull requests like https://github.com/playframework/play-json/pull/1035
> Fix Scala 3 check

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/ExitCodePolicy.scala
- modules/core/src/main/scala/org/scalasteward/core/application/RunResults.scala
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
When even one repository fails in a scala steward run the workspace is not persisted by GitHub Actions because GH Actions won't persist the workspace of a failing job. Persisting workspace is crucial for respecting `pullRequests.frequency` configuration because the workspace is how scala steward records that it has opened a pull request. This means that one failing repository can cause a lot of user annoyance because their configuration is no longer respected and they get too many PRs opened. This change aims to fix that by only returning a failure code if *all* repos have failed. So long as at least one repository succeeded the exit code will be success and the workspace will persist. If administrators need to know what repos are failing they can use the jobs summary introduced by: …
> Only return a failure exit code when all repos have failed

- modules/core/src/main/scala/org/scalasteward/core/application/ExitCodePolicy.scala
- modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala
Aligning expectation that "all repos succeed" means there are no repos with failures.
This brings back the old behavior from RunResults:
if (reposWithFailures.isEmpty) ExitCode.Success else ExitCode.Error
See:
https://github.com/scala-steward-org/scala-steward/compare/6259adb0...9d9460af
> Fix exit code policy

- modules/core/src/main/resources/artifact-migrations.v2.conf
It was already in the github org for a while, but wasn't changed.
Should be merged once https://github.com/scalameta/metaconfig/actions/runs/10093438821 release is done.
> chore: Metaconfig has been moved to org.scalameta

- modules/core/src/main/scala/org/scalasteward/core/persistence/KeyValueStore.scala
I came across this line, proved that `fa.flatMap(a => f(a).flatTap(g)) <-> fa.flatMap(f).flatTap(g)`, and applied it to this line. Hope this small change reduces complexity a bit.
> Simplify KeyValueStore.modifyF

- modules/core/src/main/resources/artifact-migrations.v2.conf
After more than two years without any activity and because original maintainers [didn't answer the questions](https://github.com/valskalla/odin/issues/499) about current status of the project, I decided to fork the project and start publishing it under `dev.scalafreaks` organization. The project is a fork a not an ownership transfer because it has not been possible to contact maintainers.
Some of the users have already migrated and are working with the new versions. I hope this explanation is enough to accept this PR 🙏🏽
> Migrate com.github.valskalla:odin to dev.scalafreaks:odin

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
Mill `0.12` will support more build file names.
* `build.sc`
* `build.mill`
* `build.mill.scala`
This change makes sure Scala Steward will detect these.
Fix https://github.com/scala-steward-org/scala-steward/issues/3409
> Support more Mill buildfiles (build.mill, build.mill.scala)

- build.sbt
Continuing on https://github.com/scala-steward-org/scala-steward/issues/2590, this allegedly will trigger buildx during a CI build
> Add dockerBuildxPlatforms

- README.md
- modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
Fixes https://github.com/scala-steward-org/scala-steward/issues/3371.
I tested these changes on the same `scala-cli`-based repository I was having issues with and the correct PRs got created.
> `scala-cli`: `using dep` and `using test.dep` directives support

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
since `fileAlg.createTemporarily` is a total function, it's a little better to use `foldMap` rather than `collectFold`
> use foldMap instead of collectFold

- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
When scala-steward attempts to update a PR and a file/folder in the repository has the same name as the branch that it is being run against, it fails with a fatal error: 
`fatal: ambiguous argument 'main': both revision and filename`
This change should fix the ambiguity
> Fix ambiguous argument 'main'

- modules/core/src/main/scala/org/scalasteward/core/forge/azurerepos/JsonCodec.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/JsonCodecTest.scala
> fix azure repos targetRefName

- docs/running.md
- modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
- modules/docs/mdoc/running.md
[Git requires](https://github.com/git/git/commit/3b0bf2704980b1ed6018622bdf5377ec22289688) that a repository directory be owned by the user executing `git`. In the normal case, it will print a message
> fatal: detected dubious ownership in repository …
which is easily searchable online, but unfortunately `git config` does not print such a nice message, and simply prints
> fatal: not in a git directory
which is misleading and hard to diagnose.
This came up for us when running Scala Steward as a AWS Fargate task using AWS EFS as its persistent storage. We configured the task to mount the EFS volume using UID 1001, which is the default UID for sbt-native-packager Docker containers, but in fact, Scala Steward current runs as root (#3283). While looking into the issue, we noticed that the …
> Improve documentation for workspace ownership mismatches

- modules/core/src/main/resources/artifact-migrations.v2.conf
bucket4j went for a versioning and deployment scheme split in 8+, 11+ and 17+. I moved to 17+ as that should be the most common, and the scalasteward user should now at least be notified of the option to update, allowing to override to a different one if wanted.
> add migration for bucket4j

- modules/core/src/main/resources/default.scala-steward.conf
Due to problem with Scala 3 release 3.6.0 should be forgotten. Do not recommend updates, block next release 3.6.1 hotfix that would shortly released.
> Block Scala 3.6.1

- modules/core/src/main/resources/default.scala-steward.conf
Ignore Scala 3.7.0 so we don't forget it, when the release comes closer.
> Ignore Scala 3.7.0

- modules/core/src/main/resources/default.scala-steward.conf
This release must be avoided according the changelog: https://github.com/typelevel/doobie/releases/tag/v1.0.0-RC6
See issue https://github.com/scala-steward-org/scala-steward/issues/3442
> Ignore doobie 1.0.0-RC6

- modules/core/src/main/resources/default.scala-steward.conf
Scala 3.5.2 is officially available. The next release 3.6.1 and broken 3.6.0 is already blocked.
> Unlock Scala 3.5.2 updates

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
- project/Dependencies.scala
This replaces the `mill` script from the Mill project with the script from the dedicated [`millw`](https://github.com/lefou/millw) project.
There is no version of the former script, that properly support all Mill version that Scala Steward can handle.
The `lefou/millw` project supports all Mill version.
Hopefully fix https://github.com/scala-steward-org/scala-steward/issues/3463
I didn't test it locally due to not having set up a test environment for Scala steward. Let me know if that is a deal breaker for you.
> Replace com-lihaoyi/mill/mill script with lefou/millw/millw

- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
This solves #3465. This ended up being quite straightforward as I didn't realize there was already a well-defined JSON serialization for updates. I think the only downside of this is a slightly larger payload that gets sent to GitHub each time a PR is created, but it does enable some interesting use cases of taking automated actions on the resulting PRs.
> Add JSON metadata in PRs

- build.sbt
JDK 21 requires that `sbt` is of version 1.9.0 or greater. This poses problems to some projects. As the other changes to support a multi-platform docker image had flaws too, this change shouldn't be a problem.
Fixes: #3467
> Revert the base docker image back to JDK 11

- modules/core/src/main/resources/default.scala-steward.conf
We're starting the release procedure for 3.6.2-RC1 and thus blocking potential upgrades to 3.6.2 stable until annouced
> Block Scala 3.6.2 until official announcment

- .github/workflows/ci.yml
- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeAuthAlg.scala
Fix for #3480
cc @nikita-ty754 @mzuehlke
> Support Basic Auth for GitHub again

- docs/repo-specific-configuration.md
- modules/core/src/main/resources/default.scala-steward.conf
- modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RetractedArtifact.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RetractedArtifactTest.scala
- modules/docs/mdoc/repo-specific-configuration.md
The `updates.retraced` section of the `scala-steward.conf` allows to declare updates that should be retracted. Each entry must have a `reason`, a `doc` URL and a list of dependency patterns.
Example:
```
updates.retracted = [
{
reason = "Ignore version 3.6.0 as it is abandoned due to broken compatibility",
doc = "https://contributors.scala-lang.org/t/broken-scala-3-6-0-release/6792",
artifacts = [
{ groupId = "org.scala-lang", artifactId = "scala3-compiler", version = { exact = "3.6.0" } }
]
}
]
```
Retraction of Pull Request is only possible, if the workspace is persisted correctly. (https://github.com/scala-steward-org/scala-steward/blob/main/docs/faq.md#why-doesnt-self-hosted-scala-steward-close-obsolete-prs)
Fixes: #3445
> Retract previously opened Pull Request

- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
With the addition of structured metadata to PR description the content was growing too large when multiple updates got grouped together. Now the metadata gets only appended, if the length is still below 65536 characters.
Caused-by: #3466
Fixes: #3476
> Ensure PR description is not too long

- modules/core/src/main/resources/default.scala-steward.conf
> Update Scala to 3.6.2

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
Successor to #3241. This should not be merged before Q3 2024 so that people have enough time to see the current deprecation messages and migrate to the `--forge-*` options.
> Remove `--vcs-*` options

- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/SbtVersion.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/data/ScalaVersion.scala
- modules/core/src/main/scala/org/scalasteward/core/data/CrossDependency.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Version.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/data/PullRequestNumber.scala
- modules/core/src/main/scala/org/scalasteward/core/util/Timestamp.scala
`deriveUnwrappedCodec` is from circe-generic-extras which is not available for Scala 3. This is a small step towards replacing that library.
> Replace `deriveUnwrappedCodec` with handwritten de-/encoders

- modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/ScannerAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/GroupRepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/ScalafmtConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigLoaderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
This changes `RepoConfig` and the other `*Config` classes such that all values are optional and there are no default parameter values except `None`s. This allows us to get rid of circe-generic-extras' `Configuration.default.withDefaults` and `deriveConfiguredCodec` since missing `Option` values do not cause an error during decoding. So `{}` can still be decoded into a `RepoConfig`, and there are a lot of tests in `RepoConfigAlgTest` that ensure that sparse configurations with a lot of missing values can still be decoded. 
Another benefit of this change is that `RepoConfig.show` can now use `deepDropNullValues` so that logged `RepoConfig`s only include stuff which was actually set by a user. For example, before this change, logging a `RepoConfig` was similar to this:
```
INFO  Parsed repo …
```
> Make all values in config classes optional

- build.sbt
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/parser.scala
- modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrations.scala
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChange.scala
- modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactChanges.scala
- modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/parserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
- project/Dependencies.scala
This concludes the work started in #3514 and #3515 to remove the dependency on circe-generic-extras.
Here are some notes about the changes:
- `Resolver` cases had non-optional fields with defaults that needed to be made optional so that the derived decoder does not fail if those are not provided
- `ArtifactChange` and `ArtifactChanges` could have always used `deriveDecoder` since the case classes have no defaults
- `ScalafixMigrations` had a default value but a `scalafix-migrations.conf` without a `migrations` field makes no sense to me and it should be the same as `ArtifactChanges` anyway
> Remove circe-generic-extras

- modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
- modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
This is in preparation for compiling with Scala 3.
See https://docs.scala-lang.org/scala3/guides/migration/incompat-syntactic.html#parentheses-around-lambda-parameter
> Add parentheses around lambda parameters

- modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillDepParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
- modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestFrequencyTest.scala
- modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
This is in preparation for compiling with Scala 3 and prevents warnings about pattern bindings with refutable patterns like this:
```
-- Warning: modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala:218:27
218 |    val Right(repoCache) = decode[RepoCache](
|                           ^
|pattern's type Right[io.circe.Error, org.scalasteward.core.repocache.RepoCache] is more specialized than the right hand side expression's type Either[io.circe.Error, org.scalasteward.core.repocache.RepoCache]
|
|If the narrowing is intentional, this can be communicated by adding `: @unchecked` after the expression,
|which may result in a MatchError at runtime.
|This patch can be rewritten automatically under -rewrite -source 3.2-migration.
```
The changes here we done by the Scala …
> Annotate pattern bindings with refutable patterns

- modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
- modules/core/src/test/scala/org/scalasteward/core/coursier/DependencyMetadataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/ForgeRepoTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/azurerepos/AzureReposApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucket/BitbucketApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/bitbucketserver/BitbucketServerApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubAuthAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinderTest.scala
This is in preparation for compiling with Scala 3 and prevents errors like
```
-- [E008] Not Found Error: modules/core/src/test/scala/org/scalasteward/core/coursier/DependencyMetadataTest.scala:7:28
7 |import org.http4s.implicits.http4sLiteralsSyntax
|                            ^^^^^^^^^^^^^^^^^^^^
| value http4sLiteralsSyntax is not a member of object org.http4s.implicits
```
and
```
-- [E008] Not Found Error: modules/core/src/test/scala/org/scalasteward/core/forge/github/GitHubAuthAlgTest.scala:4:24
4 |import io.circe.literal.JsonStringContext
|                        ^^^^^^^^^^^^^^^^^
|               value JsonStringContext is not a member of io.circe.literal
```
It also prefers importing `org.http4s.syntax.literals._` over `org.http4s.implicits._` so that we import less and are more …
> Harmonize imports for http4s and circe literals

- build.sbt
The Scala 3 compiler complains about the indentation of `InitialCommandsTest`. This fixes it.
> Properly indent `InitialCommandsTest`

- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala
- modules/core/src/main/scala/org/scalasteward/core/data/Update.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
- modules/core/src/main/scala/org/scalasteward/core/util/string.scala
- modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala
- modules/core/src/test/scala/org/scalasteward/core/util/stringTest.scala
This is in preparation for compiling with Scala 3 and probably the last chunk from #2065 that gets its own PR.
> Tweak code that uses refined so that it compiles with Scala 3

- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
Using one variable is enough since `millVersionNameInConfig` was a suffix of `millVersionName`. If Scala Steward is allowed to edit files in ending with `mill-version` it is also allowed to edit `.mill-version` files.
> Use only one variable for `mill-version` files

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
If a `.mill-version` exists there is no need to also read `.config/mill-version` and then discard its content.
> Short-circuit when reading `mill-version` files

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Running Mill 0.11 with `--ticker=false` (which has been added in #3511) produces the following error:
```
Parsing exception Position 1:9, found "=false"
```
The `--ticker <bool>` option has been added to Mill in 0.12.0 if I'm reading [this commit](https://github.com/com-lihaoyi/mill/commit/0c44ffa3e1c197bef13df66baf452b1bf064433d) correctly. We therefore need to use `--disable-ticker` with Mill 0.11 and `--ticker false` with Mill >= 0.12.
> Run Mill 0.11 with `--disable-ticker` instead of `--ticker false`

- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
Takes care of https://github.com/scala-steward-org/scala-steward/pull/3410#issuecomment-2585403190.
> Extract Mill plugins also from `build.mill{,.scala}` files

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
I forgot to update this reference in #3515. This is a subtle change in semantics. If `allow == Some(Nil)`  `allow.isEmpty` is `false` and `allowOrDefault.isEmpty` is `true`.
> Use `allowOrDefault` in `UpdatesConfig.isAllowed`

- modules/core/src/main/resources/default.scala-steward.conf
> Update Scala to 3.6.3

- modules/core/src/main/scala/org/scalasteward/core/repocache/RefreshErrorAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/repocache/RepoCacheAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/repocache/RefreshErrorAlgTest.scala
This is a small refactoring that rewrites `checkCache` as for-comprehension which I think is a little bit easier to read. It also removes the second parameter from `skipIfFailedRecently` which was a needless complication.
> Rewrite `RepoCacheAlg.checkCache` as for-comprehension

- build.sbt
This is not necessary anymore with Scala 2.13.16.
> Don't exclude `warnUnusedPatVars` compiler option

- modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
This adds support for running Scalafix migrations in Scala CLI builds by using the `scala-cli --power fix --scalafix-rules ...` command that was added to Scala CLI 1.6.0.
Example PR: https://github.com/scala-steward-org/test-repo-1/pull/115 
Closes: #3486
> Support Scalafix migrations in Scala CLI builds

- build.sbt
- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/BuildToolDispatcher.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/GradleAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/gradleParser.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/package.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/gradle/GradleAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/gradle/gradleParserTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
- project/Dependencies.scala
This adds partial support for Gradle builds that use a [version catalog](https://docs.gradle.org/current/userguide/version_catalogs.html) (i.e. a `gradle/libs.versions.toml` file). Dependencies are extracted from the version catalog just by parsing the `libs.versions.toml` file. Since the version catalog only contains libraries and no resolvers, the default resolver is used for the `Scope` of these libraries.
The support is only partial, because
* a default resolver is assumed (as mentioned above)
* dependencies and plugins that are defined in other Gradle build files are ignored
* [additional version catalogs](https://docs.gradle.org/current/userguide/version_catalogs.html#sec:multiple-catalogs) are ignored
* a version catalog with a custom name is ignored
Closes: #3534
> Extract dependencies from Gradle Version Catalogs

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
- modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/gradle/GradleAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala
The default resolver - which is Maven Central if none is provided by the `--default-maven-repo` option - is now used in multiple places where a list of resolvers is expected. It feels like an arbitrary restriction that we only allow one resolver and always wrap that in a list everywhere we use it. Why not allow `--default-maven-repo` to be a repeating option instead so that `Config` has a `List[Resolver]`. This PR does exactly that. It could be useful if a user wants to resolve Scalafmt via resolver A and Gradle dependencies via resolver B for example.
> Support multiple default resolvers

- modules/core/src/main/resources/scalafix-migrations.conf
... which is also compatible with Scala CLI.
See https://github.com/scala-steward-org/scala-steward/issues/3486#issuecomment-2629120439.
> Use modern syntax for `dependency:` Scalafix rules

- modules/core/src/main/scala/org/scalasteward/core/forge/ForgeType.scala
- modules/core/src/main/scala/org/scalasteward/core/forge/data/NewPullRequestData.scala
- modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
Depending on the used forge the size of the description of a Pull Request differs. With the additional metadata this limit can be easily exceeded.
This Pull Request sets the allowed length to:
* global default: 65536
* Azure: 4000
* BitbucketServer: 32768
Closes: #3543
> Make maximum Pull Request length configurable

- build.sbt
- docs/repo-specific-configuration.md
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala
- modules/docs/mdoc/repo-specific-configuration.md
- modules/docs/src/main/scala/DocChecker.scala
- project/Dependencies.scala
This checks that the example `.scala-steward.conf` in the docs is equivalent to the JSON one gets when parsing, decoding and encoding that example. It ensures that the values used in the example are the same as the values in the decoded `RepoConfig`.
With this change, the `docs/mdoc` task fails currently with:
```diff
error: repo-specific-configuration.md:211:1: Diff between parsed input (-) and encoded object (+):
"groupId" : "com.example",
-        "version" : "2."
+        "version" : {
+          "prefix" : "2."
+        }
},
"pullRequests" : {
-        "frequency" : "30 day"
+        "frequency" : "30 days"
}
"pullRequests" : {
-        "frequency" : "14 day"
+        "frequency" : "14 days"
}
"signoffCommits" : true,
-  "updatePullRequests" : "always | on-conflicts | never",
+ …
```
> Verify the example `.scala-steward.conf`

- modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/PostUpdateHook.scala
- modules/core/src/main/scala/org/scalasteward/core/edit/scalafix/ScalafixMigration.scala
- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsFinderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/scalafix/ScalafixMigrationsLoaderTest.scala
- modules/core/src/test/scala/org/scalasteward/core/forge/data/NewPullRequestDataTest.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
This uses `RepoConfig#signoffCommits` for Scalafix migrations and post-update hooks commits and removes the `signoffCommits` fields from `PostUpdateHook` and `ScalafixMigration` (which were added in #3432). The latter fields concealed that `RepoConfig#signoffCommits` was partially ignored for post-update hooks and completely ignored for Scalafix migrations.
> Use `RepoConfig#signoffCommits` for migrations and hooks

- modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
- modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
When running Scalafix migrations in Scala CLI builds, we disable [built-in Scala CLI rules](https://scala-cli.virtuslab.org/docs/commands/fix/#built-in-rules) so that any changes are only coming from the Scalafix migrations.
See https://github.com/scala-steward-org/scala-steward/issues/3486#issuecomment-2629120439.
> Disable built-in Scala CLI rules in Scalafix migrations

- build.sbt
Currently, we're experiencing this issue in CI workflows:
```terminal
[info] ERROR: failed to solve: process "/bin/sh -c npm install --global yarn" did not complete successfully: exit code: 127
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:745)
```
It turns out, that we run `npm install --global yarn` within the docker settings defined in the SBT build. So, it's an attempt to fix the issue.
> Fix the assembly of the Docker image in CI

- modules/core/src/main/resources/default.scala-steward.conf
> Update Scala to 3.6.4

- modules/core/src/main/resources/artifact-migrations.v2.conf
Per original repo [lemonlabsuk/scala-uri](https://github.com/lemonlabsuk/scala-uri?tab=readme-ov-file), it's no longer maintained and the new maintained fork is [indoorvivants/scala-uri](https://github.com/indoorvivants/scala-uri).
> Add artifact migration for scala-uri

- modules/core/src/main/resources/default.scala-steward.conf
We're starting the release for 3.7.1-RC1 but 3.7.0 was not yet publicly announced (planned for 7th May)
> Block automatic upgrades to Scala 3.7.1

- modules/core/src/main/resources/artifact-migrations.v2.conf
- modules/core/src/main/resources/scalafix-migrations.conf
weaver has changed stewardship from `com.disneystreaming` to `org.typelevel`.
This PR modifies the group ID and adds a rewrite rule for upgrading to `0.9.0`.
> Update weaver to `0.9.0`

- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestUpdateFilterTest.scala
A colleague mentioned to me that some of our `pullRequests.grouping` were not pulling in all the artifacts we were expecting - while looking into this, I realised that I wasn't 100% clear on where wildcards could be used in `pullRequests.grouping`, so I wrote this test to exercise all the cases that were relevant to us, and see what worked - this may be tested elsewhere to some extent in the Scala Steward codebase, but I think it's helpful to drill into the specific functionality with these new tests on `PullRequestUpdateFilter`.
Note that the tests only assert the behaviour is what it _is_ (meaning config parsing behaviour is tested to be consistent over time), not what it might 'ideally' be. By that, I mean that for myself, it would be ideal if the matching behaviour automatically …
> Add tests for `pullRequests.grouping` syntax

- docs/help.md
- modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
See discussion [here](https://github.com/scala-steward-org/scala-steward/pull/3282#issuecomment-3250222315); some repos are still overflowing the buffer size and not receiving scala-steward updates.
> Bump default maxBufferSize

- modules/core/src/main/resources/default.scala-steward.conf
[MUnit 1.1.2 removed a trait needed for binary compatibility with munit-scalacheck](https://github.com/scalameta/munit/issues/983). This was [fixed in `v1.2.0`](https://github.com/scalameta/munit/releases/tag/v1.2.0).
Since it is common to use MUnit with munit-scalacheck, many Scala Steward PRs are probably failing to build due to the incompatibility. Many will not receive the `v1.2.0` update until `v1.1.2` is merged. Therefore it makes sense to retract `v1.1.2` and let Scala Steward proceed directly to `v1.2.0`.
> Retract MUnit 1.1.2

- modules/core/src/main/resources/default.scala-steward.conf
- not sure if I have all the correct packages here, is it necessary to ignore everything in the same release?
> ignore http4s 0.23.31

- README.md
- modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
The [zio-sbt-ci sbt plugin](https://github.com/zio/zio-sbt/tree/main/zio-sbt-ci) regenerates a GitHub workflow just like some of the other supported sbt plugins. Unfortunately, it uses a different sbt command for this so some tweaks are needed.
Note that the zio plugin does not follow name-conventions, its artifact id really is zio-sbt-ci and not ~sbt-zio-ci~.
Thanks for scala-steward. It is a massive time saver!
> Add github ci generate hook for zio-sbt-ci

- modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestsConfig.scala
- modules/core/src/test/scala/org/scalasteward/core/repoconfig/PullRequestsConfigTest.scala
This fixes a bug that came in with the initial introduction of the `pullRequests.draft` config setting:
* https://github.com/scala-steward-org/scala-steward/pull/3628
The bug was that when combining global & local repo config, the result of combining `pullRequests.draft = true` with a config with _no_ setting for `pullRequests.draft` would be that `pullRequests.draft` was _unset_ (ie given the value `None`, rather than `Some(true)`.
Here's an example of where this was a problem in the wild:
* https://github.com/guardian/scala-steward-public-repos/pull/102#issuecomment-3356561770
This arose because of the behaviour of `.mapN()`, which I hadn't really thought through:
https://github.com/scala-steward-org/scala-steward/blob/373d5a70533a024389bb93f5028d0fee81a6cbd6/modules/core/src/main/scala/ …
> Fix: repo-config for `pullRequests.draft` should not be wiped when combined with _unset_ config

- modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
Scala Steward instance using the Scala-Steward-Github-Action stopped updating scalafmt some time ago. The action launches scala-steward using coursier and that picks the highest available Scala version for its artifacts. As the scalafmt-core artifact isn't available for Scala 3, the `defaultScalaBinaryVersion` can't be used. Instead, I always use the 2.13 artifact to find the available versions.
> scalafmt-core is not available for Scala 3
