scala-steward-org/scala-steward

repos.md
Cool idea :-) 
Have you thought about integrating with Dependabot?
=> Add vectos/formulation

repos.md
https://github.com/sphereio/sphere-scala-libs
=> add sphereio scala libs

repos.md
=> add two of my book codes

modules/core/src/main/scala/eu/timepit/scalasteward/github.scala, modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/main/scala/eu/timepit/scalasteward/steward.scala, modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
... so that version ranges are matched literally.
=> Quote version string in replaceAllIn

build.sbt, modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/main/scala/eu/timepit/scalasteward/sbt.scala, modules/core/src/main/scala/eu/timepit/scalasteward/util.scala, modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala, modules/core/src/test/scala/eu/timepit/scalasteward/sbtTest.scala, project/Dependencies.scala
Reverts fthomas/scala-steward#33
=> Revert "Revert 32 topic/lockstep updates"

repos.md
This won't be a steward to the template itself, but for the template's build.
=> Add http4s.g8 template

modules/core/src/main/scala/eu/timepit/scalasteward/github.scala
=> Use a friendlier PR message

modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
=> Handle Update.Group where all artifactIds are common suffixes

repos.md
=> Adding Fs2 Rabbit

modules/core/src/main/scala/eu/timepit/scalasteward/NameResolver.scala, modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/test/scala/eu/timepit/scalasteward/NameResolverTest.scala
=> Improve update naming convention

repos.md
... excluding the libraries as they don't change dependencies in minor releases.
=> Add Akka repositories

repos.md
note: I'm a maintainer on this project, ping @mefellows
=> Add mefellows/sbt-dotenv

modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/test/scala/eu/timepit/scalasteward/model/UpdateTest.scala
=> Require that the artifactIdsPrefix is at least three characters long

repos.md
Thanks for providing this service!
=> Add cb372/scalacache to repos.md

modules/core/src/main/scala/eu/timepit/scalasteward/application/Config.scala, modules/core/src/main/scala/eu/timepit/scalasteward/github/Url.scala, modules/core/src/main/scala/eu/timepit/scalasteward/github/http4s/Http4sGitHubApiAlg.scala, modules/core/src/main/scala/eu/timepit/scalasteward/github/http4s/Http4sUrl.scala, modules/core/src/test/scala/eu/timepit/scalasteward/github/http4s/http4sUrlTest.scala
=> Make GitHub API host configurable

modules/core/src/main/scala/eu/timepit/scalasteward/model/Update.scala, modules/core/src/test/scala/eu/timepit/scalasteward/NameResolverTest.scala
=> Add "config" to the list of common suffixes

repos.md
=> Add julienrf/endpoints

repos.md
Adding
- [NeQuissimus/circe-kafka](https://github.com/NeQuissimus/circe-kafka)
- [NeQuissimus/nequi-kafka](https://github.com/NeQuissimus/nequi-kafka)
- [NeQuissimus/zio-slf4j](https://github.com/NeQuissimus/zio-slf4j)
=> Add NeQuissimus/* repositories

repos.md
A few more that I've built that it would be nice to keep externally updated.
=> Add More ChristopherDavenport Libraries

repos.md
Thanks for the great work on this tool! Would be very thankful if you could add my repo to your list!
=> Add Slakah/uritemplate4s to repos.md

repos.md
Thx for the great tool! Unfortunately, because of specifics of our dev process, using it so far comes with too much overhead. This could be easily fixed though by having:
- all commits form the Steward being signed with a gpg key
- all lib updates being put in a single PR, with a separate commit per lib.
Let us know if we can help with those!
Please also see
https://github.com/rchain/rchain/pull/1880#issuecomment-439888962
https://github.com/rchain/rchain/pull/1872#issuecomment-439315572
Cheers!
=> Remove rchain/rchain (please see description :))

repos.md
@leonmaia @jeremyrsmith I feel this could be useful. Let me know what do you think!
=> Adding finagle-postgres

build.sbt, modules/core/src/main/scala/eu/timepit/scalasteward/application/Cli.scala, modules/core/src/main/scala/eu/timepit/scalasteward/application/Config.scala, modules/core/src/main/scala/eu/timepit/scalasteward/application/Context.scala, modules/core/src/main/scala/eu/timepit/scalasteward/io/WorkspaceAlg.scala, modules/core/src/main/scala/eu/timepit/scalasteward/steward.scala, modules/core/src/test/scala/eu/timepit/scalasteward/git/GitAlgTest.scala, project/Dependencies.scala, scripts/run.sh
Hi @fthomas I sketched this really quick and it might be a bit rough, let me know what you think!
=> Suggestion: Add CLI to override config values

modules/core/src/main/scala/eu/timepit/scalasteward/application/Cli.scala, modules/core/src/main/scala/eu/timepit/scalasteward/application/Config.scala, modules/core/src/main/scala/eu/timepit/scalasteward/git/GitAlg.scala, modules/core/src/test/scala/eu/timepit/scalasteward/git/GitAlgTest.scala, scripts/run.sh
=> GPG sign commits

repos.md
Thanks for this amazing tool! :heart_eyes: 
I would be very interested in having my repo added to your list!
Thanks!
=> Add ccamel/playground-binding.scala to repos.md

repos.md
added nice-uuid and nice-url-encode-decode
=> Add daandi's projects

modules/core/src/main/scala/org/scalasteward/core/NameResolver.scala, modules/core/src/main/scala/org/scalasteward/core/util/package.scala, modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
Add util.intersects from https://github.com/fthomas/scala-steward/pull/153/commits/e81c71b1f1cd366c8cd765871e542f2814b12bc2 because it can already be used in master.
=> Add util.intersects

modules/core/src/main/scala/org/scalasteward/core/git/package.scala, modules/core/src/main/scala/org/scalasteward/core/update/show.scala, modules/core/src/test/scala/org/scalasteward/core/update/showTest.scala
which makes the code hopefully a bit more clear.
=> Small refactoring and rename of name

repos.md
On behalf of Alexandre Archambault
=> Add almond-sh/almond

repos.md
=> Add http4s-modules (h4sm) to repos list

repos.md
=> Add scala-pet-store to repos list

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/test/scala/org/scalasteward/core/application/ConfigTest.scala
=> Fix disable sandbox flag

modules/core/src/main/scala/org/scalasteward/core/dependency/parser.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala
... by replacing the regex with `split` calls.
=> Simplify parseSingleUpdate

README.md
=> Add community section to README

repos.md
=> Add olafurpg/sbt-ci-release

repos.md
This looks like an amazingly useful service. Thank you 😍
=> add slickless

repos.md
this repo is in if-it-ain't-broke-don't-fix-it mode
=> remove scala/scabot

repos.md
I am an administrator on the repository, as is @hrhino who has also approved. @jmcardon is on a hiatus at the moment. 
Keeping this up to date is desired as it is going to be on the community build.
=> Add jmcardon/tsec

repos.md
https://github.com/daniel-shuy/scripted-scalatest-sbt-plugin
=> Add scripted-scalatest-sbt-plugin

repos.md
https://github.com/daniel-shuy/liquibase-slick-codegen-sbt-plugin
=> Add liquibase-slick-codegen-sbt-plugin

repos.md
=> Add scalameta/metabrowse

modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
Hi @fthomas, this latest version of `sbt-updates` has some fixes around `sbt` plugins.
=> Bump sbt-updates version

modules/core/src/main/scala/org/scalasteward/core/model/Update.scala, modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
=> Ignore lines that contain "mimaPreviousArtifacts"

repos.md
More Integrations, disjoint releases, new projects.
=> Add Epimetheus Supporting Libraries

repos.md
As one of the maintainers of unfiltered we would like the bot to run there
=> Add unfiltered/unfiltered

modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/dependency/DependencyService.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/steward.scala, modules/core/src/main/scala/org/scalasteward/core/util/DateTimeAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/LogAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/dateTime.scala, modules/core/src/main/scala/org/scalasteward/core/util/logger.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/util/LogAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
This slowly replaces requirements of `Sync` in our algebras with other proper algebras.
=>  Replace LoggerOps with LogAlg 

repos.md
As the maintainer of http4s-directives, please update our deps =)
=> add scalabin-no/http4s-directives

repos.md
I am the maintainer of this project and would like to have scala-steward suggest dependency updates
=> Add kontainers/micrometer-akka

README.md
Hello,
I've just started to introduced Steward in my company, it's just a few project yet but I hope it's going to spread.
I won't hesitate to propose Pull Requests if we feel like we need more customisation !
Regards
=> Add iAdvize to the community

repos.md
https://github.com/daniel-shuy/sbt-release-mdoc
=> Add sbt-release-mdoc

repos.md
https://github.com/finagle/finagle-mysql-shapes
=> add finagle/finagle-mysql-shapes

modules/core/src/main/scala/org/scalasteward/core/model/Update.scala, modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
=> Ignore comment lines

repos.md
=> Add some japgolly projects to repo.md

modules/core/src/test/scala/org/scalasteward/core/model/UpdateTest.scala
=> Test replaceAllIn with backticks around the search term

modules/core/src/main/scala/org/scalasteward/core/io/package.scala
=> Update versions in .travis.yml files

repos.md
I moved my OSS projects to the [ProfunKtor organization](https://profunktor.dev/).
=> Updating repos moved to organization

README.md, repos.md
I think this is how it's done? Let me know. Added SlamData to the list of companies as well. You da best.
=> Added some djspiewak/ and slamdata/ repos

modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala
=> Remove InvalidVersions from Update.newerVersions

repos.md
=> Add lagom-silhouette integration

repos.md
I am not a maintainer but I work for softwaremill
=> Add sbt-softwaremill

modules/core/src/main/scala/org/scalasteward/core/model/Update.scala
This is an optimization that prevents running the same code again for
each source file scala-steward is trying to update the version number
in.
=> Do not call replaceAllInImpl for each source file

modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
closes https://github.com/fthomas/scala-steward/issues/502
=> Ignore strings that contain the version as proper substring

repos.md
https://github.com/holidaycheck/easy-akka-http
=> Add easy-akk-http

repos.md
https://github.com/stephennancekivell/scalatest-json
thanks :)
=> keep an eye on scalatest-json

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala, modules/core/src/test/scala/org/scalasteward/core/util/LogAlgTest.scala
... since we don't need a different implementation for tests.
=> Make Cli a class

modules/core/src/main/scala/org/scalasteward/core/scalafix/Migration.scala, modules/core/src/main/scala/org/scalasteward/core/scalafix/package.scala
as mentioned by @amarrella in https://github.com/fthomas/scala-steward/issues/149#issuecomment-447577179
=> Use newest version of the fs2 rule

repos.md
Hi @fthomas, could you please add [mwz/sbt-sonar](https://github.com/mwz/sbt-sonar) to scala-steward?
=> Add mwz/sbt-sonar

modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala
=> Fix Cogen[Version]

repos.md
Add Gemini Observatory repos to be tracked by scala-steward
/cc @tpolecat @swalker2m
=> Add Gemini Observatory repos to scala-steward

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
see https://github.com/metabookmarks/sbt-plantuml-plugin/pull/10
=> Ignore another plantuml version

repos.md
(Was unruh/qrhl-tool previously which does not exist)
=> Fixed name of dominique-unruh/qrhl-tool

repos.md
https://github.com/leanovate/play-mockws
=> add leanovate/play-mockws

repos.md
Would love to have scala-steward running on our projects. Thanks for the great work !
=> Adds cuttle and lolhttp

repos.md
https://ovotech.github.io/vulcan
=> Add ovotech/vulcan

README.md
Now that Bitbucket support is almost there and I am testing it at my company I would also like to add us to the list of companies using it.
=> Add Firstbird to Community

README.md
Here at [@springernature](https://github.com/springernature) we started using this fantastic tool last week!
Thanks a lot for your amazing work!
=> Add SpringerNature to Community Section in README

repos.md
=> Add fuuid-annotation

repos.md
=> Added henkan

repos.md
https://github.com/qbicsoftware/scark-cli
=> [FEATURE] Adding qbicsoftware/scark-cli

repos.md
https://ovotech.github.io/fs2-kafka
=> Add ovotech/fs2-kafka

modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
=> List applied Scalafix rules in the PR body.

repos.md
Add my personal project for the update check
=> Include wei-1's scala-machine-learning project

modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala
=> Log executed commands

repos.md
Thanks for an amazingly useful project! Looking forward to the first pull request.
=> Added projects from tmtsoftware organization

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
=> Prune repos config

repos.md
Also sort the sub-projects in ascending order
=> Add one more repo in tmtsoftware organization

repos.md
=> Add sbt-updates repository to the list

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
When checking if a PR needs to be reset, we now run some Git commands
only if needed.
=> shouldBeReset: run Git commands only if needed

modules/core/src/main/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala, modules/core/src/test/scala/org/scalasteward/core/gitlab/Http4sGitlabApiAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
see https://github.com/fthomas/scala-steward/issues/689
=> Fix createPullRequests with Gitlab --do-not-fork option

modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/data/Repo.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/RepoTest.scala
=> Changed Repo regex to handle GitLab's sub-group

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
=> change log message to cope with #724

modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala
=> Merge instead of reset/force-push to resolve conflicts

build.sbt, docs/running.md, modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala, scripts/run.sh
=> Add authorName default

docs/repo-specific-configuration.md
=> Document scala-steward:off|on markers.

repos.md
=> Replace scalaz-nio with zio-nio

repos.md
=> Add discipline-specs2 and discipline-scalatest

repos.md
Heres what the upgrade to try to allow the changes to proliferate looks like. 
My curiosity is whether it can find default.properties or if it only finds the sbt plugins.
https://github.com/ChristopherDavenport/library.g8/pull/5
=> Update Christopher Davenport g8 Template

repos.md
=> Add ccamel/poc-piper-worker-flink to repos.md

modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala
This PR fixes https://github.com/fthomas/scala-steward/issues/810
=> Ignore changes for git submodules when looking for changes

modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala, modules/core/src/test/scala/org/scalasteward/core/scalafmt/scalafmtTest.scala
Ref: https://github.com/scalameta/scalafmt/releases/tag/v2.0.1
=> Update latest scalafmt version to 2.0.1

modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala, modules/core/src/test/scala/org/scalasteward/core/scalafmt/scalafmtTest.scala
... so that we only need to change it in one place.
=> Use latestScalafmtVersion in test

repos.md
=> Add pathikrit/dijon

repos.md
=> add kind-projector, scalacheck

repos.md
=> Add ceedubs/irrec

modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This is a purely stylistic change
=> Reformat config snippet for ignoring updates

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
It replaces the hardcoded 10 minutes timeout. The default timeout is left unchanged.
=> Added --process-timeout option

repos.md
Would be great if you would include my repo Slakah/fastparse-parsers. Thanks again for developing this great tool!
=> Add Slakah/fastparse-parsers

repos.md
Java Time Algebras for Cats-Effect based on Timer
=> Add cats-effect-time

repos.md
=> Add `scala-start` project

repos.md
=> Add datadog4s

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
This changes `getArtifactUrl` to not fail in case of any error. The
reason for this change is that creating a PR should not fail because we
couldn't figure out the URL that is used in the PR body to link to the
updated dependency.
=> Make getArtifactUrl fail-safe

repos.md
https://github.com/xerial/sbt-pack
https://github.com/xeirial/sbt-sonatype
=> Add sbt-sontype, sbt-pack plugins

repos.md
https://github.com/wvlet/airframe
=> Add airframe

modules/core/src/main/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala, modules/core/src/test/scala/org/scalasteward/core/bitbucket/http4s/Http4sBitbucketApiAlgTest.scala
This targets #883 and is similar to the implementation for gitlab.
=> Bitbucket: change source branch owner if do-not-fork is true

repos.md
Hi,
Thanks a lot for your work on Scala Steward!
I am a maintainer of the added repository and I am looking forward to PR-s, should you decide to include this one too.
=> Add emartech/pure-scheduler to repos

build.sbt, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, project/Dependencies.scala
This needs more manual tests. I just wanted to know what code changes would be required to replace the Blaze client.
Closes #888
=> Use http4s-async-http-client

repos.md
note: I am one of the maintainers of [gfc-collective]
=> add [gfc-collective] repos

repos.md
https://github.com/ThoughtWorksInc/dsl-domains-cats
=> Add dsl-domains-cats

repos.md
(I think I'm doing this right?)
=> Add bkirwi/decline

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSExtraAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Closes #905
Example PR: https://github.com/exoego/scala-steward-test-project/pull/94
=> Add link to release note or changelog.

repos.md
It would be nice to use scala-steward for squants
=> Add squants to be tracked by scala-steward

repos.md
I know this is an sbt plugin, but I added the plugin it depends on to the the `plugins.sbt` as well.
So I believe this will catch those upgrades and send PR's.
If not, happy to keep it updated manually.
=> Add ChristopherDavenport/sbt-mima-version-check

docs/running.md
This is the setup that I got working after the support provided on Gitter: https://gitter.im/fthomas/scala-steward?at=5d77dc5b6e889c4bbdd1d29b
=> Add setup to run on Docker w/ Bitbucket

repos.md
L-space/L-space
L-space/L-space-NS
L-space/Types
=> Added L-space/(L-space/L-space-NS/Types)

modules/core/src/main/scala/org/scalasteward/core/update/UpdateService.scala
Kinda fixes #420 
and helps debugging #622
=> Use logger.error instead of println

modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
We use only algebras and not services in this codebase.
=> Rename UpdateService to UpdateAlg

repos.md
=> Added specs2 to the list

repos.md
I applied the edit to my fork but forgot to PR... 🙄
=> Add `sirthias/borer` to repos.md

repos.md
I would love @scala-steward help in maintaining my projects ❤️
=> Added support for DanielaSfregola/* libraries

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/test/scala/org/scalasteward/core/gitlab/http4s/Http4sGitlabApiAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
This allows me to better filter notifications where @scala-steward is
explicitly mentioned by a human.
=> Do not mention @scala-steward in the PR body

modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
=> Set dependencyUpdatesFailBuild to false

modules/core/src/main/scala/org/scalasteward/core/data/Version.scala, modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
=> Treat alpha and beta versions as pre-releases

modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/main/scala/org/scalasteward/core/io/process.scala, modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/io/processTest.scala
... instead of creating a new Blocker on every process.slurp call.
=> Use a single Blocker for the whole application

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/command.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
=> Remove keepCredentials option

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/data/ProcessResult.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala, modules/core/src/main/scala/org/scalasteward/core/util/package.scala, modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
as @exoego pointed out, 
closes #1046 
Adds support in repoConfig for limiting the amount of Updates.
=> add support for limiting updates through config

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/test/scala/org/scalasteward/core/nurture/NurtureAlgTest.scala
=> add sorting of updates so migration ones run last

modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSPackageTest.scala
Example PR with this change: https://github.com/fthomas/refined-sjs-example/pull/65
=> Add "ReleaseNotes" as possible filename for release notes

modules/core/src/main/scala/org/scalasteward/core/application/SupportedVCS.scala, modules/core/src/main/scala/org/scalasteward/core/bitbucketserver/http4s/Http4sBitbucketServerApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/package.scala
Bitbucket Server(formerly known as Stash) is a similarly named, but different product from Bitbucket, this PR adds support creating PRs.
=> Add support for Atlassian's Bitbucket Server aka Stash.

README.md
we at [LeadIQ](https://leadiq.com) have recently have started using scala-steward, thank-you for the great work 👍
=> add `LeadIQ` to the  companies using Scala-steward

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
=> default to hompeage on coursierAlg if url starts with git@

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
This uses the same filter for the SCM URL and home page.
=> Extract getScmUrlOrHomePage

README.md
Thank you for this project, it's a breeze and very simple to setup.
Saves a lot of time and effort.
=> Add Hellosoda to the list of users

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
=> CoursierAlg: Fetch ivy.xml files from sbt-plugin-releases

modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/package.scala, modules/core/src/test/scala/org/scalasteward/core/util/utilTest.scala
=> Replace our own evalFilter with fs2's

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
closes #1126 
Would like to hear some input in case i missed something!
WDYT @fthomas
=> add checkForUpdate Test and use coursier for getting updates

modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala
This code is dead since #1133.
=> Remove more dead code in sbt package object

modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
=> Take groupId changes in checkForUpdates into account

modules/core/src/main/scala/org/scalasteward/core/data/Version.scala, modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
=> Add order for Preview and B Alpha values on Version ordering

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/package.scala, modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
In the case of plantuml, this is easier than to list all bad versions.
=> Allow to mark version ranges as bad

modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
See https://github.com/fthomas/scala-steward/pull/1144 for context.
=> Split UpdateAlg so that it can be used in SbtAlg

build.sbt, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/data/Dependency.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
=> Replace withTemporarySbtDependency with findUpdate

modules/core/src/main/scala/org/scalasteward/core/sbt/parser.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala, modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
=> Use sbt's logger instead of println in tasks

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/main/scala/org/scalasteward/core/data/ArtifactId.scala, modules/core/src/main/scala/org/scalasteward/core/data/Update.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala
... and other smaller refactorings.
=> Move findUpdates to UpdateAlg

modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Example PR: https://github.com/ThoughtWorksInc/Binding.scala/pull/235
=> Edit files that end with .sbt.shared

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/HttpExistenceClient.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala, scripts/run.sh
This allows to tweak the TTL of Coursier's cache and the cache used in
HttpExistenceClient.
=> Add --cache-ttl CLI option

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
This was removed in #1196 but it leads to creating PRs for scala-library
because the filter for dependencies is only used in PruningAlg but not
in SbtAlg. This code can be removed again once getUpdates is removed
from SbtAlg.
=> Add FilterAlg.isIgnoredGlobally again

modules/core/src/main/scala/org/scalasteward/core/io/package.scala
This fixes a defect that was introduced in #1194.
=> Also update sbt if it is in Update.Group

modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
UpdateAlg.findUpdate involves file and maybe network calls and thus is a
good condidate for running in parallel.
=> Parallelize UpdateAlg.findUpdate

modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala
See https://github.com/typelevel/cats-collections/pull/267
=> Fix duplicated artifactIds in PR body

modules/core/src/main/scala/org/scalasteward/core/application/StewardAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
Uses `addGlobalPluginTemporarily` to ensure, that the plugins are cleaned up afterwards automatically.
fixes #855
=> Cleanup plugin installation automatically

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
=> Require a scheme in SCM URL to prevent the generation of relative URLs

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
=>  Change updatePullRequests config to be an enum(always, on-conflicts, never)

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/test/scala/org/scalasteward/core/coursier/CoursierAlgTest.scala
=> Search in the parent pom for an artifact uri, if the actual pom contains none

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
Resolves https://github.com/fthomas/scala-steward/pull/1238#discussion_r365684192
/cc @mzuehlke
=> Try to make CoursierAlg.getArtifactUrlImpl clearer

modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala, modules/core/src/test/scala/org/scalasteward/core/util/ChangeTest.scala, project/Dependencies.scala
Manual update is required
Supersedes #1246
=> Update discipline-scalatest to 1.0.0-RC4

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala
By not using the default cache policies we ensure that `cache` does not
download files if local ones are younger than the TTL.
=> Explicitly set Coursier's cache policies

scripts/run.sh
=> Run public instance for GitLab repositories

docs/faq.md
=> Add and entry to the FAQ: how to control version updates

modules/core/src/main/scala/org/scalasteward/core/persistence/JsonKeyValueStore.scala
We can't handle parsing or decoding errors meaningfully in an upper
layer, so we log them here and return no result.
=> Log parsing or decoding errors in JsonKeyValueStore

modules/core/src/main/scala/org/scalasteward/core/git/GitAlg.scala, modules/core/src/test/scala/org/scalasteward/core/git/GitAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
=> Fetch tags in GitAlg.syncFork

modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/sbt/package.scala, modules/core/src/test/scala/org/scalasteward/core/io/MockFileAlg.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/SbtAlgTest.scala
So that #1298 does not need to wait for #1309. /cc @kubukoz
=> Add FileAlg.readResource

README.md
Installing Scala Steward on our Gitlab instance wasn't that hard, in the end :)
=> Add Besedo to the community list

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/git/package.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Closes https://github.com/fthomas/scala-steward/issues/994
=> Add formatting options to commit messages

modules/core/src/main/scala/org/scalasteward/core/git/package.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/CommitsConfig.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala, modules/core/src/test/scala/org/scalasteward/core/git/gitTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
For the same reason as given in #1339.
=> Make commites.message optional

docs/faq.md
see #1286 (giter8 templates)
see #1311 (missing URLS in PRs)
=> Extend FAQ

README.md
Scala Steward helps us to update dependencies in time!
=> Add PlayQ to community list.

docs/running.md
=> document how to run from docker

modules/core/src/main/scala/org/scalasteward/core/coursier/CoursierAlg.scala, modules/core/src/main/scala/org/scalasteward/core/data/Resolver.scala, modules/core/src/test/scala/org/scalasteward/core/TestSyntax.scala, modules/core/src/test/scala/org/scalasteward/core/sbt/parserTest.scala, modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
=> Support sbt credentials for coursier

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfig.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
For the same reason as given in #1339.
=> Make RepoConfig.updatePullRequests optional

build.sbt, modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
Addresses #1340 
- I also changed the title of Ignore future updates section because we can use that part for repo specific conf examples
=> Add repo specific conf link to PR body

modules/core/src/main/scala/org/scalasteward/core/io/package.scala
Reverts fthomas/scala-steward#1380
Closes fthomas/scala-steward#1394
=> Revert "fix#1376: markdown files considered for library pattern updates"

modules/core/src/main/resources/group-migrations.conf, modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/update/GroupMigrations.scala, modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/update/GroupMigrationsTest.scala, modules/core/src/test/scala/org/scalasteward/core/update/UpdateAlgTest.scala, project/Dependencies.scala
=> Support custom group migrations

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/io/package.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala, modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
A user option to make it possible to change version numbers in text files. This will hopefully create not as many unrelated PRs as the last attempt.
fixes #1376
=> Introduce an option in the repository config for the file extension

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
=> Mark sort-imports_2.12 36845576 as bad

modules/core/src/main/resources/scalafix-migrations.conf, modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
https://github.com/scalaz/scalazfix
=> add scalafix rule for scalaz 7.3

modules/core/src/main/scala/org/scalasteward/core/io/process.scala
If they are not shown, it might suggest that they are not used by `slurp`.
=> Show env vars in slurp's error messages

modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/data/UpdateState.scala, modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
=> human readable format for `UpdateState`

modules/plugin/src/main/scala/org/scalasteward/plugin/StewardPlugin.scala
=> Fallback to credentials for sbt 1.2.x

modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala
See https://github.com/fthomas/scala-steward/pull/1478#issuecomment-648437637
Thanks to @hamnis for the fix.
=> Fix loading of scala-steward-mill-plugin in MillAlg

.travis.yml, build.sbt, modules/mill-plugin/src/main/scala-2.12/org/scalasteward/mill/plugin/package.scala, modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala, project/plugins.sbt
Picked up some tricks from reading the mill source.
Should in theory fix #1499 depending on how the mill script is handled.
=> Make plugin work for 0.6 and Scala 2.12 as well

docs/running.md
Thanks for the help in https://gitter.im/fthomas/scala-steward?at=5f053e5c6e1b8050c3dd58d8.
This PR adds the workaround to the docs so we won't have to debug the same issue twice. I tried to minimize as much as possible.
=> docs/running.md: Add sbt 0.13 + coursier workaround

README.md
=> Include Babylon Health in community list

modules/core/src/main/resources/scalafix-migrations.conf, modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationAlgTest.scala
Not yet release but will be soon, so it's good to have it ready before.
=> Add scalafix rules for upcoming 10.2.0 release

modules/core/src/main/resources/scalafix-migrations.conf
=> Sort Scalafix migrations and use more immutable references

modules/core/src/main/resources/scalafix-migrations.conf
See https://github.com/scala-steward-org/scala-steward/pull/1594#pullrequestreview-481642175
=> Update newVersion of Scalafix migration for Cats 2.2.0

modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
=> fix issue when value with version is a part of a long artifactId

docs/running.md
I have set up Scala Steward within our team using a self-hosted Gitlab instance. Since the procedure was not at all straight forward I thought I'd share the CI config and setup instructions here.
On a second thought, I could also set up an example project on Gitlab.com, in case you don't want to have this here. But that would mean a bit more work for me... ;-)
=> Note how to run Scala Steward on-prem with Gitlab

modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/main/scala/org/scalasteward/core/scalafix/MigrationsLoader.scala, modules/core/src/test/scala/org/scalasteward/core/io/MockProcessAlg.scala, modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/scalafix/MigrationsLoaderTest.scala
This puts process and sandbox related configuration in new `ProcessCfg`
and `SandboxCfg` classes. The benefit here is that we only pass needed
configuratin to `ProcessAlg`.
=> Group process and sandbox related configuration

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
I forgot to delete this in #1265.
=> Remove unused Config.cacheMissDelay

modules/core/src/main/scala/org/scalasteward/core/repoconfig/RepoConfigAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala
This also prevents merging configs if there is no default config
specified.
=> DRY loading and merging the default repo config

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala, modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
... since `localFilter` calls `globalFilter` and the former is the main
function used in `FilterAlg`.
=> Test FilterAlg.localFilter instead of FilterAlg.globalFilter

modules/core/src/main/scala/org/scalasteward/core/scalafmt/ScalafmtAlg.scala, modules/core/src/test/scala/org/scalasteward/core/scalafmt/ScalafmtAlgTest.scala
```
$ scalafmt --help
scalafmt 2.7.5
...
--non-interactive        disable fancy progress bar, useful in ci or sbt plugin.
```
=> Run scalafmt with --non-interactive

modules/core/src/main/scala/org/scalasteward/core/data/Version.scala, modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
=> Recognize NIGHTLY as pre-release identifier

modules/core/src/test/scala/org/scalasteward/core/util/dateTimeTest.scala
=> Use approximate equality for parseFiniteDuration test

modules/core/src/main/resources/artifact-migrations.conf
This is the first artifactId migration in the config file, so I'm not 100% sure this syntax is correct.
=> add scalacheck-1-14 → scalacheck-1-15 migration

modules/core/src/main/scala/org/scalasteward/core/application/Config.scala
As noted by @xuwei-k in https://github.com/scala-steward-org/scala-steward/pull/1719#discussion_r519446225.
=> Fix setting enableSandbox from Cli.Args

README.md, modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala, modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
This PR adds some additional tests and a documentation breadcrumb for follow up to [this PR ](https://github.com/scala-steward-org/scala-steward/pull/1686)
=> Find migrations tests and docs

modules/core/src/main/scala/org/scalasteward/core/io/ProcessAlg.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/BuildToolDispatcherTest.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/sbt/SbtAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala, modules/core/src/test/scala/org/scalasteward/core/io/ProcessAlgTest.scala, scripts/run.sh
This fixes parsing the output of `mill` in `MillAlg.getDependencies`.
=> Run firejail with --quiet option

modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
The tests are failing locally for bizarre reasons. It seems like the paths are not be canonicalized within the mock state machinery.
=> Added sbt-spiewak to the post-update hooks

modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala
Closes https://github.com/scala-steward-org/scala-steward/issues/1753.
=> Add bad versions of commons-codec and commons-io

.github/workflows/ci.yml, build.sbt
sbt-ci-release 1.5.5 should now work with gpg2.
=> Remove olafurpg/setup-gpg

modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
Per @fthomas's [helpful suggestion](https://github.com/http4s/http4s/pull/3981#issuecomment-739419625)
=> Add sbt-http4s-org to knownGitHubActions

modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala
Example commit: https://github.com/fthomas/scalafix-test/pull/75/commits/bbc7b38c1262d7d75a147d12c2f48c2fd71e2484
=> Add Scalafix documentation URL to commit body

modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/main/scala/org/scalasteward/core/git/package.scala
... since it is only used in `FileGitAlg`.
=> Move dotdot function to FileGitAlg companion

modules/core/src/main/resources/scalafix-migrations.conf
=> add scalafix for cats-parse 0.3.0

modules/core/src/main/scala/org/scalasteward/core/nurture/PullRequestRepository.scala, modules/core/src/main/scala/org/scalasteward/core/update/PruningAlg.scala, modules/core/src/test/scala/org/scalasteward/core/nurture/PullRequestRepositoryTest.scala
Closes https://github.com/scala-steward-org/scala-steward/issues/1831.
=> Change findPullRequest to findLatestPullRequests

modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/main/scala/org/scalasteward/core/git/GenGitAlg.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
=> remove branch (local and remote) when closing an outdated PR

modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala
=> Don't remove the local branch. It doesn't exist anymore

modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/data/NewPullRequestDataTest.scala
=> Show the old version in oldVersionNote

docs/help.md, docs/running.md
A first attempt at documenting all CLI arguments.
I'm open for other formatting ideas. 
Sadly [casa-app](https://github.com/alexarchambault/case-app) does not provide a markdown help on its own.
=> Add minimal CLI help

modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/util/logger.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSRepoAlg.scala
Fixes https://github.com/scala-steward-org/scala-steward/pull/1846#commitcomment-45500521
=> Ignore error if removing remote branch fails

modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
=> git fetch with --force

modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala
=> Use common naming convention for bitbucketserver.JSON

modules/core/src/main/scala/org/scalasteward/core/util/HttpJsonClient.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/VCSSelection.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Json.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucketserver/Url.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucketserver/BitbucketServerApiAlgTest.scala
Maybe closes #1859. Needs more manual tests.
=> Fix BitbucketServerApiAlg.closePullRequest

modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
=> Create branch only if version can be bumped

modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
This removes `Sync` from `Config.vcsUser` and makes it testable by using
`ProcessAlg` and `WorkspaceAlg`.
=> Remove Sync from Config.vcsUser

modules/core/src/test/scala/org/scalasteward/core/application/StewardAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
I'm curious how much coverage changes with this "test".
=> Test that runF returns ExitCode.Success

modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala
Indicate in the Scalafix commit message if the execution of Scalafix was "Failed" or got "Applied"
See https://github.com/scala-steward-org/scala-steward/pull/1878#issuecomment-759377719
=> More precise Scalafix commit msg

modules/core/src/main/resources/artifact-migrations.conf
https://github.com/sbt/sbt-pgp/pull/186
https://github.com/sbt/sbt-pgp/releases/tag/v2.1.2-M1
https://repo1.maven.org/maven2/com/github/sbt/sbt-pgp_2.12_1.0/
https://github.com/sbt/sbt/issues/6294
/cc @eed3si9n
=> add sbt-pgp in artifact-migrations.conf

modules/core/src/main/resources/artifact-migrations.conf
See https://github.com/scala-steward-org/scala-steward/pull/1929#issuecomment-779014539.
=> Update initialVersion of sbt-pgp artifact migration

modules/core/src/main/scala/org/scalasteward/core/vcs/bitbucket/json.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/BitbucketApiAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/bitbucket/JsonCodecTest.scala
Also add a test for the JSON decoding of PRs from Bitbucket API responses
=> Extract correct PR URL from Bitbucket API response

modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
=> Verify that #960 has been fixed by #1946

modules/core/src/main/resources/artifact-migrations.conf
- https://github.com/sbt/sbt-release/pull/278
- https://repo1.maven.org/maven2/com/github/sbt/sbt-release_2.12_1.0/
=> add sbt-release in artifact-migrations.conf

build.sbt
prepare sbt 1.5 https://github.com/sbt/sbt/pull/6328
=> use slash syntax instead of "in"

modules/core/src/main/resources/artifact-migrations.conf
- https://github.com/sbt/sbt-protobuf/pull/74
- https://repo1.maven.org/maven2/com/github/sbt/sbt-protobuf_2.12_1.0/
=> add sbt-protobuf in artifact-migrations.conf

modules/core/src/main/resources/artifact-migrations.conf
- https://github.com/jwt-scala/jwt-scala/blob/6.0.0/build.sbt#L80
- https://github.com/jwt-scala/jwt-scala/blob/v5.0.0/build.sbt#L62
- https://repo1.maven.org/maven2/com/pauldijou/
- https://repo1.maven.org/maven2/com/github/jwt-scala/
- https://github.com/jwt-scala/jwt-scala/compare/v5.0.0...6.0.0#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91L62
/cc @erwan
=> add jwt-scala in artifact-migrations.conf

modules/core/src/main/scala/org/scalasteward/core/data/package.scala, modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/FilterAlg.scala, modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala
Example PR: https://github.com/scala-steward-org/test-repo-2/pull/25
Closes #1984.
=> Run 'sbt githubWorkflowGenerate' on Scala updates

docs/faq.md
I've included a mention to a GitHub action I created which enables automatic merging of Scala Steward PRs.
=> Add merge PR action to FAQ

modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockConfig.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSRepoAlgTest.scala
=> Bypass all Git hooks by setting hooksPath to /dev/null

modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/data/Update.scala, modules/core/src/main/scala/org/scalasteward/core/git/Sha1.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/PullRequestUpdateStrategy.scala
This fixes some errors reported by Scala 3 (see https://github.com/scala-steward-org/scala-steward/pull/2065/checks?check_run_id=2383524444).
=> Fix some Scala 3 errors

modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala
This selects the `replaceVersion` implementation based on the specific update.
=> Tweak 'specific' update heuristic

modules/core/src/main/resources/artifact-migrations.conf
- https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-refined_6.3_2.13/
- https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-refined_6.2_2.13/
- https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.3_2.13/ 
- https://repo1.maven.org/maven2/com/github/alexarchambault/argonaut-shapeless_6.2_2.13/
- https://repo1.maven.org/maven2/com/github/alexarchambault/scalacheck-shapeless_1.15_2.13/
- https://repo1.maven.org/maven2/com/github/alexarchambault/scalacheck-shapeless_1.14_2.13/
/cc @alexarchambault
=> add alexarchambault libraries in artifact-migrations.conf

README.md
=> Teads is now using Scala Steward internally

modules/core/src/test/scala/org/scalasteward/core/update/PruningAlgTest.scala
Reverts scala-steward-org/scala-steward#2226
=> Revert "Update scala-library to 2.12.15"

modules/core/src/main/resources/artifact-migrations.conf
See https://github.com/polyvariant/better-tostring/pull/75.
I will un-draft when the version is synced to Central :)
=> Add artifact migration for better-tostring

modules/core/src/main/resources/artifact-migrations.conf
See https://twitter.com/olafurpg/status/1440724122535743500
/cc @olafurpg @eed3si9n @SethTisue
=> Add artifact migration for sbt-ci-release

modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/test/scala/org/scalasteward/core/edit/EditAlgTest.scala
=> Improved content parser for .mill-version file

modules/core/src/main/resources/artifact-migrations.conf
=> guardrail artifacts have changed organization

modules/core/src/main/scala/org/scalasteward/core/edit/UpdateHeuristic.scala, modules/core/src/test/scala/org/scalasteward/core/edit/UpdateHeuristicTest.scala
Reverts scala-steward-org/scala-steward#2232
=> Revert "Support multi-line artifact and version"

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
Only one of them needs to be public.
=> Make methods in NurtureAlg private

modules/core/src/main/resources/artifact-migrations.conf
See https://github.com/typelevel/cats-time/pull/314
=> Add migration of groupId for cats-time

docs/repo-specific-configuration.md, modules/benchmark/src/main/scala/org/scalasteward/benchmark/UpdatesConfigBenchmark.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatePattern.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala, modules/core/src/test/scala/org/scalasteward/core/TestInstances.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/UpdatesConfigTest.scala, modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
... and document the `exact` field.
=> Move UpdatePattern.Version to VersionPattern

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/repoconfig/VersionPattern.scala, modules/core/src/test/scala/org/scalasteward/core/update/FilterAlgTest.scala
=> Add 'contains' matcher to VersionPattern

modules/core/src/main/scala/org/scalasteward/core/vcs/data/NewPullRequestData.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/data/UpdateState.scala
It has nothing to do with `NewPullRequestData`.
=> Move `UpdateState` into its own file

modules/core/src/main/resources/artifact-migrations.conf
See https://github.com/sbt/sbt-proguard/pull/47
=> Add artifact migration for sbt-proguard

build.sbt, modules/core/src/main/scala/org/scalasteward/core/application/Context.scala, modules/core/src/main/scala/org/scalasteward/core/client/ClientConfiguration.scala, modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala, modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala, modules/core/src/test/scala/org/scalasteward/core/vcs/VCSExtraAlgTest.scala, project/Dependencies.scala
=> fix: do not follow redirect when checking urls

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
=> Fix sandbox disabling

build.sbt
Closes #2248 
Maybe better to add `COURSIER_PROGRESS=false` to `SbtAlg` 🤔
=> Disable progress to potentially speed up on multi-module project

docs/artifact-migrations.md, modules/docs/mdoc/artifact-migrations.md
Fixes #2231
See https://github.com/scala-steward-org/scala-steward/pull/2216#issuecomment-918947235
=> Extend note for artifact migrations with comment about initial version.

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/repoconfig/PostUpdateHookConfig.scala, modules/core/src/test/scala/org/scalasteward/core/edit/hooks/HookExecutorTest.scala, modules/core/src/test/scala/org/scalasteward/core/repoconfig/RepoConfigAlgTest.scala
Spotted by @fthomas:https://github.com/scala-steward-org/scala-steward/pull/2434#discussion_r776669075
=> User supplied hooks should always be executed in a sandbox

modules/core/src/main/resources/artifact-migrations.conf
Reverts scala-steward-org/scala-steward#2447
=> Revert "Add artifact migration for sbt-twirl"

modules/core/src/main/resources/default.scala-steward.conf
~not for merge yet...~ GO GO GO
=> Release the 2.13.8 kraken!

modules/core/src/main/resources/artifact-migrations.conf
Reverts scala-steward-org/scala-steward#2448
@mkurz Please comment here when 1.6.0 is released.
=> Revert "Revert "Add artifact migration for sbt-twirl""

modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala, modules/core/src/main/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinder.scala, modules/core/src/test/scala/org/scalasteward/core/update/artifact/ArtifactMigrationsFinderTest.scala
Some refactorings in `UpdateAlg` to reduce the line count.
=> Refactor UpdateAlg

modules/core/src/main/resources/artifact-migrations.v2.conf
- https://repo1.maven.org/maven2/org/scalatestplus/testng-6-7_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/testng-7-5_2.13/
- https://github.com/scalatest/scalatestplus-testng/pull/19
=> add scalatestplus testng in `artifact-migrations.v2.conf`

modules/core/src/main/scala/org/scalasteward/core/update/UpdateAlg.scala
This uses `parTraverseFilter` instead of `traverseFilter` for finding
updates in `UpdateAlg`. It makes no difference when versions are
obtained from the cache, but can be a significant speed-up if they
are obtained from Coursier.
Here are the total runtimes for working on the scala-steward repo
itself with an empty and fresh cache compared to the main branch:
```
this branch with an empty cache:
Total time: Steward scala-steward-org/scala-steward: 3s 69ms
Total time: Steward scala-steward-org/scala-steward: 3s 219ms
Total time: Steward scala-steward-org/scala-steward: 3s 16ms
this branch with a fresh cache:
Total time: Steward scala-steward-org/scala-steward: 1s 147ms
Total time: Steward scala-steward-org/scala-steward: 974ms
Total time: Steward scala-steward-org/scala-steward: 1s 46ms …
```
=> Parallelize `UpdateAlg.findUpdates`

modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/vcs/github/GitHubException.scala
This will come in handy when fixing #2355.
=> Add SecondaryRateLimitExceeded exception

modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
cc @cquiroz
Thanks, these post-update hooks are a life-saver! :)
=> Register sbt-lucuma hooks

project/Dependencies.scala
=> Update coursier to 2.1.0-M5-5-g2cb552ea9

modules/core/src/main/resources/artifact-migrations.v2.conf
See https://github.com/sbt/sbt-git/pull/205
=> Add artifact migration for sbt-git

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.1.2

modules/core/src/main/resources/artifact-migrations.v2.conf
See https://github.com/playframework/play-soap/pull/313
=> Add artifact migration for sbt-play-soap

modules/core/src/main/resources/artifact-migrations.v2.conf
- https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-16_2.13/
- https://repo1.maven.org/maven2/org/scalatestplus/scalacheck-1-15_2.13/
=> add artifact-migrations for `org.scalatestplus scalacheck`

modules/core/src/main/resources/artifact-migrations.v2.conf
=> Add an artifact migration for sbt-tpolecat

modules/core/src/main/resources/artifact-migrations.v2.conf
See https://github.com/playframework/play-file-watch/pull/169
Thanks!
=> Add artifact migration for play-file-watch

modules/core/src/main/resources/artifact-migrations.v2.conf
Changed in https://github.com/playframework/play-socket.io/pull/214
=> Add artifact migration for play-socket-io

modules/core/src/main/resources/artifact-migrations.v2.conf, modules/core/src/main/resources/scalafix-migrations.conf
See https://github.com/typelevel/catbird/issues/341 and https://github.com/typelevel/catbird/pull/384.
=> Migrate catbird artifacts to org.typelevel

modules/core/src/main/resources/scalafix-migrations.conf
Hopefully solves #2616 after #2615
=> Fix missing comma in catbird config

modules/core/src/main/resources/artifact-migrations.v2.conf
=> fix `artifact-migrations.v2.conf`

modules/core/src/test/scala/org/scalasteward/core/BuiltinConfigFilesTest.scala
To prevent issues like #2616
Maybe it is better to have a dedicated sbt sub-project for this test, but I want to add this ASAP.
Let's consider such refactoring later.
=> Check files frequently updated by community

modules/core/src/test/scala/org/scalasteward/core/mock/MockContext.scala
See https://github.com/scala-steward-org/scala-steward/pull/2619#issuecomment-1148273848
=> Use the current artifact migrations file in MockContext

modules/sbt-plugin/src/main/scala/org/scalasteward/sbt/plugin/StewardPlugin.scala
Some repository providers use the same host URL for multiple repositories.
Repositories are differentiated by sub-paths.
In the current implementation, Scala Steward uses the first set of credentials that fits the host name.
This leads to all other repositories under the same base path to have invalid credentials.
This PR attempts to solve this issue by matching realm names first and falling back onto the original logic if such a match cannot be made.
Example credentials file
```
credentials += Credentials("Private Repository: org/repo1", "pkgs.org.io", "token", "ABC")
credentials += Credentials("Private Repository: org/repo2, "pkgs.org.io", "token", "DEF")
```
Example build.sbt
```
resolvers += "Private repository: org/repo1" at "https://pkgs.org.io/basic/repo1/maven/"
resolvers += …
```
=> SBT plugin: Find credentials by realms if possible

build.sbt, project/Dependencies.scala
Supersedes https://github.com/scala-steward-org/scala-steward/pull/2591
=> Bump jjwt-api 

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.1.3

modules/core/src/main/resources/default.scala-steward.conf
=> Add post-update hook for sbt-header

README.md
Accodring to [the discussion](https://github.com/VirtusLab/akka-serialization-helper/issues/185#issuecomment-1181487305)
=> Adding VirtusLab to README.md file

modules/core/src/main/resources/artifact-migrations.v2.conf
Sorry, I forgot some extra artifact migrations!
=> Add missing t4c artifact migrations

modules/mill-plugin/src/main/scala/org/scalasteward/mill/plugin/StewardPlugin.scala
=> Fix mill `headers` serialization

.github/workflows/ci.yml, .mergify.yml, build.sbt
=> Update to scala-library to 2.12.17

.github/workflows/ci.yml, .mergify.yml, build.sbt
Supersedes https://github.com/scala-steward-org/scala-steward/pull/2727
=> Update to scala-library to 2.13.10

project/Dependencies.scala
There are some issues in logback-classic 1.4.x https://github.com/scala-steward-org/scala-steward/pull/2719
Let's use 1.3.x first and see what is happening.
=> Update logback-classic to 1.3.4

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.2.1

modules/core/src/test/scala/org/scalasteward/core/vcs/github/GitHubApiAlgTest.scala
CodeCov started complaining on files unchanged in PRs.
https://github.com/scala-steward-org/scala-steward/pull/2780/checks?check_run_id=9566325577
This PR increases coverage so I hope CodeCov stop complain.
=> Increase coverage

modules/core/src/main/scala/org/scalasteward/core/util/UrlChecker.scala, project/Dependencies.scala
Supersedes https://github.com/scala-steward-org/scala-steward/pull/2340
=> Update scalacache-caffeine to 1.0.0-M6 

build.sbt
Uncomment this to enable remote debugging.
=> Add commented java options for remote debugging

modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/command.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
=> fix(maven): exclude transitive deps for Maven

build.sbt
Sorry for not doing it sooner!
=> Add Alejandro to the list of maintainers

.github/workflows/ci.yml, build.sbt
... so that its directories are created under "modules" as are the directories of the other projects.
=> Make dummy a cross project

modules/core/src/main/resources/artifact-migrations.v2.conf
https://github.com/sbt/sbt-ghpages/commit/77ad23db61a09f07615fa967d29b6f9b33cfe948
=> Add artifact migration for sbt-ghpages

modules/core/src/main/scala/org/scalasteward/core/io/process.scala
=> Use `Sync[F].blocking` for creating system processes

modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/test/scala/org/scalasteward/core/application/CliTest.scala
Follow-up of https://github.com/scala-steward-org/scala-steward/pull/2837
=> Remove redundant validation

README.md
Let's add Wiringbits as an adopter.
=> Update README.md -> Community

modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/MavenAlg.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/command.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/maven/package.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala, modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/package.scala, modules/core/src/main/scala/org/scalasteward/core/edit/EditAlg.scala, modules/core/src/main/scala/org/scalasteward/core/io/FileAlg.scala, modules/core/src/main/scala/org/scalasteward/core/io/package.scala, modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala, modules/core/src/main/scala/org/scalasteward/core/scalafmt/package.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/maven/MavenAlgTest.scala
=> Extract small refactorings from #2816

modules/core/src/main/scala/org/scalasteward/core/data/Version.scala, modules/core/src/test/scala/org/scalasteward/core/data/VersionTest.scala
Taking a quick first pass. Happy to iterate based on feedback.
=> Issue #2866: add FEAT to pre-release identifiers

docs/faq.md, modules/docs/mdoc/faq.md
Following a chat on Discord.
Happy to take notes on the wording.
=> Add a note to FAQ about persisting workspace

modules/core/src/main/resources/artifact-migrations.v2.conf
fyi @ennru (note that Frank assures me it's not too early to do this, even though there isn't a 1.5.0 final release yet)
@fthomas thanks for the suggestion on Mastodon
=> sbt-site is changing orgs

build.sbt, modules/core/src/test/scala/org/scalasteward/core/client/ClientConfigurationTest.scala, project/Dependencies.scala
Since blaze is schismed, it may lag on the milestone releases, but ember is in sync with core.
=> Use ember server for tests

modules/core/src/main/resources/artifact-migrations.v2.conf
See https://github.com/sbt/sbt-github-actions/issues/132
=> Add sbt-github-actions artifact migration

modules/core/src/main/scala/org/scalasteward/core/application/Context.scala
This is a cheap trick to increase coverage.
=> Change Context.printBanner to a field

modules/core/src/main/resources/artifact-migrations.v2.conf
- https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.32/
- https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.32/
- https://github.com/mysql/mysql-connector-j/commit/02b704c0bc4080506b80792a6a4eb4b316cd4f05#diff-118e71f89ee4e84ed88d35d5af39e1cebdc0eeb61a29c862f9815761397f1482R42
- https://github.com/mysql/mysql-connector-j/blob/fa4912a849140828e48162a2c396c8df0091bed7/src/build/misc/pom-relocation.xml#L42
=> add mysql-connector-j in artifact-migrations

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.2.2

modules/core/src/main/scala/org/scalasteward/core/edit/update/Selector.scala, modules/core/src/test/scala/org/scalasteward/core/edit/RewriteTest.scala
=> Update `.scalafmt.conf` and `.mill-version` also in subdirectories

docs/help.md, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/forge/ForgeSelection.scala, modules/core/src/main/scala/org/scalasteward/core/forge/ForgeType.scala, modules/core/src/main/scala/org/scalasteward/core/forge/gitea/GiteaApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/forge/gitea/Url.scala, modules/core/src/main/scala/org/scalasteward/core/forge/package.scala, modules/core/src/main/scala/org/scalasteward/core/nurture/UpdateInfoUrlFinder.scala, modules/core/src/test/scala/org/scalasteward/core/forge/gitea/GiteaApiAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/forge/gitea/UrlTest.scala
=> vcs: add gitea

modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlgTest.scala
=> Run Scala CLI with `--power`

docs/help.md, modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlg.scala, modules/core/src/main/scala/org/scalasteward/core/forge/gitlab/Url.scala, modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/GitLabApiAlgTest.scala, modules/core/src/test/scala/org/scalasteward/core/forge/gitlab/MergeRequestPayloadTest.scala
Fixes #3006 
Once we agree that this is a useful feature to add, I can update the relevant tests etc.
=> #3006 Support for removing source branch on GitLab merge requests

modules/core/src/main/resources/artifact-migrations.v2.conf
Ref https://github.com/sbt/sbt-license-report/releases/tag/v1.3.0
=> Notify groupId change for sbt-license-report

modules/core/src/main/resources/artifact-migrations.v2.conf
Ref https://github.com/sbt/sbt-sdlc/releases/tag/v0.3.0
=> Notify groupId change of sbt-sdlc

project/Dependencies.scala
=> update cats-effect and fs2 together

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.3.0

modules/core/src/main/scala/org/scalasteward/core/edit/hooks/HookExecutor.scala
- https://github.com/scala-steward-org/scala-steward/pull/2914
- https://github.com/sbt/sbt-github-actions/issues/132
=> add `sbt-github-actions` in `HookExecutor` with new groupId

modules/core/src/main/resources/default.scala-steward.conf
=> Release the Scala 2.12.18 kraken!

modules/core/src/main/resources/default.scala-steward.conf
=> Release the Scala 2.13.11 kraken!

modules/core/src/main/scala/org/scalasteward/core/buildtool/mill/MillAlg.scala, modules/core/src/test/scala/org/scalasteward/core/buildtool/mill/MillAlgTest.scala
This address the issues discussed in https://github.com/scala-steward-org/scala-steward/pull/3083
=> Different execution for mill 0.11

modules/core/src/main/resources/scalafix-migrations.conf
Add migrations for `prometheus4cats` 2.0
=> Add migrations for `prometheus4cats` 2.0

modules/core/src/main/resources/default.scala-steward.conf
=> Update Scala to 3.3.1

modules/core/src/main/resources/default.scala-steward.conf
Artifacts that are ignored because they are not yet announced are at the top and broken artifacts are listed below them.
=> Reorganize updates.ignore entries

modules/core/src/main/resources/artifact-migrations.v2.conf
=> Play 3 will migrate to new groupId (Akka -> Pekko)

modules/core/src/main/scala/org/scalasteward/core/buildtool/scalacli/ScalaCliAlg.scala
Follow-up to https://github.com/scala-steward-org/scala-steward/pull/3188#discussion_r1416774935.
=> Add `toolkit` to list of scala-cli directives

modules/core/src/main/resources/artifact-migrations.v2.conf
See https://github.com/playframework/play-grpc/commit/2053af69bf4b1e8d775199077eec090736f82b5d
=> `play-grpc` changed groupid to `org.playframework`

docs/faq.md, modules/docs/mdoc/faq.md
Add a FAQ entry on how to control updates of the Scala version.
=> Document how to control Scala updates

modules/core/src/main/resources/artifact-migrations.v2.conf
Rename `org.typelevel:otel4s-java*` to `org.typelevel:otel4s-oteljava*`.
=> Rename `otel4s-java*` to `otel4s-oteljava*`

modules/core/src/main/resources/default.scala-steward.conf
See: https://github.com/circe/circe-yaml/issues/402
Most pull-request have probably been already created.
https://github.com/pulls?q=author%3Ascala-steward+is%3Apr+sort%3Aupdated-desc+circe-yaml+1.15.0
/cc @armanbilge
=> Ignore circe-yaml 1.15.0

modules/core/src/main/resources/artifact-migrations.v2.conf
See
- https://github.com/sbt/sbt-multi-jvm/releases/tag/v0.5.0
=> Migrate sbt-multi-jvm

modules/core/src/main/resources/artifact-migrations.v2.conf
See 
- https://github.com/sbt/sbt-boilerplate/pull/39
=> Migrate sbt-boilerplate

modules/core/src/main/resources/artifact-migrations.v2.conf
* https://github.com/johanandren/sbt-akka-version-check/commit/623017edb047435b3a587e2db8b5a9c2682d69d9
* https://repo1.maven.org/maven2/com/markatta/sbt-akka-version-check_2.12_1.0/0.2/sbt-akka-version-check-0.2.pom
* https://github.com/johanandren/sbt-akka-version-check/pull/2
* https://github.com/johanandren/sbt-akka-version-check/releases/tag/v0.2
* https://github.com/playframework/playframework/pull/12339
=> Migrate `sbt-akka-version-check`

docs/help.md, modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala
See https://github.com/VirtusLab/scala-steward-repos/issues/98#issuecomment-1929368687
=> Increase default `--max-buffer-size`

modules/core/src/main/resources/default.scala-steward.conf
Users should not be updated to non-LTS versions automatically
see #3302
=> Ignore any non LTS version

modules/core/src/main/resources/artifact-migrations.v2.conf
Follows https://github.com/VirtusLab/scala-steward-repos/pull/377.
=> Migrate com.sksamuel.elastic4s to nl.gn0s1s

project/Dependencies.scala
- discipline-munit 1.0.9 -> 2.0.0
- munit 0.7.29 -> 1.0.0
- munit-scalacheck 0.7.29 -> 1.0.0
- munit-cats-effect(-3) 1.0.7 -> 2.0.0
closes #3362
closes #3363
closes #3364
=> Update all munit related dependencies

modules/core/src/main/resources/artifact-migrations.v2.conf
See: https://github.com/polyvariant/sttp-oauth2/issues/477
@majk-p
=> Add migrations for `sttp-oauth2`

modules/core/src/main/resources/default.scala-steward.conf
=> un-embargo Scala 2.12.20

docs/repo-specific-configuration.md, modules/core/src/main/scala/org/scalasteward/core/repoconfig/UpdatesConfig.scala
=> Add `.sdkmanrc` to the default file extensions of files to update

.github/workflows/ci.yml, .mergify.yml, build.sbt
Addresses https://github.com/scala-steward-org/scala-steward/issues/2590
See: https://adoptium.net/supported-platforms/ for architecture matrix
=> Add multi-arch image support by moving to temurin 21

docs/help.md, modules/core/src/main/scala/org/scalasteward/core/application/Cli.scala, modules/core/src/main/scala/org/scalasteward/core/application/Config.scala, modules/core/src/main/scala/org/scalasteward/core/git/FileGitAlg.scala, modules/core/src/test/scala/org/scalasteward/core/mock/MockState.scala
=> Add option for --signoff

modules/core/src/main/resources/default.scala-steward.conf, modules/core/src/main/scala/org/scalasteward/core/data/package.scala
To prevent pull request like: https://github.com/typelevel/doobie/pull/2120
These libs probably got added since https://github.com/scala-steward-org/sbt-plugin/pull/61
=> Add tasty-core to the list of scala libs

.github/workflows/ci.yml, build.sbt
Similar to https://github.com/fthomas/fs2-cron/pull/532
@fthomas I can not add a secret to the repo
=> Switch to codecov action v4 using a token to upload

build.sbt, project/Dependencies.scala
See https://github.com/scala-steward-org/scala-steward/pull/3464#issuecomment-2565268731
=> Use Mill script from `com-lihaoyi/mill` for the Docker image

modules/core/src/main/resources/default.scala-steward.conf
=> Release the Scala 2.13.16 kraken!!

modules/core/src/main/resources/default.scala-steward.conf
=> Retract sbt 1.10.8

README.md
=> Add company to community section

modules/core/src/main/scala/org/scalasteward/core/nurture/NurtureAlg.scala
In GitHub comments, when a list element contains a pull request (`#1234`), GitHub will render its title.
It would be nice if Scala steward could use this feature so on first sight we could see what the new PR actually is called:
<kbd><img width="400" src="https://github.com/user-attachments/assets/7181bbf8-3c74-4169-8162-bd322342bec5" /></kbd>
:point_down: 
<kbd><img width="400" src="https://github.com/user-attachments/assets/ea6560a8-1582-4c49-8938-b7cd6be39c40" /></kbd>
Tested locally:
- Original behaviour: https://github.com/mkurz/scala-steward-pr-title/pull/1
- With patch applied: https://github.com/mkurz/scala-steward-pr-title/pull/3
=> Make GitHub render an obsolete PR's title

modules/core/src/main/resources/default.scala-steward.conf
https://github.com/disneystreaming/smithy4s/issues/1792
=> Retract smithy4s 0.18.40
